SPUC: SPUC::iir_df< Numeric, Coeff > Class Template Reference
SPUC::iir_df< Numeric, Coeff > Class Template Reference
SPUC double templates | IIR filters
Template Class for Modeling a Direct Form IIR.
#include <iir_df.h>
Public Member Functions
void reset ()
Reset.
Numeric out ()
Get current output.
~iir_df (void)
iir_df (const char *filep, const char *filez)
Constructor.
iir_df (const iir_df< Numeric, Coeff > &cp)
Numeric clock (Numeric in)
Numeric update (Numeric in)
void print (void)
Public Attributes
fir< Numeric, Coeff > poles
fir< Numeric, Coeff > zeros
Numeric output
int err
Detailed Description
template<class Numeric, class Coeff = float_type>
class SPUC::iir_df< Numeric, Coeff >
Template Class for Modeling a Direct Form IIR.
Template works for float_type, long, complex, etc Taps for FIR and IIR parts are typically loaded from two seperate files Assumed that IIR part Tap 0 = 1 and is not in file. Implemented as cascade of FIR part followed by IIR part IIR function implemented with FIR class using special iir function
Author
Tony Kirke
Constructor & Destructor Documentation
template<class Numeric , class Coeff = float_type> SPUC::iir_df< Numeric, Coeff >::~iir_df (void) inline
template<class Numeric , class Coeff = float_type> SPUC::iir_df< Numeric, Coeff >::iir_df (const char * filep, const char * filez) inline
Constructor.
References SPUC::fir< Numeric, Coeff >::read_taps().
template<class Numeric , class Coeff = float_type> SPUC::iir_df< Numeric, Coeff >::iir_df (const iir_df< Numeric, Coeff > & cp) inline
References SPUC::fir< Numeric, Coeff >::coeff.
Member Function Documentation
template<class Numeric , class Coeff = float_type> Numeric SPUC::iir_df< Numeric, Coeff >::clock (Numeric in) inline
References SPUC::iir_df< Numeric, Coeff >::update().
template<class Numeric , class Coeff = float_type> Numeric SPUC::iir_df< Numeric, Coeff >::out () inline
Get current output.
template<class Numeric , class Coeff = float_type> void SPUC::iir_df< Numeric, Coeff >::print (void) inline
References SPUC::fir< Numeric, Coeff >::print().
template<class Numeric , class Coeff = float_type> void SPUC::iir_df< Numeric, Coeff >::reset (void) inline
Reset.
References SPUC::fir< Numeric, Coeff >::reset().
template<class Numeric , class Coeff = float_type> Numeric SPUC::iir_df< Numeric, Coeff >::update (Numeric in) inline
References SPUC::fir< Numeric, Coeff >::iir(), and SPUC::fir< Numeric, Coeff >::update().
Referenced by SPUC::iir_df< Numeric, Coeff >::clock().
Member Data Documentation
template<class Numeric , class Coeff = float_type> int SPUC::iir_df< Numeric, Coeff >::err
template<class Numeric , class Coeff = float_type> Numeric SPUC::iir_df< Numeric, Coeff >::output
template<class Numeric , class Coeff = float_type> fir<Numeric,Coeff> SPUC::iir_df< Numeric, Coeff >::poles
template<class Numeric , class Coeff = float_type> fir<Numeric,Coeff> SPUC::iir_df< Numeric, Coeff >::zeros
The documentation for this class was generated from the following file:
iir_df.h