SPUC: SPUC::iir_2nd< Numeric, Coeff > Class Template Reference
SPUC::iir_2nd< Numeric, Coeff > Class Template Reference
SPUC double templates | IIR filters
Template for 2nd Order IIR filter.
#include <iir_2nd.h>
Public Types
typedef mixed_type< Numeric,
Coeff >::dtype sum_type
Public Member Functions
iir_2nd (Coeff B0, Coeff B1, Coeff B2, Coeff A1, Coeff A2, long b=0)
iir_2nd (Coeff A1=0, Coeff A2=0)
void set_round_bits (long x)
int get_round_bits ()
Coeff get_b0 ()
Coeff get_b1 ()
Coeff get_b2 ()
Coeff get_a1 ()
Coeff get_a2 ()
void reset ()
void set_a (Coeff A1, Coeff A2)
void set_b (Coeff A1, Coeff A2)
void set_coeffs (Coeff B0, Coeff B1, Coeff B2, Coeff A1, Coeff A2)
iir_2nd (const char *file)
Constructor reading coefficients from a file.
void print ()
Print out coefficients.
Numeric clock (Numeric input)
Input new sample and calculate output.
Public Attributes
Numeric fb2
Numeric fb1
Numeric fb0
Protected Attributes
long round_bits
Coeff b0
Coeff b1
Coeff b2
Coeff a1
Coeff a2
Numeric in [3]
quantiser< Coeff > Q
Detailed Description
template<class Numeric, class Coeff = float_type>
class SPUC::iir_2nd< Numeric, Coeff >
Template for 2nd Order IIR filter.
The filter is assumed to be a low pass 2nd order digital filter of the form
Author
Tony Kirke
Member Typedef Documentation
template<class Numeric, class Coeff = float_type> typedef mixed_type<Numeric,Coeff>::dtype SPUC::iir_2nd< Numeric, Coeff >::sum_type
Constructor & Destructor Documentation
template<class Numeric, class Coeff = float_type> SPUC::iir_2nd< Numeric, Coeff >::iir_2nd (Coeff B0, Coeff B1, Coeff B2, Coeff A1, Coeff A2, long b = 0) inline
References SPUC::iir_2nd< Numeric, Coeff >::reset().
template<class Numeric, class Coeff = float_type> SPUC::iir_2nd< Numeric, Coeff >::iir_2nd (Coeff A1 = 0, Coeff A2 = 0) inline
References SPUC::iir_2nd< Numeric, Coeff >::reset().
template<class Numeric, class Coeff = float_type> SPUC::iir_2nd< Numeric, Coeff >::iir_2nd (const char * file) inline
Constructor reading coefficients from a file.
References SPUC::iir_2nd< Numeric, Coeff >::a1, SPUC::iir_2nd< Numeric, Coeff >::a2, SPUC::iir_2nd< Numeric, Coeff >::b0, SPUC::iir_2nd< Numeric, Coeff >::b1, SPUC::iir_2nd< Numeric, Coeff >::b2, and SPUC::iir_2nd< Numeric, Coeff >::reset().
Member Function Documentation
template<class Numeric, class Coeff = float_type> Numeric SPUC::iir_2nd< Numeric, Coeff >::clock (Numeric input) inline
Input new sample and calculate output.
References SPUC::iir_2nd< Numeric, Coeff >::fb0, SPUC::iir_2nd< Numeric, Coeff >::fb1, SPUC::iir_2nd< Numeric, Coeff >::fb2, and SPUC::iir_2nd< Numeric, Coeff >::Q.
Referenced by SPUC::notch_iir< Numeric, Coeff >::clock(), and main().
template<class Numeric, class Coeff = float_type> Coeff SPUC::iir_2nd< Numeric, Coeff >::get_a1 () inline
Referenced by SPUC::notch_iir< Numeric, Coeff >::set_freq().
template<class Numeric, class Coeff = float_type> Coeff SPUC::iir_2nd< Numeric, Coeff >::get_a2 () inline
template<class Numeric, class Coeff = float_type> Coeff SPUC::iir_2nd< Numeric, Coeff >::get_b0 () inline
template<class Numeric, class Coeff = float_type> Coeff SPUC::iir_2nd< Numeric, Coeff >::get_b1 () inline
template<class Numeric, class Coeff = float_type> Coeff SPUC::iir_2nd< Numeric, Coeff >::get_b2 () inline
Referenced by SPUC::notch_iir< Numeric, Coeff >::set_depth().
template<class Numeric, class Coeff = float_type> int SPUC::iir_2nd< Numeric, Coeff >::get_round_bits () inline
template<class Numeric, class Coeff = float_type> void SPUC::iir_2nd< Numeric, Coeff >::print (void) inline
Print out coefficients.
References SPUC::iir_2nd< Numeric, Coeff >::a1, SPUC::iir_2nd< Numeric, Coeff >::a2, SPUC::iir_2nd< Numeric, Coeff >::b0, SPUC::iir_2nd< Numeric, Coeff >::b1, and SPUC::iir_2nd< Numeric, Coeff >::b2.
Referenced by main().
template<class Numeric, class Coeff = float_type> void SPUC::iir_2nd< Numeric, Coeff >::reset (void) inline
Referenced by SPUC::iir_2nd< Numeric, Coeff >::iir_2nd().
template<class Numeric, class Coeff = float_type> void SPUC::iir_2nd< Numeric, Coeff >::set_a (Coeff A1, Coeff A2) inline
template<class Numeric, class Coeff = float_type> void SPUC::iir_2nd< Numeric, Coeff >::set_b (Coeff A1, Coeff A2) inline
template<class Numeric, class Coeff = float_type> void SPUC::iir_2nd< Numeric, Coeff >::set_coeffs (Coeff B0, Coeff B1, Coeff B2, Coeff A1, Coeff A2) inline
Referenced by main(), SPUC::notch_iir< Numeric, Coeff >::set_coeffs(), SPUC::notch_iir< Numeric, Coeff >::set_depth(), and SPUC::notch_iir< Numeric, Coeff >::set_freq().
template<class Numeric, class Coeff = float_type> void SPUC::iir_2nd< Numeric, Coeff >::set_round_bits (long x) inline
References SPUC::quantiser< Numeric >::set_bits().
Referenced by main().
Member Data Documentation
template<class Numeric, class Coeff = float_type> Coeff SPUC::iir_2nd< Numeric, Coeff >::a1 protected
Referenced by SPUC::iir_2nd< Numeric, Coeff >::iir_2nd(), main(), and SPUC::iir_2nd< Numeric, Coeff >::print().
template<class Numeric, class Coeff = float_type> Coeff SPUC::iir_2nd< Numeric, Coeff >::a2 protected
Referenced by SPUC::iir_2nd< Numeric, Coeff >::iir_2nd(), main(), and SPUC::iir_2nd< Numeric, Coeff >::print().
template<class Numeric, class Coeff = float_type> Coeff SPUC::iir_2nd< Numeric, Coeff >::b0 protected
Referenced by SPUC::iir_2nd< Numeric, Coeff >::iir_2nd(), main(), and SPUC::iir_2nd< Numeric, Coeff >::print().
template<class Numeric, class Coeff = float_type> Coeff SPUC::iir_2nd< Numeric, Coeff >::b1 protected
Referenced by SPUC::iir_2nd< Numeric, Coeff >::iir_2nd(), main(), and SPUC::iir_2nd< Numeric, Coeff >::print().
template<class Numeric, class Coeff = float_type> Coeff SPUC::iir_2nd< Numeric, Coeff >::b2 protected
Referenced by SPUC::iir_2nd< Numeric, Coeff >::iir_2nd(), main(), and SPUC::iir_2nd< Numeric, Coeff >::print().
template<class Numeric, class Coeff = float_type> Numeric SPUC::iir_2nd< Numeric, Coeff >::fb0
Referenced by SPUC::iir_2nd< Numeric, Coeff >::clock().
template<class Numeric, class Coeff = float_type> Numeric SPUC::iir_2nd< Numeric, Coeff >::fb1
Referenced by SPUC::iir_2nd< Numeric, Coeff >::clock().
template<class Numeric, class Coeff = float_type> Numeric SPUC::iir_2nd< Numeric, Coeff >::fb2
Referenced by SPUC::iir_2nd< Numeric, Coeff >::clock(), and main().
template<class Numeric, class Coeff = float_type> Numeric SPUC::iir_2nd< Numeric, Coeff >::in[3] protected
template<class Numeric, class Coeff = float_type> quantiser<Coeff> SPUC::iir_2nd< Numeric, Coeff >::Q protected
Referenced by SPUC::iir_2nd< Numeric, Coeff >::clock().
template<class Numeric, class Coeff = float_type> long SPUC::iir_2nd< Numeric, Coeff >::round_bits protected
The documentation for this class was generated from the following file:
iir_2nd.h