SPUC: SPUC::notch_comb< Numeric, Coeff > Class Template Reference
SPUC::notch_comb< Numeric, Coeff > Class Template Reference
#include <notch_comb.h>
Public Member Functions
notch_comb (float_type fp, int dly)
notch_comb (float_type fp)
notch_comb ()
void set_coeffs (float_type fp, int dly)
void reset ()
Numeric clock (Numeric x)
Public Attributes
allpass_1< Numeric, Coeff > ap
Constructor & Destructor Documentation
template<class Numeric , class Coeff = float_type> SPUC::notch_comb< Numeric, Coeff >::notch_comb (float_type fp, int dly) inline
template<class Numeric , class Coeff = float_type> SPUC::notch_comb< Numeric, Coeff >::notch_comb (float_type fp) inline
template<class Numeric , class Coeff = float_type> SPUC::notch_comb< Numeric, Coeff >::notch_comb () inline
Member Function Documentation
template<class Numeric , class Coeff = float_type> Numeric SPUC::notch_comb< Numeric, Coeff >::clock (Numeric x) inline
References SPUC::allpass_1< Numeric, Coeff >::clock().
template<class Numeric , class Coeff = float_type> void SPUC::notch_comb< Numeric, Coeff >::reset (void) inline
References SPUC::allpass_1< Numeric, Coeff >::reset().
template<class Numeric , class Coeff = float_type> void SPUC::notch_comb< Numeric, Coeff >::set_coeffs (float_type fp, int dly) inline
References SPUC::allpass_1< Numeric, Coeff >::init().
Member Data Documentation
template<class Numeric , class Coeff = float_type> allpass_1<Numeric,Coeff> SPUC::notch_comb< Numeric, Coeff >::ap
The documentation for this class was generated from the following file:
notch_comb.h