SPUC: SPUC::iir_allpass1< Numeric, Coeff > Class Template Reference
SPUC::iir_allpass1< Numeric, Coeff > Class Template Reference
SPUC double templates | IIR filters
Template Class for IIR Filter using 2 1st order sections.
#include <iir_allpass1.h>
Public Member Functions
iir_allpass1 (Coeff c0, Coeff c1, long round_bits=0)
iir_allpass1 (float_type fp)
void reset ()
reset
Numeric clock (Numeric input)
Shift inputs by one time sample and place new sample into array.
Protected Attributes
int Delay
The 2 1st order allpass filters.
allpass_1< Numeric, Coeff > A0
allpass_1< Numeric, Coeff > A1
Numeric prev_input
Detailed Description
template<class Numeric, class Coeff = float_type>
class SPUC::iir_allpass1< Numeric, Coeff >
Template Class for IIR Filter using 2 1st order sections.
The filter is a combination of 2 Allpass sections of the form G(z) = (a*z*z + 1)/(z*z+a) so that the overall H(z) is H(z) = 1/z*G(z,a0) + G(z,a1) The combination of these two allpass functions result in a lowpass/highpass complementary pair. The class only uses the low pass filter. This class needs the allpass_1 class
Author
Tony Kirke
Constructor & Destructor Documentation
template<class Numeric , class Coeff = float_type> SPUC::iir_allpass1< Numeric, Coeff >::iir_allpass1 (Coeff c0, Coeff c1, long round_bits = 0) inline
References SPUC::iir_allpass1< Numeric, Coeff >::reset().
template<class Numeric , class Coeff = float_type> SPUC::iir_allpass1< Numeric, Coeff >::iir_allpass1 (float_type fp) inline
References SPUC::iir_allpass1< Numeric, Coeff >::A0, SPUC::iir_allpass1< Numeric, Coeff >::A1, SPUC::iir_allpass1< Numeric, Coeff >::Delay, SPUC::elliptic_allpass(), and SPUC::iir_allpass1< Numeric, Coeff >::reset().
Member Function Documentation
template<class Numeric , class Coeff = float_type> Numeric SPUC::iir_allpass1< Numeric, Coeff >::clock (Numeric input) inline
Shift inputs by one time sample and place new sample into array.
References SPUC::iir_allpass1< Numeric, Coeff >::A0, SPUC::iir_allpass1< Numeric, Coeff >::A1, SPUC::iir_allpass1< Numeric, Coeff >::prev_input, and SPUC::round().
template<class Numeric , class Coeff = float_type> void SPUC::iir_allpass1< Numeric, Coeff >::reset (void) inline
reset
References SPUC::iir_allpass1< Numeric, Coeff >::A0, SPUC::iir_allpass1< Numeric, Coeff >::A1, and SPUC::iir_allpass1< Numeric, Coeff >::prev_input.
Referenced by SPUC::iir_allpass1< Numeric, Coeff >::iir_allpass1().
Member Data Documentation
template<class Numeric , class Coeff = float_type> allpass_1<Numeric,Coeff> SPUC::iir_allpass1< Numeric, Coeff >::A0 protected
Referenced by SPUC::iir_allpass1< Numeric, Coeff >::clock(), SPUC::iir_allpass1< Numeric, Coeff >::iir_allpass1(), and SPUC::iir_allpass1< Numeric, Coeff >::reset().
template<class Numeric , class Coeff = float_type> allpass_1<Numeric,Coeff> SPUC::iir_allpass1< Numeric, Coeff >::A1 protected
Referenced by SPUC::iir_allpass1< Numeric, Coeff >::clock(), SPUC::iir_allpass1< Numeric, Coeff >::iir_allpass1(), and SPUC::iir_allpass1< Numeric, Coeff >::reset().
template<class Numeric , class Coeff = float_type> int SPUC::iir_allpass1< Numeric, Coeff >::Delay protected
The 2 1st order allpass filters.
Referenced by SPUC::iir_allpass1< Numeric, Coeff >::iir_allpass1().
template<class Numeric , class Coeff = float_type> Numeric SPUC::iir_allpass1< Numeric, Coeff >::prev_input protected
Referenced by SPUC::iir_allpass1< Numeric, Coeff >::clock(), and SPUC::iir_allpass1< Numeric, Coeff >::reset().
The documentation for this class was generated from the following file:
iir_allpass1.h