SPUC: SPUC::dqpsk Class Reference
SPUC::dqpsk Class Reference
SPUC non-template classes | Communication classes And functions
Differential QPSK encoder/decoder.
#include <dqpsk.h>
Public Member Functions
dqpsk ()
complex< long > encode (complex< long > c)
complex< long > decode (complex< long > c)
complex< long > convbits (int sym)
int qpsk_sym (complex< long > c)
Public Attributes
int ** datbase
int previous_encoded_symbol
int previous_decoded_symbol
Detailed Description
Differential QPSK encoder/decoder.
Encode/Decode the input bits into quaternary qpsk format
Author
Tony Kirke
Constructor & Destructor Documentation
SPUC::dqpsk::dqpsk ()
Differential encoding/decoding of QPSK Encode/Decode the input bits into quaternary qpsk format
References datbase, previous_decoded_symbol, and previous_encoded_symbol.
Member Function Documentation
complex< long > SPUC::dqpsk::convbits (int sym)
Convert integer symbol (0-3) back to binary pair
Referenced by decode(), and encode().
complex< long > SPUC::dqpsk::decode (complex< long > c)
Differential decoder
References convbits(), datbase, previous_decoded_symbol, and qpsk_sym().
complex< long > SPUC::dqpsk::encode (complex< long > c)
Call qpsk_sym to get equivalent symbol value (0-3) of current input bit pair Get current output symbol (0-3) from encoding data base[curr symbol][prev encoded symbol] Call convbits to convert current encoded symbol to bit pair Previous encoded symbol = current encoded symbol
References convbits(), datbase, previous_encoded_symbol, and qpsk_sym().
int SPUC::dqpsk::qpsk_sym (complex< long > c)
Encode bit pair into integer value from 0 to 3 and return symbol
Referenced by decode(), and encode().
Member Data Documentation
int** SPUC::dqpsk::datbase
Referenced by decode(), dqpsk(), and encode().
int SPUC::dqpsk::previous_decoded_symbol
Referenced by decode(), and dqpsk().
int SPUC::dqpsk::previous_encoded_symbol
Referenced by dqpsk(), and encode().
The documentation for this class was generated from the following files:
dqpsk.h
dqpsk.cpp