SPUC: SPUC::qpsk_variable< Numeric > Class Template Reference
SPUC::qpsk_variable< Numeric > Class Template Reference
SPUC templates with real parameters | Communication classes And functions
A QPSK receiver that can operate over a range of non-integer sampling rates.
#include <qpsk_variable.h>
Public Types
typedef fundtype< Numeric >::ftype CNumeric
Public Member Functions
Numeric I_data ()
Numeric Q_data ()
complex< CNumeric > data ()
Numeric carrier_loop ()
Numeric symbol_loop ()
bool symclk (void)
Numeric agc_out (void)
qpsk_variable (void)
void clock (complex< CNumeric > adc)
Public Attributes
a_d ADC
fir< complex< CNumeric >, Numeric > rcv_sqrt_rc
lagrange< complex< float_type > > interp
delay< complex< CNumeric > > final_baseband_delay
delay< complex< CNumeric > > hard_decision_delay
delay< complex< CNumeric > > timing_disc_delay
sum_and_dump< CNumeric > symbol_lock_detect
fir< complex< CNumeric >, Numeric > fmf
agc sigma_delta
loop_filter< Numeric > afc_loop_filter
loop_filter< Numeric > carrier_loop_filter
loop_filter< Numeric > symbol_loop_filter
qpsk_discriminators discriminators
Numeric agc_bit
Numeric carrier_loop_out
Numeric symbol_loop_out
bool symbol_clk
bool symbol_clk_pls
bool sample_clk
bool symbol_x2_clk
bool symbol_x2_clk_pls
vco< Numeric > carrier__nco
cordic< CNumeric > cordic_mult
resampler< complex< CNumeric > > rate_change
long bpsk
long resampler_round
int sym_dec
Numeric carrier_error
Numeric symbol_nco_out
complex< CNumeric > hard_decision_prev
complex< CNumeric > final_baseband_prev
complex< long > adc_out
complex< CNumeric > baseband
complex< CNumeric > decimated
complex< CNumeric > decimated_baseband
complex< CNumeric > resampled
complex< CNumeric > carrier_in
complex< CNumeric > carrier_nco_out
complex< CNumeric > mf_in
complex< CNumeric > mf_out
complex< CNumeric > fmf_out
complex< CNumeric > final_baseband
Numeric timing_error
Numeric nda_timing_error
Numeric sym_lock
Numeric symbol_locked
Numeric sym_lock_thres
Numeric cp_afc
Numeric quad_afc
bool afc
complex< CNumeric > hard_decision
Numeric qpsk_bpsk_reg
Numeric lock_rate_reg
Numeric invert_q_reg
Detailed Description
template<class Numeric>
class SPUC::qpsk_variable< Numeric >
A QPSK receiver that can operate over a range of non-integer sampling rates.
,Symbol timing, frequency control and carrier phase locked loops are included. Also contains root-raised cosine matched filter, A/D and agc function.
Author
Tony Kirke
Member Typedef Documentation
template<class Numeric> typedef fundtype<Numeric>::ftype SPUC::qpsk_variable< Numeric >::CNumeric
Constructor & Destructor Documentation
template<class Numeric> SPUC::qpsk_variable< Numeric >::qpsk_variable (void) inline
References SPUC::fir< Numeric, Coeff >::coeff, SPUC::loop_filter< Numeric, Coeff >::k0, SPUC::loop_filter< Numeric, Coeff >::k0_en, SPUC::loop_filter< Numeric, Coeff >::k1, SPUC::loop_filter< Numeric, Coeff >::k1_en, SPUC::vco< Numeric >::reset_frequency(), SPUC::sum_and_dump< Numeric >::set_exp(), and SPUC::qpsk_discriminators::set_mode().
Member Function Documentation
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::agc_out (void) inline
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::carrier_loop () inline
template<class Numeric> void SPUC::qpsk_variable< Numeric >::clock (complex< CNumeric > adc) inline
References SPUC::qpsk_variable< Numeric >::baseband, SPUC::vco< Numeric >::clock(), SPUC::qpsk_discriminators::cross_prod_afc(), SPUC::qpsk_discriminators::dd_timing_disc(), SPUC::vco< Numeric >::get_phase(), SPUC::sum_and_dump< Numeric >::input(), SPUC::vco< Numeric >::load(), SPUC::qpsk_variable< Numeric >::mf_out, SPUC::qpsk_discriminators::nda_timing_disc(), SPUC::sum_and_dump< Numeric >::output(), SPUC::qpsk_discriminators::pll_disc(), SPUC::qpsk_discriminators::quad(), SPUC::resampler< Numeric >::ready, SPUC::cordic< Numeric >::rotate(), SPUC::round(), SPUC::qpsk_discriminators::sample(), SPUC::saturate(), SPUC::signbit(), SPUC::qpsk_variable< Numeric >::sym_lock_thres, SPUC::qpsk_variable< Numeric >::symbol_clk, SPUC::qpsk_discriminators::symbol_lock_out(), SPUC::resampler< Numeric >::update(), SPUC::loop_filter< Numeric, Coeff >::update(), and SPUC::fir< Numeric, Coeff >::update().
Referenced by SPUC::sim_qpsk_variable< Numeric >::rx_step().
template<class Numeric> complex<CNumeric> SPUC::qpsk_variable< Numeric >::data () inline
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::I_data () inline
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::Q_data () inline
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::symbol_loop () inline
template<class Numeric> bool SPUC::qpsk_variable< Numeric >::symclk (void) inline
Referenced by SPUC::sim_qpsk_variable< Numeric >::rx_step().
Member Data Documentation
template<class Numeric> a_d SPUC::qpsk_variable< Numeric >::ADC
template<class Numeric> complex<long> SPUC::qpsk_variable< Numeric >::adc_out
template<class Numeric> bool SPUC::qpsk_variable< Numeric >::afc
template<class Numeric> loop_filter<Numeric> SPUC::qpsk_variable< Numeric >::afc_loop_filter
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::agc_bit
template<class Numeric> complex<CNumeric> SPUC::qpsk_variable< Numeric >::baseband
Referenced by SPUC::qpsk_variable< Numeric >::clock().
template<class Numeric> long SPUC::qpsk_variable< Numeric >::bpsk
template<class Numeric> vco<Numeric> SPUC::qpsk_variable< Numeric >::carrier__nco
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::carrier_error
template<class Numeric> complex<CNumeric> SPUC::qpsk_variable< Numeric >::carrier_in
template<class Numeric> loop_filter<Numeric> SPUC::qpsk_variable< Numeric >::carrier_loop_filter
Referenced by SPUC::sim_qpsk_variable< Numeric >::loop_init().
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::carrier_loop_out
template<class Numeric> complex<CNumeric> SPUC::qpsk_variable< Numeric >::carrier_nco_out
template<class Numeric> cordic<CNumeric> SPUC::qpsk_variable< Numeric >::cordic_mult
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::cp_afc
template<class Numeric> complex<CNumeric> SPUC::qpsk_variable< Numeric >::decimated
template<class Numeric> complex<CNumeric> SPUC::qpsk_variable< Numeric >::decimated_baseband
template<class Numeric> qpsk_discriminators SPUC::qpsk_variable< Numeric >::discriminators
template<class Numeric> complex<CNumeric> SPUC::qpsk_variable< Numeric >::final_baseband
template<class Numeric> delay< complex<CNumeric> > SPUC::qpsk_variable< Numeric >::final_baseband_delay
template<class Numeric> complex<CNumeric> SPUC::qpsk_variable< Numeric >::final_baseband_prev
template<class Numeric> fir< complex<CNumeric>, Numeric > SPUC::qpsk_variable< Numeric >::fmf
template<class Numeric> complex<CNumeric> SPUC::qpsk_variable< Numeric >::fmf_out
template<class Numeric> complex<CNumeric> SPUC::qpsk_variable< Numeric >::hard_decision
template<class Numeric> delay< complex<CNumeric> > SPUC::qpsk_variable< Numeric >::hard_decision_delay
template<class Numeric> complex<CNumeric> SPUC::qpsk_variable< Numeric >::hard_decision_prev
template<class Numeric> lagrange<complex<float_type> > SPUC::qpsk_variable< Numeric >::interp
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::invert_q_reg
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::lock_rate_reg
template<class Numeric> complex<CNumeric> SPUC::qpsk_variable< Numeric >::mf_in
template<class Numeric> complex<CNumeric> SPUC::qpsk_variable< Numeric >::mf_out
Referenced by SPUC::qpsk_variable< Numeric >::clock().
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::nda_timing_error
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::qpsk_bpsk_reg
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::quad_afc
template<class Numeric> resampler<complex<CNumeric> > SPUC::qpsk_variable< Numeric >::rate_change
Referenced by SPUC::sim_qpsk_variable< Numeric >::loop_init().
template<class Numeric> fir< complex<CNumeric>, Numeric > SPUC::qpsk_variable< Numeric >::rcv_sqrt_rc
template<class Numeric> complex<CNumeric> SPUC::qpsk_variable< Numeric >::resampled
template<class Numeric> long SPUC::qpsk_variable< Numeric >::resampler_round
template<class Numeric> bool SPUC::qpsk_variable< Numeric >::sample_clk
template<class Numeric> agc SPUC::qpsk_variable< Numeric >::sigma_delta
template<class Numeric> int SPUC::qpsk_variable< Numeric >::sym_dec
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::sym_lock
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::sym_lock_thres
Referenced by SPUC::qpsk_variable< Numeric >::clock().
template<class Numeric> bool SPUC::qpsk_variable< Numeric >::symbol_clk
Referenced by SPUC::qpsk_variable< Numeric >::clock().
template<class Numeric> bool SPUC::qpsk_variable< Numeric >::symbol_clk_pls
template<class Numeric> sum_and_dump<CNumeric> SPUC::qpsk_variable< Numeric >::symbol_lock_detect
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::symbol_locked
template<class Numeric> loop_filter<Numeric> SPUC::qpsk_variable< Numeric >::symbol_loop_filter
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::symbol_loop_out
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::symbol_nco_out
template<class Numeric> bool SPUC::qpsk_variable< Numeric >::symbol_x2_clk
template<class Numeric> bool SPUC::qpsk_variable< Numeric >::symbol_x2_clk_pls
template<class Numeric> delay< complex<CNumeric> > SPUC::qpsk_variable< Numeric >::timing_disc_delay
template<class Numeric> Numeric SPUC::qpsk_variable< Numeric >::timing_error
The documentation for this class was generated from the following file:
qpsk_variable.h