SPUC: SPUC::cascaded_cic< Numeric > Class Template Reference
SPUC::cascaded_cic< Numeric > Class Template Reference
#include <cascaded_cic.h>
Public Member Functions
cascaded_cic (char n=2, long r=4)
void num_stages (char stages, long r)
void reset ()
Numeric clock (Numeric in)
Protected Attributes
long rate
char stages
int dump_count
cic< Numeric > cic1
cic< Numeric > cic2
Constructor & Destructor Documentation
template<class Numeric > SPUC::cascaded_cic< Numeric >::cascaded_cic (char n = 2, long r = 4) inline
References SPUC::cic< Numeric >::num_stages().
Member Function Documentation
template<class Numeric > Numeric SPUC::cascaded_cic< Numeric >::clock (Numeric in) inline
References SPUC::cic< Numeric >::decimate(), and SPUC::cic< Numeric >::interpolate().
template<class Numeric > void SPUC::cascaded_cic< Numeric >::num_stages (char stages, long r) inline
References SPUC::cic< Numeric >::num_stages().
template<class Numeric > void SPUC::cascaded_cic< Numeric >::reset (void) inline
References SPUC::cic< Numeric >::reset().
Member Data Documentation
template<class Numeric > cic<Numeric> SPUC::cascaded_cic< Numeric >::cic1 protected
template<class Numeric > cic<Numeric> SPUC::cascaded_cic< Numeric >::cic2 protected
template<class Numeric > int SPUC::cascaded_cic< Numeric >::dump_count protected
template<class Numeric > long SPUC::cascaded_cic< Numeric >::rate protected
template<class Numeric > char SPUC::cascaded_cic< Numeric >::stages protected
The documentation for this class was generated from the following file:
cascaded_cic.h