SPUC: SPUC::a_d Class Reference
SPUC::a_d Class Reference
SPUC non-template classes | Miscellaneous DSP | Simulation classes And functions
An A/D conversion class.
#include <a_d.h>
Public Member Functions
a_d (char h=8)
Constructor.
long clock (float_type x)
Quantize and limit signal to size bits.
complex< long > clock (complex< float_type > x)
Protected Attributes
char size
long max
Number of bits <= 8.
long min
Detailed Description
An A/D conversion class.
Bit width is specified in constructor. Default is 8 bits. Handles real and complex samples
Author
Tony Kirke
Constructor & Destructor Documentation
SPUC::a_d::a_d (char h = 8)
Constructor.
References max, min, and size.
Member Function Documentation
long SPUC::a_d::clock (float_type x)
Quantize and limit signal to size bits.
References max, and min.
Referenced by clock(), SPUC::sim_qpsk< Numeric >::step(), and SPUC::sim_qam< Numeric >::step().
complex< long > SPUC::a_d::clock (complex< float_type > x)
References clock().
Member Data Documentation
long SPUC::a_d::max protected
Number of bits <= 8.
Referenced by a_d(), and clock().
long SPUC::a_d::min protected
Referenced by a_d(), and clock().
char SPUC::a_d::size protected
Referenced by a_d().
The documentation for this class was generated from the following files:
a_d.h
a_d.cpp