SPUC: SPUC::baud_eq_env< Numeric > Class Template Reference
SPUC::baud_eq_env< Numeric > Class Template Reference
SPUC complex templates | Simulation classes And functions | Equalization classes And functions
Class for doing a simulation of an equalizer running at 1 sample/symbol.
#include <baud_eq_env.h>
Public Member Functions
baud_eq_env (long npaths=1)
void loop_init (long equalizer_type, long data_delay, float_type delay_spread)
void step (void)
void loop_end ()
Public Attributes
bpsk_ber_test * BER_mon
max_pn * tx_data_source
noise * n
mle< Numeric > * DUT
fading_channel * multipaths
long num
float_type var
float_type snr
long data
long output_delay
long eq_type
complex< float_type > base
complex< float_type > main
complex< float_type > b_noise
long rcv_symbols
long count
long paths
long phase_acc
Detailed Description
template<class Numeric>
class SPUC::baud_eq_env< Numeric >
Class for doing a simulation of an equalizer running at 1 sample/symbol.
Author
Tony Kirke
Constructor & Destructor Documentation
template<class Numeric > SPUC::baud_eq_env< Numeric >::baud_eq_env (long npaths = 1) inline
Member Function Documentation
template<class Numeric > void SPUC::baud_eq_env< Numeric >::loop_end () inline
References SPUC::baud_eq_env< Numeric >::BER_mon, SPUC::baud_eq_env< Numeric >::DUT, SPUC::baud_eq_env< Numeric >::multipaths, SPUC::baud_eq_env< Numeric >::n, and SPUC::baud_eq_env< Numeric >::tx_data_source.
Referenced by main().
template<class Numeric > void SPUC::baud_eq_env< Numeric >::loop_init (long equalizer_type, long data_delay, float_type delay_spread) inline
References SPUC::fading_channel::exp_decay, SPUC::baud_eq_env< Numeric >::paths, SPUC::mle< Numeric >::set_cir(), SPUC::fir< Numeric, Coeff >::settap(), and SPUC::sqrt().
Referenced by main().
template<class Numeric > void SPUC::baud_eq_env< Numeric >::step (void) inline
References SPUC::baud_eq_env< Numeric >::b_noise, SPUC::noise::Cgauss(), SPUC::expj(), MASK_BIT, SPUC::mle< Numeric >::mlsd(), SPUC::max_pn::out(), PI, and SPUC::fading_channel::update().
Referenced by main().
Member Data Documentation
template<class Numeric > complex<float_type> SPUC::baud_eq_env< Numeric >::b_noise
Referenced by SPUC::baud_eq_env< Numeric >::step().
template<class Numeric > complex<float_type> SPUC::baud_eq_env< Numeric >::base
template<class Numeric > bpsk_ber_test* SPUC::baud_eq_env< Numeric >::BER_mon
Referenced by SPUC::baud_eq_env< Numeric >::loop_end(), and main().
template<class Numeric > long SPUC::baud_eq_env< Numeric >::count
template<class Numeric > long SPUC::baud_eq_env< Numeric >::data
Referenced by main().
template<class Numeric > mle<Numeric>* SPUC::baud_eq_env< Numeric >::DUT
Referenced by SPUC::baud_eq_env< Numeric >::loop_end().
template<class Numeric > long SPUC::baud_eq_env< Numeric >::eq_type
template<class Numeric > complex<float_type> SPUC::baud_eq_env< Numeric >::main
template<class Numeric > fading_channel* SPUC::baud_eq_env< Numeric >::multipaths
Referenced by SPUC::baud_eq_env< Numeric >::loop_end(), and main().
template<class Numeric > noise* SPUC::baud_eq_env< Numeric >::n
Referenced by SPUC::baud_eq_env< Numeric >::loop_end().
template<class Numeric > long SPUC::baud_eq_env< Numeric >::num
Referenced by main().
template<class Numeric > long SPUC::baud_eq_env< Numeric >::output_delay
template<class Numeric > long SPUC::baud_eq_env< Numeric >::paths
Referenced by SPUC::baud_eq_env< Numeric >::loop_init().
template<class Numeric > long SPUC::baud_eq_env< Numeric >::phase_acc
template<class Numeric > long SPUC::baud_eq_env< Numeric >::rcv_symbols
Referenced by main().
template<class Numeric > float_type SPUC::baud_eq_env< Numeric >::snr
Referenced by main().
template<class Numeric > max_pn* SPUC::baud_eq_env< Numeric >::tx_data_source
Referenced by SPUC::baud_eq_env< Numeric >::loop_end().
template<class Numeric > float_type SPUC::baud_eq_env< Numeric >::var
The documentation for this class was generated from the following file:
baud_eq_env.h