SPUC: SPUC::quad_data< Numeric > Class Template Reference
SPUC::quad_data< Numeric > Class Template Reference
SPUC templates with real parameters | Communication classes And functions
Class for QPSK data using a root raised cosine transmit filter.
#include <quad_data.h>
Public Types
typedef fundtype< Numeric >::ftype CNumeric
Public Member Functions
void set_initial_offset (float_type timing_init)
quad_data (int total_over)
complex< CNumeric > get_fir_output (void)
complex< CNumeric > get_sample (float_type timing_inc)
Public Attributes
fir_interp< complex< CNumeric >
, Numeric > rcfir
max_pn pn_i
max_pn pn_q
int symbols
int over
complex< CNumeric > data
lagrange< complex< CNumeric > > interp
float_type prev_timing_offset
Detailed Description
template<class Numeric>
class SPUC::quad_data< Numeric >
Class for QPSK data using a root raised cosine transmit filter.
Samples are generated by a combination of polyphase FIR and lagrange interpolation (to allow for a wide range of sampling rates)
Author
Tony Kirke, Copyright(c) 2001
Tony Kirke
Member Typedef Documentation
template<class Numeric> typedef fundtype<Numeric>::ftype SPUC::quad_data< Numeric >::CNumeric
Constructor & Destructor Documentation
template<class Numeric> SPUC::quad_data< Numeric >::quad_data (int total_over) inline
Member Function Documentation
template<class Numeric> complex<CNumeric> SPUC::quad_data< Numeric >::get_fir_output (void) inline
Referenced by SPUC::quad_data< float_type >::get_sample().
template<class Numeric> complex<CNumeric> SPUC::quad_data< Numeric >::get_sample (float_type timing_inc) inline
Referenced by SPUC::sim_qpsk< Numeric >::tx_step(), and SPUC::sim_qpsk_variable< Numeric >::tx_step().
template<class Numeric> void SPUC::quad_data< Numeric >::set_initial_offset (float_type timing_init) inline
Referenced by SPUC::sim_qpsk< Numeric >::loop_init(), and SPUC::sim_qpsk_variable< Numeric >::loop_init().
Member Data Documentation
template<class Numeric> complex<CNumeric> SPUC::quad_data< Numeric >::data
template<class Numeric> lagrange<complex<CNumeric> > SPUC::quad_data< Numeric >::interp
template<class Numeric> int SPUC::quad_data< Numeric >::over
template<class Numeric> max_pn SPUC::quad_data< Numeric >::pn_i
template<class Numeric> max_pn SPUC::quad_data< Numeric >::pn_q
template<class Numeric> float_type SPUC::quad_data< Numeric >::prev_timing_offset
template<class Numeric> fir_interp<complex<CNumeric>, Numeric > SPUC::quad_data< Numeric >::rcfir
template<class Numeric> int SPUC::quad_data< Numeric >::symbols
The documentation for this class was generated from the following file:
quad_data.h