SPUC: SPUC::cutboost< Numeric, Coeff > Class Template Reference
SPUC::cutboost< Numeric, Coeff > Class Template Reference
SPUC double templates | IIR filters
IIR structure that can cut or boost signals at a programmed frequency.
#include <cutboost.h>
Public Member Functions
cutboost ()
cutboost (float_type fp, float_type k2, float_type k0)
cutboost (float_type fp, float_type k0)
void reset ()
Numeric clock (Numeric x)
void set_coeffs (float_type fp, float_type k2, float_type k0)
void set_depth (float_type k0)
void set_freq (float_type fp)
Public Attributes
allpass_2nd< Numeric, Coeff > ap
float_type k
float_type g
float_type a
Detailed Description
template<class Numeric, class Coeff = float_type>
class SPUC::cutboost< Numeric, Coeff >
IIR structure that can cut or boost signals at a programmed frequency.
Author
Tony Kirke
Constructor & Destructor Documentation
template<class Numeric , class Coeff = float_type> SPUC::cutboost< Numeric, Coeff >::cutboost () inline
template<class Numeric , class Coeff = float_type> SPUC::cutboost< Numeric, Coeff >::cutboost (float_type fp, float_type k2, float_type k0) inline
template<class Numeric , class Coeff = float_type> SPUC::cutboost< Numeric, Coeff >::cutboost (float_type fp, float_type k0) inline
Member Function Documentation
template<class Numeric , class Coeff = float_type> Numeric SPUC::cutboost< Numeric, Coeff >::clock (Numeric x) inline
References SPUC::allpass_2nd< Numeric, Coeff >::clock().
template<class Numeric , class Coeff = float_type> void SPUC::cutboost< Numeric, Coeff >::reset (void) inline
References SPUC::allpass_2nd< Numeric, Coeff >::reset().
template<class Numeric , class Coeff = float_type> void SPUC::cutboost< Numeric, Coeff >::set_coeffs (float_type fp, float_type k2, float_type k0) inline
References SPUC::cos(), SPUC::allpass_2nd< Numeric, Coeff >::set_coeffs(), and TWOPI.
template<class Numeric , class Coeff = float_type> void SPUC::cutboost< Numeric, Coeff >::set_depth (float_type k0) inline
template<class Numeric , class Coeff = float_type> void SPUC::cutboost< Numeric, Coeff >::set_freq (float_type fp) inline
References SPUC::cos(), SPUC::allpass_2nd< Numeric, Coeff >::set_coeffs(), and TWOPI.
Member Data Documentation
template<class Numeric , class Coeff = float_type> float_type SPUC::cutboost< Numeric, Coeff >::a
template<class Numeric , class Coeff = float_type> allpass_2nd<Numeric,Coeff> SPUC::cutboost< Numeric, Coeff >::ap
template<class Numeric , class Coeff = float_type> float_type SPUC::cutboost< Numeric, Coeff >::g
template<class Numeric , class Coeff = float_type> float_type SPUC::cutboost< Numeric, Coeff >::k
The documentation for this class was generated from the following file:
cutboost.h