SPUC: SPUC::nested_allpass_1< Numeric, Coeff > Class Template Reference
SPUC::nested_allpass_1< Numeric, Coeff > Class Template Reference
#include <nested_allpass_1.h>
Public Member Functions
nested_allpass_1 (Coeff Gain=0, Coeff VGain=0)
Constructor with gain and delay.
Coeff get_coefficient (void)
void reset ()
Reset.
void init (Coeff Gain, Coeff VGain, long s)
Initializes gain and delay.
Numeric clock (Numeric input)
Shift inputs by one time sample and place new sample into array.
Protected Types
typedef mixed_type< Numeric,
Coeff >::dtype sum_type
Protected Attributes
long size
number of unit sample delays
long round_bits
float_type gain
float_type vgain
float_type prev_sum
float_type prev_mult
allpass_1< Numeric > mult
allpass_1< Numeric > sum
Member Typedef Documentation
template<class Numeric , class Coeff = float_type> typedef mixed_type<Numeric,Coeff>::dtype SPUC::nested_allpass_1< Numeric, Coeff >::sum_type protected
Constructor & Destructor Documentation
template<class Numeric , class Coeff = float_type> SPUC::nested_allpass_1< Numeric, Coeff >::nested_allpass_1 (Coeff Gain = 0, Coeff VGain = 0) inline
Constructor with gain and delay.
Member Function Documentation
template<class Numeric , class Coeff = float_type> Numeric SPUC::nested_allpass_1< Numeric, Coeff >::clock (Numeric input) inline
Shift inputs by one time sample and place new sample into array.
References SPUC::allpass_1< Numeric, Coeff >::clock(), SPUC::nested_allpass_1< Numeric, Coeff >::prev_mult, and SPUC::nested_allpass_1< Numeric, Coeff >::prev_sum.
template<class Numeric , class Coeff = float_type> Coeff SPUC::nested_allpass_1< Numeric, Coeff >::get_coefficient (void) inline
template<class Numeric , class Coeff = float_type> void SPUC::nested_allpass_1< Numeric, Coeff >::init (Coeff Gain, Coeff VGain, long s) inline
Initializes gain and delay.
References SPUC::allpass_1< Numeric, Coeff >::init().
template<class Numeric , class Coeff = float_type> void SPUC::nested_allpass_1< Numeric, Coeff >::reset (void) inline
Reset.
References SPUC::allpass_1< Numeric, Coeff >::reset().
Member Data Documentation
template<class Numeric , class Coeff = float_type> float_type SPUC::nested_allpass_1< Numeric, Coeff >::gain protected
template<class Numeric , class Coeff = float_type> allpass_1<Numeric> SPUC::nested_allpass_1< Numeric, Coeff >::mult protected
template<class Numeric , class Coeff = float_type> float_type SPUC::nested_allpass_1< Numeric, Coeff >::prev_mult protected
Referenced by SPUC::nested_allpass_1< Numeric, Coeff >::clock().
template<class Numeric , class Coeff = float_type> float_type SPUC::nested_allpass_1< Numeric, Coeff >::prev_sum protected
Referenced by SPUC::nested_allpass_1< Numeric, Coeff >::clock().
template<class Numeric , class Coeff = float_type> long SPUC::nested_allpass_1< Numeric, Coeff >::round_bits protected
template<class Numeric , class Coeff = float_type> long SPUC::nested_allpass_1< Numeric, Coeff >::size protected
number of unit sample delays
template<class Numeric , class Coeff = float_type> allpass_1<Numeric> SPUC::nested_allpass_1< Numeric, Coeff >::sum protected
template<class Numeric , class Coeff = float_type> float_type SPUC::nested_allpass_1< Numeric, Coeff >::vgain protected
The documentation for this class was generated from the following file:
nested_allpass_1.h