SPUC: SPUC::dvb_conv_encoder Class Reference
SPUC::dvb_conv_encoder Class Reference
SPUC non-template classes | Communication classes And functions | Forward Error Correcting Codes
DVB Convolution encode for rate 1/2.
#include <dvb_conv_encoder.h>
Public Member Functions
dvb_conv_encoder ()
Constructor.
void reset ()
~dvb_conv_encoder ()
bool clock ()
bool get_data (void)
bool reduce (long x, long y)
Public Attributes
max_pn test_pn
const long g1
const long g2
bool conv_enc_phase
int conv_enc_get_bit
long conv_enc_u
long conv_bit_number
bool raw_bit
Detailed Description
DVB Convolution encode for rate 1/2.
Convolutional Encoder for rate 1/2 encoding with DVB Generators. Uses PN sequence for data generation
Author
Tony Kirke
Constructor & Destructor Documentation
SPUC::dvb_conv_encoder::dvb_conv_encoder () inline
Constructor.
References reset().
SPUC::dvb_conv_encoder::~dvb_conv_encoder () inline
Member Function Documentation
bool SPUC::dvb_conv_encoder::clock ()
References conv_bit_number, conv_enc_phase, conv_enc_u, g1, g2, get_data(), and reduce().
bool SPUC::dvb_conv_encoder::get_data (void) inline
References SPUC::max_pn::get_bit().
Referenced by clock().
bool SPUC::dvb_conv_encoder::reduce (long x, long y)
Referenced by clock().
void SPUC::dvb_conv_encoder::reset (void) inline
References SPUC::max_pn::reset().
Referenced by dvb_conv_encoder().
Member Data Documentation
long SPUC::dvb_conv_encoder::conv_bit_number
Referenced by clock().
int SPUC::dvb_conv_encoder::conv_enc_get_bit
bool SPUC::dvb_conv_encoder::conv_enc_phase
Referenced by clock().
long SPUC::dvb_conv_encoder::conv_enc_u
Referenced by clock().
const long SPUC::dvb_conv_encoder::g1
Referenced by clock().
const long SPUC::dvb_conv_encoder::g2
Referenced by clock().
bool SPUC::dvb_conv_encoder::raw_bit
max_pn SPUC::dvb_conv_encoder::test_pn
The documentation for this class was generated from the following files:
dvb_conv_encoder.h
dvb_conv_encoder.cpp