SPUC: SPUC::ofdm_data_encoder Class Reference
SPUC::ofdm_data_encoder Class Reference
SPUC non-template classes | Communication classes And functions
OFDM/802.11A/G Data Encoder.
#include <ofdm_data_encoder.h>
Public Member Functions
ofdm_data_encoder (int index, int T_fft, int D_carriers, int max_range)
long tx_burst_size (long bytes)
void reset ()
~ofdm_data_encoder ()
void set_rate (int mod, int conv_rate)
complex< long > data_map (long rate)
void get_data_frame ()
void serial_to_word_input (bool in)
long serial_to_word_output (void)
Public Attributes
data_conv_encoder CONV
qam_mod QAM
long rate_index
long enc_rate
long tx_bits_per_symbol
long total_bits
long number_symbols
long frame
long serial
long sample
long data_index
bool raw_bit
const long Carriers
std::vector< bool > raw_data
std::vector< bool > interleaver_in
std::vector< bool > interleaved
std::vector< bool > interleaver_out
std::vector< long > pre_mod
int coded_bits_per_frame
int raw_bits_this_frame
bool no_conv
Detailed Description
OFDM/802.11A/G Data Encoder.
Uses data_conv_encoder and qam_mod classes
Author
Tony Kirke
Constructor & Destructor Documentation
SPUC::ofdm_data_encoder::ofdm_data_encoder (int index, int T_fft, int D_carriers, int max_range) inline
SPUC::ofdm_data_encoder::~ofdm_data_encoder () inline
Member Function Documentation
complex< long > SPUC::ofdm_data_encoder::data_map (long rate)
References Carriers, data_index, SPUC::qam_mod::data_map(), get_data_frame(), and QAM.
void SPUC::ofdm_data_encoder::get_data_frame ()
References Carriers, coded_bits_per_frame, CONV, SPUC::data_conv_encoder::conv_encoder(), enc_rate, SPUC::data_conv_encoder::get_data(), interleaver_in, interleaver_out, no_conv, pre_mod, raw_bits_this_frame, serial_to_word_input(), serial_to_word_output(), and tx_bits_per_symbol.
Referenced by data_map().
void SPUC::ofdm_data_encoder::reset (void) inline
void SPUC::ofdm_data_encoder::serial_to_word_input (bool in)
References serial.
Referenced by get_data_frame().
long SPUC::ofdm_data_encoder::serial_to_word_output (void)
References serial.
Referenced by get_data_frame().
void SPUC::ofdm_data_encoder::set_rate (int mod, int conv_rate) inline
long SPUC::ofdm_data_encoder::tx_burst_size (long bytes) inline
References coded_bits_per_frame.
Member Data Documentation
const long SPUC::ofdm_data_encoder::Carriers
Referenced by data_map(), and get_data_frame().
int SPUC::ofdm_data_encoder::coded_bits_per_frame
Referenced by get_data_frame(), and tx_burst_size().
data_conv_encoder SPUC::ofdm_data_encoder::CONV
Referenced by get_data_frame().
long SPUC::ofdm_data_encoder::data_index
Referenced by data_map().
long SPUC::ofdm_data_encoder::enc_rate
Referenced by get_data_frame().
long SPUC::ofdm_data_encoder::frame
std::vector<bool> SPUC::ofdm_data_encoder::interleaved
std::vector<bool> SPUC::ofdm_data_encoder::interleaver_in
Referenced by get_data_frame().
std::vector<bool> SPUC::ofdm_data_encoder::interleaver_out
Referenced by get_data_frame().
bool SPUC::ofdm_data_encoder::no_conv
Referenced by get_data_frame().
long SPUC::ofdm_data_encoder::number_symbols
std::vector<long> SPUC::ofdm_data_encoder::pre_mod
Referenced by get_data_frame().
qam_mod SPUC::ofdm_data_encoder::QAM
Referenced by data_map().
long SPUC::ofdm_data_encoder::rate_index
bool SPUC::ofdm_data_encoder::raw_bit
int SPUC::ofdm_data_encoder::raw_bits_this_frame
Referenced by get_data_frame().
std::vector<bool> SPUC::ofdm_data_encoder::raw_data
long SPUC::ofdm_data_encoder::sample
long SPUC::ofdm_data_encoder::serial
Referenced by serial_to_word_input(), and serial_to_word_output().
long SPUC::ofdm_data_encoder::total_bits
long SPUC::ofdm_data_encoder::tx_bits_per_symbol
Referenced by get_data_frame().
The documentation for this class was generated from the following files:
ofdm_data_encoder.h
ofdm_data_encoder.cpp