SPUC: SPUC::timing_nco Class Reference
SPUC::timing_nco Class Reference
SPUC non-template classes | Simulation classes And functions
A NCO for symbol recovery in a variable rate QPSK receiver.
#include <timing_nco.h>
Public Member Functions
timing_nco (void)
void set_frequency (unsigned long freq)
void reset_frequency (unsigned long freq)
float_type get_off1 (void)
float_type get_off2 (void)
long get_phase1 (void)
long get_phase2 (void)
long run (long loop_filter_out=0, int load=1)
signed long residual_phase (signed long acc_value)
Protected Attributes
signed long resid1
signed long acc
unsigned long fcw
unsigned long new_fcw
signed long phase1
signed long phase2
signed long new_phase
long sample2
Detailed Description
A NCO for symbol recovery in a variable rate QPSK receiver.
Since interpolation is being done, either one or two samples must be calculated on each update. When sample2 is true, there are 2 samples available.
Author
Tony Kirke, Copyright(c) 2001
Tony Kirke
Constructor & Destructor Documentation
SPUC::timing_nco::timing_nco (void) inline
References MASK_LOd2.
Member Function Documentation
float_type SPUC::timing_nco::get_off1 (void) inline
References MASK_LO.
Referenced by SPUC::resampler< SPUC::complex< CNumeric > >::update().
float_type SPUC::timing_nco::get_off2 (void) inline
References MASK_LO.
Referenced by SPUC::resampler< SPUC::complex< CNumeric > >::update().
long SPUC::timing_nco::get_phase1 (void) inline
References MAX_STEP.
long SPUC::timing_nco::get_phase2 (void) inline
References MAX_STEP.
void SPUC::timing_nco::reset_frequency (unsigned long freq) inline
signed long SPUC::timing_nco::residual_phase (signed long acc_value)
References BITS_USED, and STEP_BITS.
Referenced by run().
long SPUC::timing_nco::run (long loop_filter_out = 0, int load = 1)
References acc, fcw, MASK_HI, MASK_HIx, MASK_LO, MASK_LOd2, new_fcw, phase1, phase2, resid1, residual_phase(), and sample2.
Referenced by SPUC::resampler< SPUC::complex< CNumeric > >::update().
void SPUC::timing_nco::set_frequency (unsigned long freq) inline
Member Data Documentation
signed long SPUC::timing_nco::acc protected
Referenced by run().
unsigned long SPUC::timing_nco::fcw protected
Referenced by run().
unsigned long SPUC::timing_nco::new_fcw protected
Referenced by run().
signed long SPUC::timing_nco::new_phase protected
signed long SPUC::timing_nco::phase1 protected
Referenced by run().
signed long SPUC::timing_nco::phase2 protected
Referenced by run().
signed long SPUC::timing_nco::resid1 protected
Referenced by run().
long SPUC::timing_nco::sample2 protected
Referenced by run().
The documentation for this class was generated from the following files:
timing_nco.h
timing_nco.cpp