SPUC: SPUC::fir< Numeric, Coeff > Class Template Reference
SPUC::fir< Numeric, Coeff > Class Template Reference
SPUC double templates | FIR filters
Template Class for Modeling a Finite Impulse Response filter.
#include <fir.h>
Public Types
typedef base_type< Numeric >::btype Numeric_base
typedef mixed_type< Numeric,
Coeff >::dtype sum_type
Public Member Functions
void settap (long i, Coeff tap)
Set tap weights.
void settaps (fir_coeff< Coeff > &c)
long number_of_taps ()
Coeff gettap (long i)
void reset ()
Reset.
Coeff coeff_sum ()
Get sum of coefficients.
void normalize_gain ()
void make_hpf ()
Numeric out ()
Get current output.
Numeric check (long i)
Clock in new sample & compute current output.
void set_round_bits (long x)
~fir (void)
fir (void)
Constructor.
fir (long n, long rb=0)
Constructor.
fir (fir_coeff< Coeff > C)
Constructor.
void set_size (long n)
Set size of Filter.
long get_size (void)
fir (const char *file)
Constructor that gets coefficients from file (requires fir.cpp)
Numeric clock (Numeric in)
Update filter by inputting 1 sample and returning convolved output sample.
Numeric update (Numeric in)
Numeric iir (Numeric in)
int read_taps (const char *file)
void print (void)
void settap (std::vector< Coeff > z)
Public Attributes
std::vector< Coeff > coeff
std::vector< Numeric > z
Numeric output
quantiser< Numeric > Q
long num_taps
Friends
template<class N , class C >
std::vector< C > get_taps (const fir< N, C > &x)
template<class N , class C >
std::vector< N > get_input (const fir< N, C > &y)
Detailed Description
template<class Numeric, class Coeff = float_type>
class SPUC::fir< Numeric, Coeff >
Template Class for Modeling a Finite Impulse Response filter.
Template works for float_type, long, complex, etc Taps initialized to zeros.
Author
Tony Kirke
Member Typedef Documentation
template<class Numeric, class Coeff = float_type> typedef base_type<Numeric>::btype SPUC::fir< Numeric, Coeff >::Numeric_base
template<class Numeric, class Coeff = float_type> typedef mixed_type<Numeric,Coeff>::dtype SPUC::fir< Numeric, Coeff >::sum_type
Constructor & Destructor Documentation
template<class Numeric, class Coeff = float_type> SPUC::fir< Numeric, Coeff >::~fir (void) inline
template<class Numeric, class Coeff = float_type> SPUC::fir< Numeric, Coeff >::fir (void) inline
Constructor.
template<class Numeric, class Coeff = float_type> SPUC::fir< Numeric, Coeff >::fir (long n, long rb = 0) inline
Constructor.
template<class Numeric, class Coeff = float_type> SPUC::fir< Numeric, Coeff >::fir (fir_coeff< Coeff > C) inline
Constructor.
template<class Numeric, class Coeff = float_type> SPUC::fir< Numeric, Coeff >::fir (const char * file) inline
Constructor that gets coefficients from file (requires fir.cpp)
Member Function Documentation
template<class Numeric, class Coeff = float_type> Numeric SPUC::fir< Numeric, Coeff >::check (long i) inline
Clock in new sample & compute current output.
template<class Numeric, class Coeff = float_type> Numeric SPUC::fir< Numeric, Coeff >::clock (Numeric in) inline
Update filter by inputting 1 sample and returning convolved output sample.
Referenced by main().
template<class Numeric, class Coeff = float_type> Coeff SPUC::fir< Numeric, Coeff >::coeff_sum () inline
Get sum of coefficients.
Referenced by SPUC::fir< Numeric, Numeric >::normalize_gain().
template<class Numeric, class Coeff = float_type> long SPUC::fir< Numeric, Coeff >::get_size (void) inline
template<class Numeric, class Coeff = float_type> Coeff SPUC::fir< Numeric, Coeff >::gettap (long i) inline
template<class Numeric, class Coeff = float_type> Numeric SPUC::fir< Numeric, Coeff >::iir (Numeric in) inline
Referenced by SPUC::iir_df< Numeric, Coeff >::update().
template<class Numeric, class Coeff = float_type> void SPUC::fir< Numeric, Coeff >::make_hpf () inline
template<class Numeric, class Coeff = float_type> void SPUC::fir< Numeric, Coeff >::normalize_gain () inline
template<class Numeric, class Coeff = float_type> long SPUC::fir< Numeric, Coeff >::number_of_taps () inline
Referenced by SPUC::qam_tx< float_type >::loop_init(), and SPUC::quad_data< float_type >::quad_data().
template<class Numeric, class Coeff = float_type> Numeric SPUC::fir< Numeric, Coeff >::out () inline
Get current output.
template<class Numeric, class Coeff = float_type> void SPUC::fir< Numeric, Coeff >::print (void) inline
Referenced by SPUC::iir_df< Numeric, Coeff >::print().
template<class Numeric, class Coeff = float_type> int SPUC::fir< Numeric, Coeff >::read_taps (const char * file) inline
Referenced by SPUC::fir< Numeric, Numeric >::fir(), SPUC::fir_decim< Numeric, Coeff >::fir_decim(), and SPUC::iir_df< Numeric, Coeff >::iir_df().
template<class Numeric, class Coeff = float_type> void SPUC::fir< Numeric, Coeff >::reset (void) inline
Reset.
Referenced by SPUC::sim_qam< Numeric >::loop_end(), SPUC::sim_qam< Numeric >::loop_init(), SPUC::fir_adapt< Numeric, Numeric >::reset(), SPUC::iir_df< Numeric, Coeff >::reset(), SPUC::fir_interp< SPUC::complex< CNumeric >, float_type >::reset(), and SPUC::qpsk< Numeric >::reset().
template<class Numeric, class Coeff = float_type> void SPUC::fir< Numeric, Coeff >::set_round_bits (long x) inline
template<class Numeric, class Coeff = float_type> void SPUC::fir< Numeric, Coeff >::set_size (long n) inline
Set size of Filter.
Referenced by SPUC::fading_channel::fading_channel(), SPUC::lms_dfe< Numeric, Coeff >::lms_dfe(), and SPUC::mle< Numeric >::mle().
template<class Numeric, class Coeff = float_type> void SPUC::fir< Numeric, Coeff >::settap (long i, Coeff tap) inline
Set tap weights.
Referenced by SPUC::baud_eq_env< Numeric >::loop_init(), main(), and SPUC::lms_dfe< Numeric, Coeff >::reset().
template<class Numeric, class Coeff = float_type> void SPUC::fir< Numeric, Coeff >::settap (std::vector< Coeff > z) inline
template<class Numeric, class Coeff = float_type> void SPUC::fir< Numeric, Coeff >::settaps (fir_coeff< Coeff > & c) inline
Referenced by SPUC::qam_tx< float_type >::loop_init(), SPUC::notch_example(), SPUC::qpsk< Numeric >::qpsk(), SPUC::quad_data< float_type >::quad_data(), and SPUC::sim_qam< Numeric >::sim_qam().
template<class Numeric, class Coeff = float_type> Numeric SPUC::fir< Numeric, Coeff >::update (Numeric in) inline
Referenced by SPUC::fir< Numeric, Numeric >::clock(), SPUC::qpsk< Numeric >::clock(), SPUC::qpsk_variable< Numeric >::clock(), main(), SPUC::sim_qam< Numeric >::tx_step(), SPUC::rls< Numeric >::update(), SPUC::iir_df< Numeric, Coeff >::update(), and SPUC::lms_dfe< Numeric, Coeff >::update().
Friends And Related Function Documentation
template<class Numeric, class Coeff = float_type> template<class N , class C > std::vector<N> get_input (const fir< N, C > & y) friend
template<class Numeric, class Coeff = float_type> template<class N , class C > std::vector<C> get_taps (const fir< N, C > & x) friend
Member Data Documentation
template<class Numeric, class Coeff = float_type> std::vector<Coeff> SPUC::fir< Numeric, Coeff >::coeff
Referenced by SPUC::fir_interp< SPUC::complex< CNumeric >, float_type >::clock(), SPUC::fir_decim< Numeric, Coeff >::decim(), SPUC::mle< Numeric >::ff_estimate(), SPUC::lms_dfe< Numeric, Coeff >::get_fb_tap(), SPUC::lms_dfe< Numeric, Coeff >::get_ff_tap(), SPUC::get_taps(), SPUC::iir_df< Numeric, Coeff >::iir_df(), SPUC::lms_dfe< Numeric, Coeff >::lms_dfe(), main(), SPUC::qpsk_variable< Numeric >::qpsk_variable(), SPUC::mle< Numeric >::set_cir(), SPUC::lms_dfe< Numeric, Coeff >::set_fb_tap(), SPUC::lms_dfe< Numeric, Coeff >::set_ff_tap(), SPUC::sim_qam< Numeric >::sim_qam(), and SPUC::mle< Numeric >::tap0().
template<class Numeric, class Coeff = float_type> long SPUC::fir< Numeric, Coeff >::num_taps
Referenced by SPUC::fir< Numeric, Numeric >::coeff_sum(), SPUC::fir_decim< Numeric, Coeff >::decim(), SPUC::lms_dfe< Numeric, Coeff >::fb_size(), SPUC::lms_dfe< Numeric, Coeff >::ff_size(), SPUC::get_input(), SPUC::get_taps(), SPUC::fir< Numeric, Numeric >::iir(), SPUC::fir_decim< Numeric, Coeff >::input(), SPUC::fir< Numeric, Numeric >::make_hpf(), SPUC::fir< Numeric, Numeric >::normalize_gain(), SPUC::fir< Numeric, Numeric >::print(), SPUC::qpsk< Numeric >::qpsk(), SPUC::fir< Numeric, Numeric >::read_taps(), SPUC::fir< Numeric, Numeric >::reset(), SPUC::lms_dfe< Numeric, Coeff >::reset(), SPUC::mle< Numeric >::set_cir(), SPUC::fir_interp< SPUC::complex< CNumeric >, float_type >::set_rate(), SPUC::fir< Numeric, Numeric >::settap(), SPUC::fir< Numeric, Numeric >::settaps(), SPUC::sim_qam< Numeric >::sim_qam(), SPUC::lms_dfe< Numeric, Coeff >::update(), SPUC::fir< Numeric, Numeric >::update(), and SPUC::lms_dfe< Numeric, Coeff >::update_taps_lms().
template<class Numeric, class Coeff = float_type> Numeric SPUC::fir< Numeric, Coeff >::output
Referenced by SPUC::fir_interp< SPUC::complex< CNumeric >, float_type >::clock(), SPUC::fir_decim< Numeric, Coeff >::decim(), and SPUC::fir< Numeric, Numeric >::iir().
template<class Numeric, class Coeff = float_type> quantiser<Numeric> SPUC::fir< Numeric, Coeff >::Q
Referenced by SPUC::fir_interp< SPUC::complex< CNumeric >, float_type >::clock(), SPUC::fir_decim< Numeric, Coeff >::decim(), SPUC::fir< Numeric, Numeric >::iir(), and SPUC::fir< Numeric, Numeric >::update().
template<class Numeric, class Coeff = float_type> std::vector<Numeric> SPUC::fir< Numeric, Coeff >::z
Referenced by SPUC::fir_interp< SPUC::complex< CNumeric >, float_type >::clock(), SPUC::fir_decim< Numeric, Coeff >::decim(), SPUC::get_input(), SPUC::fir_decim< Numeric, Coeff >::input(), and SPUC::fir_interp< SPUC::complex< CNumeric >, float_type >::input().
The documentation for this class was generated from the following file:
fir.h