SPUC: SPUC::nested_shelf_allpass_2< Numeric, Coeff > Class Template Reference
SPUC::nested_shelf_allpass_2< Numeric, Coeff > Class Template Reference
#include <nested_shelf_allpass_2.h>
Public Member Functions
nested_shelf_allpass_2 (Coeff B0, Coeff B1, Coeff k)
void reset ()
reset
void set_hpf (bool h)
void init (float_type fp, float_type k, float_type low_gain, float_type high_gain)
void print ()
void change (Coeff k)
Numeric clock (Numeric input)
Shift inputs by one time sample and place new sample into array.
Protected Attributes
int Delay
The 2 1st order allpass filters.
Coeff b0
Coeff b1
allpass_2nd< Numeric, Coeff > A0
allpass_2nd< Numeric, Coeff > A1
allpass_1< Numeric, Coeff > D0
Coeff kb
Coeff kc
bool hpf
Constructor & Destructor Documentation
template<class Numeric , class Coeff = float_type> SPUC::nested_shelf_allpass_2< Numeric, Coeff >::nested_shelf_allpass_2 (Coeff B0, Coeff B1, Coeff k) inline
References SPUC::nested_shelf_allpass_2< Numeric, Coeff >::reset().
Member Function Documentation
template<class Numeric , class Coeff = float_type> void SPUC::nested_shelf_allpass_2< Numeric, Coeff >::change (Coeff k) inline
References SPUC::nested_shelf_allpass_2< Numeric, Coeff >::b0, SPUC::nested_shelf_allpass_2< Numeric, Coeff >::b1, SPUC::allpass_1< Numeric, Coeff >::init(), and SPUC::allpass_2nd< Numeric, Coeff >::set_coeffs().
template<class Numeric , class Coeff = float_type> Numeric SPUC::nested_shelf_allpass_2< Numeric, Coeff >::clock (Numeric input) inline
Shift inputs by one time sample and place new sample into array.
References SPUC::allpass_1< Numeric, Coeff >::clock(), SPUC::allpass_2nd< Numeric, Coeff >::clock(), and SPUC::round().
template<class Numeric , class Coeff = float_type> void SPUC::nested_shelf_allpass_2< Numeric, Coeff >::init (float_type fp, float_type k, float_type low_gain, float_type high_gain) inline
References SPUC::nested_shelf_allpass_2< Numeric, Coeff >::b0, SPUC::nested_shelf_allpass_2< Numeric, Coeff >::b1, SPUC::butterworth_allpass(), SPUC::allpass_1< Numeric, Coeff >::init(), and SPUC::allpass_2nd< Numeric, Coeff >::set_coeffs().
template<class Numeric , class Coeff = float_type> void SPUC::nested_shelf_allpass_2< Numeric, Coeff >::print (void) inline
References SPUC::allpass_2nd< Numeric, Coeff >::a, SPUC::allpass_2nd< Numeric, Coeff >::b, and SPUC::allpass_1< Numeric, Coeff >::get_coefficient().
template<class Numeric , class Coeff = float_type> void SPUC::nested_shelf_allpass_2< Numeric, Coeff >::reset (void) inline
reset
References SPUC::allpass_2nd< Numeric, Coeff >::reset(), and SPUC::allpass_1< Numeric, Coeff >::reset().
Referenced by SPUC::nested_shelf_allpass_2< Numeric, Coeff >::nested_shelf_allpass_2().
template<class Numeric , class Coeff = float_type> void SPUC::nested_shelf_allpass_2< Numeric, Coeff >::set_hpf (bool h) inline
Member Data Documentation
template<class Numeric , class Coeff = float_type> allpass_2nd<Numeric,Coeff> SPUC::nested_shelf_allpass_2< Numeric, Coeff >::A0 protected
template<class Numeric , class Coeff = float_type> allpass_2nd<Numeric,Coeff> SPUC::nested_shelf_allpass_2< Numeric, Coeff >::A1 protected
template<class Numeric , class Coeff = float_type> Coeff SPUC::nested_shelf_allpass_2< Numeric, Coeff >::b0 protected
Referenced by SPUC::nested_shelf_allpass_2< Numeric, Coeff >::change(), and SPUC::nested_shelf_allpass_2< Numeric, Coeff >::init().
template<class Numeric , class Coeff = float_type> Coeff SPUC::nested_shelf_allpass_2< Numeric, Coeff >::b1 protected
Referenced by SPUC::nested_shelf_allpass_2< Numeric, Coeff >::change(), and SPUC::nested_shelf_allpass_2< Numeric, Coeff >::init().
template<class Numeric , class Coeff = float_type> allpass_1<Numeric,Coeff> SPUC::nested_shelf_allpass_2< Numeric, Coeff >::D0 protected
template<class Numeric , class Coeff = float_type> int SPUC::nested_shelf_allpass_2< Numeric, Coeff >::Delay protected
The 2 1st order allpass filters.
template<class Numeric , class Coeff = float_type> bool SPUC::nested_shelf_allpass_2< Numeric, Coeff >::hpf protected
template<class Numeric , class Coeff = float_type> Coeff SPUC::nested_shelf_allpass_2< Numeric, Coeff >::kb protected
template<class Numeric , class Coeff = float_type> Coeff SPUC::nested_shelf_allpass_2< Numeric, Coeff >::kc protected
The documentation for this class was generated from the following file:
nested_shelf_allpass_2.h