SPUC: SPUC::notch_allpass< Numeric, Coeff > Class Template Reference
SPUC::notch_allpass< Numeric, Coeff > Class Template Reference
SPUC double templates | IIR filters
IIR notch filter based on 2nd order allpass structure.
#include <notch_allpass.h>
Public Member Functions
notch_allpass (float_type fp, float_type k2)
notch_allpass (float_type fp)
notch_allpass ()
void set_coeffs (float_type fp, float_type k2)
void reset ()
Numeric clock (Numeric x)
Public Attributes
allpass_2nd< Numeric, Coeff > ap
Detailed Description
template<class Numeric, class Coeff = float_type>
class SPUC::notch_allpass< Numeric, Coeff >
IIR notch filter based on 2nd order allpass structure.
Author
Tony Kirke
Constructor & Destructor Documentation
template<class Numeric, class Coeff = float_type> SPUC::notch_allpass< Numeric, Coeff >::notch_allpass (float_type fp, float_type k2) inline
template<class Numeric, class Coeff = float_type> SPUC::notch_allpass< Numeric, Coeff >::notch_allpass (float_type fp) inline
template<class Numeric, class Coeff = float_type> SPUC::notch_allpass< Numeric, Coeff >::notch_allpass () inline
Member Function Documentation
template<class Numeric, class Coeff = float_type> Numeric SPUC::notch_allpass< Numeric, Coeff >::clock (Numeric x) inline
References SPUC::allpass_2nd< Numeric, Coeff >::clock().
Referenced by main().
template<class Numeric, class Coeff = float_type> void SPUC::notch_allpass< Numeric, Coeff >::reset (void) inline
References SPUC::allpass_2nd< Numeric, Coeff >::reset().
template<class Numeric, class Coeff = float_type> void SPUC::notch_allpass< Numeric, Coeff >::set_coeffs (float_type fp, float_type k2) inline
References SPUC::cos(), SPUC::allpass_2nd< Numeric, Coeff >::set_coeffs(), and TWOPI.
Member Data Documentation
template<class Numeric, class Coeff = float_type> allpass_2nd<Numeric,Coeff> SPUC::notch_allpass< Numeric, Coeff >::ap
The documentation for this class was generated from the following file:
notch_allpass.h