SPUC: SPUC::vector< T > Class Template Reference
SPUC::vector< T > Class Template Reference
#include <vector_class.h>
Public Member Functions
vector ()
vector (int size)
vector (const vector< T > &v)
~vector ()
int len () const
int size () const
void reset ()
void ones ()
T operator[] (int i) const
T operator() (int i) const
T & operator[] (int i)
T & operator() (int i)
vector & operator+= (const vector< T > &v)
vector & operator-= (const vector< T > &v)
vector & operator+= (const T t)
vector & operator-= (const T t)
vector & operator*= (const T t)
vector & operator/= (const T t)
void operator= (const T v)
void operator= (const vector< T > &v)
Protected Member Functions
void resize (int size)
Protected Attributes
smart_array< T > data
Constructor & Destructor Documentation
template<class T> SPUC::vector< T >::vector () inline
template<class T> SPUC::vector< T >::vector (int size) inline
template<class T> SPUC::vector< T >::vector (const vector< T > & v) inline
template<class T> SPUC::vector< T >::~vector () inline
Member Function Documentation
template<class T> int SPUC::vector< T >::len () const inline
Referenced by SPUC::elem_div(), SPUC::elem_mult(), SPUC::operator*(), SPUC::operator+(), SPUC::operator-(), and SPUC::operator/().
template<class T> void SPUC::vector< T >::ones () inline
template<class T> T SPUC::vector< T >::operator() (int i) const inline
template<class T> T& SPUC::vector< T >::operator() (int i) inline
template<class T> vector& SPUC::vector< T >::operator*= (const T t) inline
template<class T> vector& SPUC::vector< T >::operator+= (const vector< T > & v) inline
template<class T> vector& SPUC::vector< T >::operator+= (const T t) inline
template<class T> vector& SPUC::vector< T >::operator-= (const vector< T > & v) inline
template<class T> vector& SPUC::vector< T >::operator-= (const T t) inline
template<class T> vector& SPUC::vector< T >::operator/= (const T t) inline
template<class T> void SPUC::vector< T >::operator= (const T v) inline
template<class T> void SPUC::vector< T >::operator= (const vector< T > & v) inline
template<class T> T SPUC::vector< T >::operator[] (int i) const inline
template<class T> T& SPUC::vector< T >::operator[] (int i) inline
template<class T> void SPUC::vector< T >::reset (void) inline
template<class T> void SPUC::vector< T >::resize (int size) inline protected
Referenced by SPUC::vector< Numeric >::operator+=(), SPUC::vector< Numeric >::operator-=(), SPUC::vector< Numeric >::operator=(), and SPUC::vector< Numeric >::vector().
template<class T> int SPUC::vector< T >::size (void) const inline
Referenced by SPUC::matrix< Numeric >::operator=(), SPUC::vector< Numeric >::resize(), and SPUC::toeplitz().
Member Data Documentation
template<class T> smart_array<T> SPUC::vector< T >::data protected
Referenced by SPUC::vector< Numeric >::len(), SPUC::vector< Numeric >::ones(), SPUC::vector< Numeric >::operator()(), SPUC::vector< Numeric >::operator*=(), SPUC::vector< Numeric >::operator+=(), SPUC::vector< Numeric >::operator-=(), SPUC::vector< Numeric >::operator/=(), SPUC::vector< Numeric >::operator=(), SPUC::vector< Numeric >::operator[](), SPUC::vector< Numeric >::reset(), SPUC::vector< Numeric >::resize(), SPUC::vector< Numeric >::size(), and SPUC::vector< Numeric >::vector().
The documentation for this class was generated from the following files:
spuc_typedefs.h
vector_class.h