SPUC: SPUC::quantiser< Numeric > Class Template Reference
SPUC::quantiser< Numeric > Class Template Reference
Miscellaneous DSP | Simulation classes And functions
........
#include <quantiser.h>
Public Member Functions
quantiser (char h=0)
Constructor.
void set_bits (char h)
template<typename T >
T operator() (T x)
template<>
void set_bits (char h)
template<>
void set_bits (char h)
Protected Attributes
char size
float_type scale
Number of bits <= 8.
float_type iscale
Detailed Description
template<class Numeric>
class SPUC::quantiser< Numeric >
........
Class for ......... Bit width is specified in constructor. Default is 8 bits. Output type is specified as template parameter. Handles real and complex samples
Author
Tony Kirke
Tony Kirke
Constructor & Destructor Documentation
template<class Numeric> SPUC::quantiser< Numeric >::quantiser (char h = 0) inline
Constructor.
Member Function Documentation
template<class Numeric> template<typename T > T SPUC::quantiser< Numeric >::operator() (T x) inline
template<class Numeric> void SPUC::quantiser< Numeric >::set_bits (char h) inline
Referenced by SPUC::quantiser< Coeff >::quantiser(), SPUC::iir_lpf1< Numeric, Coeff >::set_round_bits(), SPUC::iir_exp1< Numeric, Coeff >::set_round_bits(), SPUC::iir_1st< Numeric, Coeff >::set_round_bits(), SPUC::iir_2nd< Numeric, Coeff >::set_round_bits(), SPUC::iir_shelf< Numeric, Coeff >::set_round_bits(), and SPUC::fir< Numeric, Numeric >::set_round_bits().
template<> void SPUC::quantiser< long >::set_bits (char h) inline
template<> void SPUC::quantiser< float_type >::set_bits (char h) inline
Member Data Documentation
template<class Numeric> float_type SPUC::quantiser< Numeric >::iscale protected
template<class Numeric> float_type SPUC::quantiser< Numeric >::scale protected
Number of bits <= 8.
template<class Numeric> char SPUC::quantiser< Numeric >::size protected
The documentation for this class was generated from the following file:
quantiser.h