SPUC: SPUC::quantizer< Numeric > Singleton Reference
SPUC::quantizer< Numeric > Singleton Reference
#include <spuc_typedefs.h>
Static Public Member Functions
static long quantized (Numeric x)
static long quantized_scale (float_type x, float_type ox, Numeric y)
Member Function Documentation
template<class Numeric > static long SPUC::quantizer< Numeric >::quantized (Numeric x) inline static
References SPUC::real_quantize().
Referenced by SPUC::quantize().
template<class Numeric > static long SPUC::quantizer< Numeric >::quantized_scale (float_type x, float_type ox, Numeric y) inline static
References SPUC::real_quantize().
The documentation for this singleton was generated from the following file:
quantizer.h