SPUC: SPUC::qam_conv_decoder Class Reference
SPUC::qam_conv_decoder Class Reference
SPUC non-template classes | Communication classes And functions
QAM convolutional decoder.
#include <qam_conv_decoder.h>
Public Member Functions
qam_conv_decoder (int index)
~qam_conv_decoder ()
void reset ()
void set_rate (int mod, int conv_rate)
set modulation and punctured coding rate
bool data_decode (complex< long > data_in)
return true when output is available
bool get_bit (void)
call when viterbi_ready is true
void clear_soft_decision (long rate)
clear soft decision array
Public Attributes
const long Max_bits_per_symbol
const long soft_decision_level
viterbi viterbi_decoder
std::vector< long > viterbi_input
long enc_rate
long rate_index
long soft_bit_counter
long rx_bits_per_symbol
long raw_bits_this_frame
long coded_bits_per_frame
long raw_bits_out
long sample
long serial
bool frame_ready
bool viterbi_ready
bool viterbi_data
bool output_buffer_empty
bool no_conv
Detailed Description
QAM convolutional decoder.
Author
Tony Kirke, Copyright(c) 2004
Tony Kirke
Constructor & Destructor Documentation
SPUC::qam_conv_decoder::qam_conv_decoder (int index) inline
References reset(), and set_rate().
SPUC::qam_conv_decoder::~qam_conv_decoder () inline
Member Function Documentation
void SPUC::qam_conv_decoder::clear_soft_decision (long rate)
clear soft decision array
References viterbi_input.
bool SPUC::qam_conv_decoder::data_decode (complex< long > data_in)
return true when output is available
References SPUC::viterbi::depuncture(), enc_rate, no_conv, SPUC::viterbi::output_ready, SPUC::qam_data_demap(), rate_index, rx_bits_per_symbol, soft_decision_level, viterbi_data, viterbi_decoder, viterbi_input, and viterbi_ready.
bool SPUC::qam_conv_decoder::get_bit (void) inline
call when viterbi_ready is true
void SPUC::qam_conv_decoder::reset (void) inline
References SPUC::viterbi::reset().
Referenced by qam_conv_decoder().
void SPUC::qam_conv_decoder::set_rate (int mod, int conv_rate) inline
set modulation and punctured coding rate
Referenced by qam_conv_decoder().
Member Data Documentation
long SPUC::qam_conv_decoder::coded_bits_per_frame
long SPUC::qam_conv_decoder::enc_rate
Referenced by data_decode().
bool SPUC::qam_conv_decoder::frame_ready
const long SPUC::qam_conv_decoder::Max_bits_per_symbol
bool SPUC::qam_conv_decoder::no_conv
Referenced by data_decode().
bool SPUC::qam_conv_decoder::output_buffer_empty
long SPUC::qam_conv_decoder::rate_index
Referenced by data_decode().
long SPUC::qam_conv_decoder::raw_bits_out
long SPUC::qam_conv_decoder::raw_bits_this_frame
long SPUC::qam_conv_decoder::rx_bits_per_symbol
Referenced by data_decode().
long SPUC::qam_conv_decoder::sample
long SPUC::qam_conv_decoder::serial
long SPUC::qam_conv_decoder::soft_bit_counter
const long SPUC::qam_conv_decoder::soft_decision_level
Referenced by data_decode().
bool SPUC::qam_conv_decoder::viterbi_data
Referenced by data_decode().
viterbi SPUC::qam_conv_decoder::viterbi_decoder
Referenced by data_decode().
std::vector<long> SPUC::qam_conv_decoder::viterbi_input
Referenced by clear_soft_decision(), and data_decode().
bool SPUC::qam_conv_decoder::viterbi_ready
Referenced by data_decode().
The documentation for this class was generated from the following files:
qam_conv_decoder.h
qam_conv_decoder.cpp