SPUC: SPUC::farrow_upsampler Class Reference
SPUC::farrow_upsampler Class Reference
SPUC non-template classes
Upsampler/interpolator using farrow structure.
#include <farrow_upsampler.h>
Public Member Functions
int need_sample (float_type t_inc, float_type x)
float_type output (float_type t_inc)
farrow_upsampler (int order=4)
Public Attributes
float_type time_offset
farrow< float_type > INTERP
Detailed Description
Upsampler/interpolator using farrow structure.
Essentially a wrapper around farrow to allow one to upsample by specifing a fractional time increment input should always be available, need_sample returns 1 when the input needs to be update for next call
Author
Tony Kirke
Constructor & Destructor Documentation
SPUC::farrow_upsampler::farrow_upsampler (int order = 4)
References time_offset.
Member Function Documentation
int SPUC::farrow_upsampler::need_sample (float_type t_inc, float_type x)
References SPUC::farrow< Numeric >::input(), INTERP, and time_offset.
Referenced by main().
float_type SPUC::farrow_upsampler::output (float_type t_inc)
References INTERP, SPUC::farrow< Numeric >::rephase(), and time_offset.
Referenced by main().
Member Data Documentation
farrow<float_type> SPUC::farrow_upsampler::INTERP
Referenced by need_sample(), and output().
float_type SPUC::farrow_upsampler::time_offset
Referenced by farrow_upsampler(), need_sample(), and output().
The documentation for this class was generated from the following files:
farrow_upsampler.h
farrow_upsampler.cpp