SPUC: SPUC::sim_qpsk_variable< Numeric > Class Template Reference
SPUC::sim_qpsk_variable< Numeric > Class Template Reference
SPUC templates with real parameters | Simulation classes And functions
A Class for simulating a variable rate QPSK system.
#include <sim_qpsk_variable.h>
Public Types
typedef fundtype< Numeric >::ftype CNumeric
typedef complex< CNumeric > complex_type
Public Member Functions
sim_qpsk_variable (void)
void loop_init (float_type actual, float_type time_offset=0)
void tx_step (void)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
void rx_step (complex< CNumeric > b)
void step (void)
void loop_end (void)
Public Attributes
qpsk_ber_test * BER_mon
quad_data< float_type > * tx_data_source
vco< float_type > * freq_offset
noise * n
qpsk_variable< Numeric > * RECEIVER
long num
float_type var
float_type snr
float_type timing_offset
long total_over
complex< float_type > data
complex< float_type > base
complex< float_type > main
complex< float_type > b_noise
float_type sum_s
float_type sum_n
long rcv_symbols
long count
int dec_rate_log
float_type resample_over
float_type agc_scale
float_type nominal_scale
float_type analog_agc
float_type analog_filter_gain
float_type analog_agc_gain
float_type actual_over
float_type tx_time_inc
int rc_delay
long symbol_nco_word
Detailed Description
template<class Numeric>
class SPUC::sim_qpsk_variable< Numeric >
A Class for simulating a variable rate QPSK system.
that includes transmitters, receivers, frequency offsets, gaussian noise, and a BER tester Based on sim_qpsk with some minor changes.
Author
Tony Kirke
Member Typedef Documentation
template<class Numeric> typedef fundtype<Numeric>::ftype SPUC::sim_qpsk_variable< Numeric >::CNumeric
template<class Numeric> typedef complex<CNumeric> SPUC::sim_qpsk_variable< Numeric >::complex_type
Constructor & Destructor Documentation
template<class Numeric> SPUC::sim_qpsk_variable< Numeric >::sim_qpsk_variable (void) inline
Member Function Documentation
template<class Numeric> void SPUC::sim_qpsk_variable< Numeric >::loop_end (void) inline
References SPUC::sim_qpsk_variable< Numeric >::BER_mon, SPUC::sim_qpsk_variable< Numeric >::freq_offset, SPUC::sim_qpsk_variable< Numeric >::n, SPUC::sim_qpsk_variable< Numeric >::RECEIVER, and SPUC::sim_qpsk_variable< Numeric >::tx_data_source.
Referenced by main().
template<class Numeric> void SPUC::sim_qpsk_variable< Numeric >::loop_init (float_type actual, float_type time_offset = 0) inline
References SPUC::sim_qpsk_variable< Numeric >::actual_over, SPUC::sim_qpsk_variable< Numeric >::analog_agc_gain, SPUC::qpsk_variable< Numeric >::carrier_loop_filter, SPUC::sim_qpsk_variable< Numeric >::dec_rate_log, SPUC::loop_filter< Numeric, Coeff >::k0, SPUC::loop_filter< Numeric, Coeff >::k1, SPUC::sim_qpsk_variable< Numeric >::nominal_scale, SPUC::qpsk_variable< Numeric >::rate_change, SPUC::quad_data< Numeric >::set_initial_offset(), SPUC::sqrt(), SPUC::sim_qpsk_variable< Numeric >::total_over, and TWOPI.
Referenced by main().
template<class Numeric> void SPUC::sim_qpsk_variable< Numeric >::rx_step (complex< CNumeric > b) inline
References SPUC::qpsk_variable< Numeric >::clock(), and SPUC::qpsk_variable< Numeric >::symclk().
Referenced by SPUC::sim_qpsk_variable< Numeric >::step().
template<class Numeric> void SPUC::sim_qpsk_variable< Numeric >::step (void) inline
References SPUC::sim_qpsk_variable< Numeric >::rx_step(), and SPUC::sim_qpsk_variable< Numeric >::tx_step().
Referenced by main().
template<class Numeric> void SPUC::sim_qpsk_variable< Numeric >::tx_step (void) inline
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
References SPUC::sim_qpsk_variable< Numeric >::agc_scale, SPUC::sim_qpsk_variable< Numeric >::b_noise, SPUC::noise::Cgauss(), SPUC::vco< Numeric >::clock(), SPUC::quad_data< Numeric >::get_sample(), and SPUC::magsq().
Referenced by SPUC::sim_qpsk_variable< Numeric >::step().
Member Data Documentation
template<class Numeric> float_type SPUC::sim_qpsk_variable< Numeric >::actual_over
Referenced by SPUC::sim_qpsk_variable< Numeric >::loop_init().
template<class Numeric> float_type SPUC::sim_qpsk_variable< Numeric >::agc_scale
Referenced by main(), and SPUC::sim_qpsk_variable< Numeric >::tx_step().
template<class Numeric> float_type SPUC::sim_qpsk_variable< Numeric >::analog_agc
template<class Numeric> float_type SPUC::sim_qpsk_variable< Numeric >::analog_agc_gain
Referenced by SPUC::sim_qpsk_variable< Numeric >::loop_init().
template<class Numeric> float_type SPUC::sim_qpsk_variable< Numeric >::analog_filter_gain
template<class Numeric> complex<float_type> SPUC::sim_qpsk_variable< Numeric >::b_noise
Referenced by SPUC::sim_qpsk_variable< Numeric >::tx_step().
template<class Numeric> complex<float_type> SPUC::sim_qpsk_variable< Numeric >::base
Referenced by main().
template<class Numeric> qpsk_ber_test* SPUC::sim_qpsk_variable< Numeric >::BER_mon
Referenced by SPUC::sim_qpsk_variable< Numeric >::loop_end(), and main().
template<class Numeric> long SPUC::sim_qpsk_variable< Numeric >::count
template<class Numeric> complex<float_type> SPUC::sim_qpsk_variable< Numeric >::data
template<class Numeric> int SPUC::sim_qpsk_variable< Numeric >::dec_rate_log
Referenced by SPUC::sim_qpsk_variable< Numeric >::loop_init().
template<class Numeric> vco<float_type>* SPUC::sim_qpsk_variable< Numeric >::freq_offset
Referenced by SPUC::sim_qpsk_variable< Numeric >::loop_end().
template<class Numeric> complex<float_type> SPUC::sim_qpsk_variable< Numeric >::main
template<class Numeric> noise* SPUC::sim_qpsk_variable< Numeric >::n
Referenced by SPUC::sim_qpsk_variable< Numeric >::loop_end().
template<class Numeric> float_type SPUC::sim_qpsk_variable< Numeric >::nominal_scale
Referenced by SPUC::sim_qpsk_variable< Numeric >::loop_init().
template<class Numeric> long SPUC::sim_qpsk_variable< Numeric >::num
Referenced by main().
template<class Numeric> int SPUC::sim_qpsk_variable< Numeric >::rc_delay
template<class Numeric> long SPUC::sim_qpsk_variable< Numeric >::rcv_symbols
Referenced by main().
template<class Numeric> qpsk_variable<Numeric>* SPUC::sim_qpsk_variable< Numeric >::RECEIVER
Referenced by SPUC::sim_qpsk_variable< Numeric >::loop_end(), and main().
template<class Numeric> float_type SPUC::sim_qpsk_variable< Numeric >::resample_over
template<class Numeric> float_type SPUC::sim_qpsk_variable< Numeric >::snr
Referenced by main().
template<class Numeric> float_type SPUC::sim_qpsk_variable< Numeric >::sum_n
Referenced by main().
template<class Numeric> float_type SPUC::sim_qpsk_variable< Numeric >::sum_s
Referenced by main().
template<class Numeric> long SPUC::sim_qpsk_variable< Numeric >::symbol_nco_word
template<class Numeric> float_type SPUC::sim_qpsk_variable< Numeric >::timing_offset
template<class Numeric> long SPUC::sim_qpsk_variable< Numeric >::total_over
Referenced by SPUC::sim_qpsk_variable< Numeric >::loop_init().
template<class Numeric> quad_data<float_type>* SPUC::sim_qpsk_variable< Numeric >::tx_data_source
Referenced by SPUC::sim_qpsk_variable< Numeric >::loop_end().
template<class Numeric> float_type SPUC::sim_qpsk_variable< Numeric >::tx_time_inc
template<class Numeric> float_type SPUC::sim_qpsk_variable< Numeric >::var
The documentation for this class was generated from the following file:
sim_qpsk_variable.h