SPUC: SPUC::qpsk_discriminators Class Reference
SPUC::qpsk_discriminators Class Reference
SPUC non-template classes | Communication classes And functions
A Class incorporating several symbol and carrier discriminators for QPSK.
#include <qpsk_discriminators.h>
Public Member Functions
void update (complex< long > data_in, complex< long > decision_in, int sym_pls)
void sample (complex< long > fmf_in, complex< long > data_in, complex< long > decision_in, int sym_pls)
qpsk_discriminators (int bpsk=0)
void set_mode (int bpsk=0)
long cross_prod_afc (void)
long quad (void)
long rcfd (void)
long dd_timing_disc (void)
long nda_timing_disc (void)
long symbol_lock_out (void)
long pll_disc (void)
Public Attributes
int bpsk_mode
complex< long > fmf
complex< long > prev_sam
complex< long > prev_sym
complex< long > data
complex< long > hard_decision_prev
complex< long > decision
delay< complex< long > > hard_decision_delay
delay< complex< long > > timing_disc_delay
Detailed Description
A Class incorporating several symbol and carrier discriminators for QPSK.
Author
Tony Kirke
Constructor & Destructor Documentation
SPUC::qpsk_discriminators::qpsk_discriminators (int bpsk = 0) inline
References bpsk_mode.
Member Function Documentation
long SPUC::qpsk_discriminators::cross_prod_afc (void)
References SPUC::cp_afc(), data, prev_sam, prev_sym, and sample().
Referenced by SPUC::qpsk_variable< Numeric >::clock().
long SPUC::qpsk_discriminators::dd_timing_disc (void)
References data, SPUC::dd_symbol(), decision, hard_decision_prev, and prev_sym.
Referenced by SPUC::qpsk_variable< Numeric >::clock().
long SPUC::qpsk_discriminators::nda_timing_disc (void)
References data, SPUC::nda_symbol(), and prev_sam.
Referenced by SPUC::qpsk_variable< Numeric >::clock().
long SPUC::qpsk_discriminators::pll_disc (void)
References SPUC::bpsk_dd_phase(), bpsk_mode, data, decision, SPUC::qpsk_dd_phase(), and SPUC::saturate().
Referenced by SPUC::qpsk_variable< Numeric >::clock().
long SPUC::qpsk_discriminators::quad (void)
References decision, prev_sam, and SPUC::qpsk_quadricorrelator().
Referenced by SPUC::qpsk_variable< Numeric >::clock().
long SPUC::qpsk_discriminators::rcfd (void)
References data, fmf, and SPUC::qpsk_rcfd().
void SPUC::qpsk_discriminators::sample (complex< long > fmf_in, complex< long > data_in, complex< long > decision_in, int sym_pls)
References fmf, and update().
Referenced by SPUC::qpsk_variable< Numeric >::clock(), and cross_prod_afc().
void SPUC::qpsk_discriminators::set_mode (int bpsk = 0) inline
References bpsk_mode.
Referenced by SPUC::qpsk_variable< Numeric >::qpsk_variable().
long SPUC::qpsk_discriminators::symbol_lock_out (void)
References data, SPUC::magsq(), and prev_sam.
Referenced by SPUC::qpsk_variable< Numeric >::clock().
void SPUC::qpsk_discriminators::update (complex< long > data_in, complex< long > decision_in, int sym_pls)
References data, decision, hard_decision_delay, hard_decision_prev, prev_sam, prev_sym, and timing_disc_delay.
Referenced by sample().
Member Data Documentation
int SPUC::qpsk_discriminators::bpsk_mode
Referenced by pll_disc(), qpsk_discriminators(), and set_mode().
complex<long> SPUC::qpsk_discriminators::data
Referenced by cross_prod_afc(), dd_timing_disc(), nda_timing_disc(), pll_disc(), rcfd(), symbol_lock_out(), and update().
complex<long> SPUC::qpsk_discriminators::decision
Referenced by dd_timing_disc(), pll_disc(), quad(), and update().
complex<long> SPUC::qpsk_discriminators::fmf
Referenced by rcfd(), and sample().
delay< complex<long> > SPUC::qpsk_discriminators::hard_decision_delay
Referenced by update().
complex<long> SPUC::qpsk_discriminators::hard_decision_prev
Referenced by dd_timing_disc(), and update().
complex<long> SPUC::qpsk_discriminators::prev_sam
Referenced by cross_prod_afc(), nda_timing_disc(), quad(), symbol_lock_out(), and update().
complex<long> SPUC::qpsk_discriminators::prev_sym
Referenced by cross_prod_afc(), dd_timing_disc(), and update().
delay< complex<long> > SPUC::qpsk_discriminators::timing_disc_delay
Referenced by update().
The documentation for this class was generated from the following files:
qpsk_discriminators.h
qpsk_discriminators.cpp