SPUC: SPUC::spuc_int< I_ > Class Template Reference
SPUC::spuc_int< I_ > Class Template Reference
A faster version of the older systemc spuc_int.
#include <spuc_int.h>
Public Types
typedef int_type_size
< NEXT_INT_SIZE< I_ >::val >
::int_type val_type
typedef int64_t max_val_type
Public Member Functions
spuc_int ()
constructors
spuc_int (const spuc_int &a)
From exact same type - just copy val.
spuc_int (const double &a)
spuc_int (const int8_t &a)
spuc_int (const int16_t &a)
spuc_int (const int32_t &a)
spuc_int (const int64_t &a)
spuc_int (const uint8_t &a)
spuc_int (const uint16_t &a)
spuc_int (const uint32_t &a)
spuc_int (const uint64_t &a)
template<int I_1>
spuc_int (const spuc_int< I_1 > &a)
from another spuc_int<>
val_type getVal () const
void from_int (int64_t x)
Conversions.
double to_double (void) const
int64_t to_int (void) const
bool operator! () const
operator int64_t () const
spuc_int & operator++ ()
spuc_int operator++ (int)
spuc_int & operator-- ()
spuc_int operator-- (int)
spuc_int & operator= (const spuc_int &a)
template<int I_1>
spuc_int< I_ > & operator= (const spuc_int< I_1 > &a)
spuc_int< I_+1 > operator- () const
sign operator
spuc_int< I_ > operator+ () const
spuc_int operator~ () const
bit flip
spuc_int & operator= (const int8_t &a)
spuc_int & operator= (const int16_t &a)
spuc_int & operator= (const int32_t &a)
spuc_int & operator= (const int64_t &a)
spuc_int & operator= (const uint8_t &a)
spuc_int & operator= (const uint16_t &a)
spuc_int & operator= (const uint32_t &a)
spuc_int & operator= (const uint64_t &a)
spuc_int & operator= (const double &a)
template<int I_1>
spuc_int & operator+= (const spuc_int< I_1 > &a)
template<int I_1>
spuc_int & operator-= (const spuc_int< I_1 > &a)
template<int I_1>
spuc_int & operator*= (const spuc_int< I_1 > &b)
spuc_int & operator+= (const int8_t &b)
spuc_int & operator-= (const int8_t &b)
spuc_int & operator*= (const int8_t &b)
spuc_int & operator/= (const int8_t &b)
spuc_int & operator+= (const int16_t &b)
spuc_int & operator-= (const int16_t &b)
spuc_int & operator*= (const int16_t &b)
spuc_int & operator/= (const int16_t &b)
spuc_int & operator+= (const int32_t &b)
spuc_int & operator-= (const int32_t &b)
spuc_int & operator*= (const int32_t &b)
spuc_int & operator/= (const int32_t &b)
spuc_int & operator+= (const int64_t &b)
spuc_int & operator-= (const int64_t &b)
spuc_int & operator*= (const int64_t &b)
spuc_int & operator/= (const int64_t &b)
spuc_int & operator+= (const uint8_t &b)
spuc_int & operator-= (const uint8_t &b)
spuc_int & operator*= (const uint8_t &b)
spuc_int & operator/= (const uint8_t &b)
spuc_int & operator+= (const uint16_t &b)
spuc_int & operator-= (const uint16_t &b)
spuc_int & operator*= (const uint16_t &b)
spuc_int & operator/= (const uint16_t &b)
spuc_int & operator+= (const uint32_t &b)
spuc_int & operator-= (const uint32_t &b)
spuc_int & operator*= (const uint32_t &b)
spuc_int & operator/= (const uint32_t &b)
spuc_int & operator+= (const uint64_t &b)
spuc_int & operator-= (const uint64_t &b)
spuc_int & operator*= (const uint64_t &b)
spuc_int & operator/= (const uint64_t &b)
spuc_int & operator*= (const double &a)
spuc_int & operator/= (const double &a)
spuc_int & operator+= (const double &a)
spuc_int & operator-= (const double &a)
spuc_int & operator>>= (const int &a)
spuc_int & operator<<= (const int &a)
template<typename T >
spuc_int & operator&= (const T &l)
template<typename T >
spuc_int & operator|= (const T &l)
template<typename T >
spuc_int & operator^= (const T &l)
void print (std::ostream &os=::std::cout) const
Public Attributes
val_type val
Static Public Attributes
static const int INTEGER_BITS = I_
Detailed Description
template<int I_>
class SPUC::spuc_int< I_ >
A faster version of the older systemc spuc_int.
Member Typedef Documentation
template<int I_> typedef int64_t SPUC::spuc_int< I_ >::max_val_type
template<int I_> typedef int_type_size<NEXT_INT_SIZE<I_>::val>::int_type SPUC::spuc_int< I_ >::val_type
Constructor & Destructor Documentation
template<int I_> SPUC::spuc_int< I_ >::spuc_int () inline
constructors
Referenced by SPUC::spuc_int< TOTAL_BITS_ >::operator=().
template<int I_> SPUC::spuc_int< I_ >::spuc_int (const spuc_int< I_ > & a) inline
From exact same type - just copy val.
template<int I_> SPUC::spuc_int< I_ >::spuc_int (const double & a) inline
template<int I_> SPUC::spuc_int< I_ >::spuc_int (const int8_t & a) inline
template<int I_> SPUC::spuc_int< I_ >::spuc_int (const int16_t & a) inline
template<int I_> SPUC::spuc_int< I_ >::spuc_int (const int32_t & a) inline
template<int I_> SPUC::spuc_int< I_ >::spuc_int (const int64_t & a) inline
template<int I_> SPUC::spuc_int< I_ >::spuc_int (const uint8_t & a) inline
template<int I_> SPUC::spuc_int< I_ >::spuc_int (const uint16_t & a) inline
template<int I_> SPUC::spuc_int< I_ >::spuc_int (const uint32_t & a) inline
template<int I_> SPUC::spuc_int< I_ >::spuc_int (const uint64_t & a) inline
template<int I_> template<int I_1> SPUC::spuc_int< I_ >::spuc_int (const spuc_int< I_1 > & a) inline
from another spuc_int<>
Member Function Documentation
template<int I_> void SPUC::spuc_int< I_ >::from_int (int64_t x) inline
Conversions.
template<int I_> val_type SPUC::spuc_int< I_ >::getVal () const inline
Referenced by SPUC::operator*(), SPUC::spuc_int< TOTAL_BITS_ >::operator*=(), SPUC::spuc_int< TOTAL_BITS_ >::operator+=(), SPUC::spuc_int< TOTAL_BITS_ >::operator-=(), SPUC::operator/(), SPUC::spuc_int< TOTAL_BITS_ >::operator/=(), and SPUC::spuc_int< TOTAL_BITS_ >::operator=().
template<int I_> SPUC::spuc_int< I_ >::operator int64_t () const inline
template<int I_> bool SPUC::spuc_int< I_ >::operator! () const inline
template<int I_> template<typename T > spuc_int& SPUC::spuc_int< I_ >::operator&= (const T & l) inline
template<int I_> template<int I_1> spuc_int& SPUC::spuc_int< I_ >::operator*= (const spuc_int< I_1 > & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator*= (const int8_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator*= (const int16_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator*= (const int32_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator*= (const int64_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator*= (const uint8_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator*= (const uint16_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator*= (const uint32_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator*= (const uint64_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator*= (const double & a) inline
template<int I_> spuc_int<I_> SPUC::spuc_int< I_ >::operator+ () const inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator++ () inline
template<int I_> spuc_int SPUC::spuc_int< I_ >::operator++ (int) inline
template<int I_> template<int I_1> spuc_int& SPUC::spuc_int< I_ >::operator+= (const spuc_int< I_1 > & a) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator+= (const int8_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator+= (const int16_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator+= (const int32_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator+= (const int64_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator+= (const uint8_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator+= (const uint16_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator+= (const uint32_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator+= (const uint64_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator+= (const double & a) inline
template<int I_> spuc_int<I_ + 1> SPUC::spuc_int< I_ >::operator- () const inline
sign operator
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator-- () inline
template<int I_> spuc_int SPUC::spuc_int< I_ >::operator-- (int) inline
template<int I_> template<int I_1> spuc_int& SPUC::spuc_int< I_ >::operator-= (const spuc_int< I_1 > & a) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator-= (const int8_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator-= (const int16_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator-= (const int32_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator-= (const int64_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator-= (const uint8_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator-= (const uint16_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator-= (const uint32_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator-= (const uint64_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator-= (const double & a) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator/= (const int8_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator/= (const int16_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator/= (const int32_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator/= (const int64_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator/= (const uint8_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator/= (const uint16_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator/= (const uint32_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator/= (const uint64_t & b) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator/= (const double & a) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator<<= (const int & a) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator= (const spuc_int< I_ > & a) inline
template<int I_> template<int I_1> spuc_int<I_>& SPUC::spuc_int< I_ >::operator= (const spuc_int< I_1 > & a) inline
assignment operator from another size, use copy constructor, then copy val;
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator= (const int8_t & a) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator= (const int16_t & a) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator= (const int32_t & a) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator= (const int64_t & a) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator= (const uint8_t & a) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator= (const uint16_t & a) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator= (const uint32_t & a) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator= (const uint64_t & a) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator= (const double & a) inline
template<int I_> spuc_int& SPUC::spuc_int< I_ >::operator>>= (const int & a) inline
template<int I_> template<typename T > spuc_int& SPUC::spuc_int< I_ >::operator^= (const T & l) inline
template<int I_> template<typename T > spuc_int& SPUC::spuc_int< I_ >::operator|= (const T & l) inline
template<int I_> spuc_int SPUC::spuc_int< I_ >::operator~ (void) const inline
bit flip
template<int I_> void SPUC::spuc_int< I_ >::print (std::ostream & os = ::std::cout) const inline
template<int I_> double SPUC::spuc_int< I_ >::to_double (void) const inline
Referenced by SPUC::operator!=(), SPUC::operator==(), SPUC::operator>(), and SPUC::operator>=().
template<int I_> int64_t SPUC::spuc_int< I_ >::to_int (void) const inline
Referenced by SPUC::operator!=(), SPUC::operator*(), SPUC::operator==(), SPUC::operator>(), SPUC::operator>=(), and SPUC::spuc_int< TOTAL_BITS_ >::print().
Member Data Documentation
template<int I_> const int SPUC::spuc_int< I_ >::INTEGER_BITS = I_ static
template<int I_> val_type SPUC::spuc_int< I_ >::val
Referenced by SPUC::spuc_int< TOTAL_BITS_ >::from_int(), SPUC::spuc_int< TOTAL_BITS_ >::getVal(), SPUC::spuc_int< TOTAL_BITS_ >::operator int64_t(), SPUC::spuc_int< TOTAL_BITS_ >::operator!(), SPUC::operator&(), SPUC::spuc_int< TOTAL_BITS_ >::operator&=(), SPUC::operator*(), SPUC::spuc_int< TOTAL_BITS_ >::operator*=(), SPUC::spuc_int< TOTAL_BITS_ >::operator++(), SPUC::spuc_int< TOTAL_BITS_ >::operator+=(), SPUC::spuc_int< TOTAL_BITS_ >::operator-(), SPUC::spuc_int< TOTAL_BITS_ >::operator--(), SPUC::spuc_int< TOTAL_BITS_ >::operator-=(), SPUC::operator/(), SPUC::spuc_int< TOTAL_BITS_ >::operator/=(), SPUC::operator<(), SPUC::spuc_int< TOTAL_BITS_ >::operator<<=(), SPUC::spuc_int< TOTAL_BITS_ >::operator=(), SPUC::operator==(), SPUC::spuc_int< TOTAL_BITS_ >::operator>>=(), SPUC::operator^(), SPUC::spuc_int< TOTAL_BITS_ >::operator^=(), SPUC::operator|(), SPUC::spuc_int< TOTAL_BITS_ >::operator|=(), SPUC::spuc_int< TOTAL_BITS_ >::operator~(), SPUC::spuc_int< TOTAL_BITS_ >::spuc_int(), SPUC::spuc_int< TOTAL_BITS_ >::to_double(), and SPUC::spuc_int< TOTAL_BITS_ >::to_int().
The documentation for this class was generated from the following file:
spuc_int.h