SPUC: SPUC::lms_dfe< Numeric, Coeff > Class Template Reference
SPUC::lms_dfe< Numeric, Coeff > Class Template Reference
SPUC double templates restricted | Equalization classes And functions | Communication classes And functions
Template Class for LMS Decision Feedback equalizer.
#include <lms_dfe.h>
Public Types
typedef base_type< Numeric >::btype real_type
Public Member Functions
lms_dfe (char inf=16, char inb=0, real_type gain=0, Numeric mid_val=1)
Constructor with feedforward size, feedback size and gain.
~lms_dfe ()
void reset ()
void set_ff_tap (long i, Numeric x)
void set_fb_tap (long i, Numeric x)
Coeff get_ff_tap (long x)
Coeff get_fb_tap (long x)
long ff_size ()
long fb_size ()
void set_gain (real_type g)
Numeric update (Numeric in, Numeric slicer_output)
void update_taps_lms (Numeric err)
Public Attributes
fir_adapt< Numeric, Coeff > ff
Feedforward FIR section.
fir_adapt< Numeric, Coeff > fb
Feedback FIR section.
real_type u
Adaptation Gain.
Numeric mid_tap
Detailed Description
template<class Numeric, class Coeff = double>
class SPUC::lms_dfe< Numeric, Coeff >
Template Class for LMS Decision Feedback equalizer.
Author
Tony Kirke
Tony Kirke
Member Typedef Documentation
template<class Numeric , class Coeff = double> typedef base_type<Numeric>::btype SPUC::lms_dfe< Numeric, Coeff >::real_type
Constructor & Destructor Documentation
template<class Numeric , class Coeff = double> SPUC::lms_dfe< Numeric, Coeff >::lms_dfe (char inf = 16, char inb = 0, real_type gain = 0, Numeric mid_val = 1) inline
Constructor with feedforward size, feedback size and gain.
References SPUC::fir< Numeric, Coeff >::coeff, SPUC::lms_dfe< Numeric, Coeff >::mid_tap, SPUC::fir_adapt< Numeric, Coeff >::set_gain(), and SPUC::fir< Numeric, Coeff >::set_size().
template<class Numeric , class Coeff = double> SPUC::lms_dfe< Numeric, Coeff >::~lms_dfe () inline
Member Function Documentation
template<class Numeric , class Coeff = double> long SPUC::lms_dfe< Numeric, Coeff >::fb_size () inline
References SPUC::fir< Numeric, Coeff >::num_taps.
template<class Numeric , class Coeff = double> long SPUC::lms_dfe< Numeric, Coeff >::ff_size () inline
References SPUC::fir< Numeric, Coeff >::num_taps.
template<class Numeric , class Coeff = double> Coeff SPUC::lms_dfe< Numeric, Coeff >::get_fb_tap (long x) inline
References SPUC::fir< Numeric, Coeff >::coeff.
template<class Numeric , class Coeff = double> Coeff SPUC::lms_dfe< Numeric, Coeff >::get_ff_tap (long x) inline
References SPUC::fir< Numeric, Coeff >::coeff.
template<class Numeric , class Coeff = double> void SPUC::lms_dfe< Numeric, Coeff >::reset (void) inline
References SPUC::fir< Numeric, Coeff >::num_taps, SPUC::fir_adapt< Numeric, Coeff >::reset(), and SPUC::fir< Numeric, Coeff >::settap().
template<class Numeric , class Coeff = double> void SPUC::lms_dfe< Numeric, Coeff >::set_fb_tap (long i, Numeric x) inline
References SPUC::fir< Numeric, Coeff >::coeff.
template<class Numeric , class Coeff = double> void SPUC::lms_dfe< Numeric, Coeff >::set_ff_tap (long i, Numeric x) inline
References SPUC::fir< Numeric, Coeff >::coeff.
template<class Numeric , class Coeff = double> void SPUC::lms_dfe< Numeric, Coeff >::set_gain (real_type g) inline
References SPUC::fir_adapt< Numeric, Coeff >::set_gain().
template<class Numeric , class Coeff = double> Numeric SPUC::lms_dfe< Numeric, Coeff >::update (Numeric in, Numeric slicer_output) inline
References SPUC::fir< Numeric, Coeff >::num_taps, and SPUC::fir< Numeric, Coeff >::update().
template<class Numeric , class Coeff = double> void SPUC::lms_dfe< Numeric, Coeff >::update_taps_lms (Numeric err) inline
References SPUC::fir< Numeric, Coeff >::num_taps, and SPUC::fir_adapt< Numeric, Coeff >::update_lms().
Member Data Documentation
template<class Numeric , class Coeff = double> fir_adapt< Numeric, Coeff > SPUC::lms_dfe< Numeric, Coeff >::fb
Feedback FIR section.
template<class Numeric , class Coeff = double> fir_adapt< Numeric, Coeff > SPUC::lms_dfe< Numeric, Coeff >::ff
Feedforward FIR section.
template<class Numeric , class Coeff = double> Numeric SPUC::lms_dfe< Numeric, Coeff >::mid_tap
Referenced by SPUC::lms_dfe< Numeric, Coeff >::lms_dfe().
template<class Numeric , class Coeff = double> real_type SPUC::lms_dfe< Numeric, Coeff >::u
Adaptation Gain.
The documentation for this class was generated from the following file:
lms_dfe.h