SPUC: SPUC::sum_and_dump< Numeric > Class Template Reference
SPUC::sum_and_dump< Numeric > Class Template Reference
SPUC templates | FIR filters
sum and dump filter
#include <sum_and_dump.h>
Public Member Functions
sum_and_dump (long exp=0)
Numeric get_sum ()
void reset ()
Numeric output (void)
void set_exp (long exp)
Numeric run (Numeric in_val)
void input (Numeric in_val)
Public Attributes
Numeric average
Numeric result
long count_exp
long count
long count_val
Detailed Description
template<class Numeric>
class SPUC::sum_and_dump< Numeric >
sum and dump filter
This modules sums the input for a fixed number of samples stores the result and begins a new summation. Similar to an integrate and dump function
Author
="Tony Kirke" Copyright(c) 1993-1996
Tony Kirke
Constructor & Destructor Documentation
template<class Numeric> SPUC::sum_and_dump< Numeric >::sum_and_dump (long exp = 0) inline
Member Function Documentation
template<class Numeric> Numeric SPUC::sum_and_dump< Numeric >::get_sum () inline
template<class Numeric> void SPUC::sum_and_dump< Numeric >::input (Numeric in_val) inline
Referenced by SPUC::qpsk_variable< Numeric >::clock(), and SPUC::sum_and_dump< CNumeric >::run().
template<class Numeric> Numeric SPUC::sum_and_dump< Numeric >::output (void) inline
Referenced by SPUC::qpsk_variable< Numeric >::clock().
template<class Numeric> void SPUC::sum_and_dump< Numeric >::reset (void) inline
template<class Numeric> Numeric SPUC::sum_and_dump< Numeric >::run (Numeric in_val) inline
template<class Numeric> void SPUC::sum_and_dump< Numeric >::set_exp (long exp) inline
Referenced by SPUC::qpsk_variable< Numeric >::qpsk_variable().
Member Data Documentation
template<class Numeric> Numeric SPUC::sum_and_dump< Numeric >::average
Referenced by SPUC::sum_and_dump< CNumeric >::get_sum(), and SPUC::sum_and_dump< CNumeric >::input().
template<class Numeric> long SPUC::sum_and_dump< Numeric >::count
template<class Numeric> long SPUC::sum_and_dump< Numeric >::count_exp
Referenced by SPUC::sum_and_dump< CNumeric >::set_exp(), and SPUC::sum_and_dump< CNumeric >::sum_and_dump().
template<class Numeric> long SPUC::sum_and_dump< Numeric >::count_val
template<class Numeric> Numeric SPUC::sum_and_dump< Numeric >::result
Referenced by SPUC::sum_and_dump< CNumeric >::run().
The documentation for this class was generated from the following file:
sum_and_dump.h