SPUC: SPUC::allpass< Numeric, Coeff > Class Template Reference
SPUC::allpass< Numeric, Coeff > Class Template Reference
SPUC double templates | Allpass filters
Template Class for allpass filter consisting of several stages of 1st order allpass sections.
#include <allpass.h>
Public Member Functions
allpass (std::vector< Coeff > &design, int n)
ord = Filter order
Coeff get_coefficient (int i)
allpass (long n=1)
ord = Filter order
void init (std::vector< Coeff > &design, int n, int d=2)
~allpass ()
Destructor.
void reset ()
Reset history.
void set_coeffs (std::vector< Coeff > &design, int d=2)
Set 1st order ALLPASS coefficients.
Numeric clock (Numeric in)
Clock in sample and get output.
Public Attributes
long stages
std::vector< allpass_1
< Numeric, Coeff > > ap
Detailed Description
template<class Numeric, class Coeff = float_type>
class SPUC::allpass< Numeric, Coeff >
Template Class for allpass filter consisting of several stages of 1st order allpass sections.
Author
Tony Kirke
Constructor & Destructor Documentation
template<class Numeric, class Coeff = float_type> SPUC::allpass< Numeric, Coeff >::allpass (std::vector< Coeff > & design, int n) inline
ord = Filter order
References SPUC::allpass< Numeric, Coeff >::set_coeffs().
template<class Numeric, class Coeff = float_type> SPUC::allpass< Numeric, Coeff >::allpass (long n = 1) inline
ord = Filter order
template<class Numeric, class Coeff = float_type> SPUC::allpass< Numeric, Coeff >::~allpass () inline
Destructor.
Member Function Documentation
template<class Numeric, class Coeff = float_type> Numeric SPUC::allpass< Numeric, Coeff >::clock (Numeric in) inline
Clock in sample and get output.
References SPUC::allpass< Numeric, Coeff >::stages.
Referenced by SPUC::iir_allpass_variable_cascade< Numeric, Coeff >::clock(), and SPUC::iir_allpass1_cascade< Numeric, Coeff >::clock().
template<class Numeric, class Coeff = float_type> Coeff SPUC::allpass< Numeric, Coeff >::get_coefficient (int i) inline
References SPUC::allpass< Numeric, Coeff >::get_coefficient().
Referenced by SPUC::allpass< Numeric, Coeff >::get_coefficient().
template<class Numeric, class Coeff = float_type> void SPUC::allpass< Numeric, Coeff >::init (std::vector< Coeff > & design, int n, int d = 2) inline
References SPUC::allpass< Numeric, Coeff >::set_coeffs().
Referenced by SPUC::iir_allpass1_cascade< Numeric, Coeff >::iir_allpass1_cascade(), SPUC::iir_allpass_variable_cascade< Numeric, Coeff >::iir_allpass_variable_cascade(), SPUC::allpass< Numeric, Coeff >::set_coeffs(), SPUC::iir_allpass_variable_cascade< Numeric, Coeff >::set_coeffs(), and SPUC::iir_allpass1_cascade< Numeric, Coeff >::set_coeffs().
template<class Numeric, class Coeff = float_type> void SPUC::allpass< Numeric, Coeff >::reset () inline
Reset history.
References SPUC::allpass< Numeric, Coeff >::stages.
Referenced by SPUC::iir_allpass_variable_cascade< Numeric, Coeff >::reset(), and SPUC::iir_allpass1_cascade< Numeric, Coeff >::reset().
template<class Numeric, class Coeff = float_type> void SPUC::allpass< Numeric, Coeff >::set_coeffs (std::vector< Coeff > & design, int d = 2) inline
Set 1st order ALLPASS coefficients.
References SPUC::allpass< Numeric, Coeff >::init(), and SPUC::allpass< Numeric, Coeff >::stages.
Referenced by SPUC::allpass< Numeric, Coeff >::allpass(), and SPUC::allpass< Numeric, Coeff >::init().
Member Data Documentation
template<class Numeric, class Coeff = float_type> std::vector<allpass_1<Numeric,Coeff> > SPUC::allpass< Numeric, Coeff >::ap
Referenced by SPUC::iir_allpass_variable_cascade< Numeric, Coeff >::get_a0(), SPUC::iir_allpass1_cascade< Numeric, Coeff >::get_a0(), SPUC::iir_allpass_variable_cascade< Numeric, Coeff >::get_a1(), and SPUC::iir_allpass1_cascade< Numeric, Coeff >::get_a1().
template<class Numeric, class Coeff = float_type> long SPUC::allpass< Numeric, Coeff >::stages
Referenced by SPUC::allpass< Numeric, Coeff >::clock(), SPUC::allpass< Numeric, Coeff >::reset(), and SPUC::allpass< Numeric, Coeff >::set_coeffs().
The documentation for this class was generated from the following file:
allpass.h