SPUC: SPUC::qam_mod Class Reference
SPUC::qam_mod Class Reference
SPUC non-template classes | Communication classes And functions
QAM Modulator for BPSK - 64 QAM for 802.11A Data modulation.
#include <qam_mod.h>
Public Member Functions
qam_mod (int index)
~qam_mod ()
complex< long > data_map (long r_ind, long data_in)
complex< long > bpsk_map (long data_in)
complex< long > qpsk_map (long data_in)
complex< long > qam16_map (long data_in)
complex< long > qam64_map (long data_in)
Public Attributes
long rate_index
Detailed Description
QAM Modulator for BPSK - 64 QAM for 802.11A Data modulation.
Author
Tony Kirke
Constructor & Destructor Documentation
SPUC::qam_mod::qam_mod (int index) inline
SPUC::qam_mod::~qam_mod () inline
Member Function Documentation
complex< long > SPUC::qam_mod::bpsk_map (long data_in)
Referenced by data_map().
complex< long > SPUC::qam_mod::data_map (long r_ind, long data_in)
References bpsk_map(), qam16_map(), qam64_map(), and qpsk_map().
Referenced by SPUC::qam_tx< float_type >::clock(), and SPUC::ofdm_data_encoder::data_map().
complex< long > SPUC::qam_mod::qam16_map (long data_in)
Referenced by data_map().
complex< long > SPUC::qam_mod::qam64_map (long data_in)
Referenced by data_map().
complex< long > SPUC::qam_mod::qpsk_map (long data_in)
Referenced by data_map().
Member Data Documentation
long SPUC::qam_mod::rate_index
Referenced by SPUC::qam_tx< float_type >::loop_init().
The documentation for this class was generated from the following files:
qam_mod.h
qam_mod.cpp