SPUC: SPUC::bpe< Numeric, Coeff > Class Template Reference
SPUC::bpe< Numeric, Coeff > Class Template Reference
SPUC double templates with real parameters | Communication classes And functions
Block Phase Estimator.
#include <bpe.h>
Public Member Functions
float_type angle ()
length of BPE
complex< Numeric > refvect (void)
Reference Vector.
bpe (char len=16)
void clock (const complex< Numeric > &in)
Perform BPE but don't calculate output.
float_type fq_angle (const complex< Numeric > &pid)
complex< Numeric > output (const complex< Numeric > &in)
Perform BPE and return transformed input.
Detailed Description
template<class Numeric, class Coeff = double>
class SPUC::bpe< Numeric, Coeff >
Block Phase Estimator.
Unquantized BPE Calculate phase angle using a moving window Notes: Note that the BPE only cares about the phase of a vector, and not on the actual vector magnitude. This results in a degradation of the average bpe vector magnitude as Eb/No decreases.
Author
Tony Kirke
Constructor & Destructor Documentation
template<class Numeric , class Coeff = double> SPUC::bpe< Numeric, Coeff >::bpe (char len = 16) inline
Member Function Documentation
template<class Numeric , class Coeff = double> float_type SPUC::bpe< Numeric, Coeff >::angle () inline
length of BPE
template<class Numeric , class Coeff = double> void SPUC::bpe< Numeric, Coeff >::clock (const complex< Numeric > & in) inline
Perform BPE but don't calculate output.
References SPUC::arg(), SPUC::bpe< Numeric, Coeff >::fq_angle(), PI, SPUC::polar(), RTD, and TWOPI.
Referenced by SPUC::bpe< Numeric, Coeff >::output().
template<class Numeric , class Coeff = double> float_type SPUC::bpe< Numeric, Coeff >::fq_angle (const complex< Numeric > & pid) inline
References SPUC::arg(), PI, and TWOPI.
Referenced by SPUC::bpe< Numeric, Coeff >::clock().
template<class Numeric , class Coeff = double> complex<Numeric> SPUC::bpe< Numeric, Coeff >::output (const complex< Numeric > & in) inline
Perform BPE and return transformed input.
References SPUC::bpe< Numeric, Coeff >::clock(), and SPUC::bpe< Numeric, Coeff >::refvect().
template<class Numeric , class Coeff = double> complex<Numeric> SPUC::bpe< Numeric, Coeff >::refvect (void) inline
Reference Vector.
current averaged angle
Referenced by SPUC::bpe< Numeric, Coeff >::output().
The documentation for this class was generated from the following file:
bpe.h