SPUC: SPUC::sim_qam< Numeric > Class Template Reference
SPUC::sim_qam< Numeric > Class Template Reference
SPUC templates with real parameters | Simulation classes And functions
A Class for simulating a QAM system.
#include <sim_qam.h>
Public Types
typedef fundtype< Numeric >::ftype CNumeric
typedef complex< CNumeric > complex_type
Public Member Functions
~sim_qam ()
sim_qam (float_type rc_alpha=0.25)
void loop_init (long rate, long conv_rate, float_type carrier_off=0, float_type time_off=0)
complex< float_type > tx_step ()
void step (void)
complex< long > rx_step (complex_type x)
void loop_end (void)
Public Attributes
const long over
float_type alpha
lagrange< complex< float_type > > interp
fir< complex< float_type >
, float_type > rx_filter
qam_tx< float_type > TX
noise * n
base_demod< Numeric > * DUT
vco< float_type > * freq_offset
a_d * ADC
float_type var
float_type snr
float_type channel_pwr
complex< float_type > tx_data
complex< long > data
long output_delay
long rate
bool enable_freq_offset
bool enable_time_offset
float_type carrier_offset_rate
float_type time_inc
float_type time_offset
complex_type adc_out
complex< float_type > base
complex< float_type > main
complex< float_type > main1
complex< float_type > base1
complex< float_type > b_noise
long rcv_symbols
long tx_symbols
long count
float_type phase_inc
float_type phase_acc
Detailed Description
template<class Numeric>
class SPUC::sim_qam< Numeric >
A Class for simulating a QAM system.
that includes transmitters, receivers, A/D, frequency offsets, gaussian noise, and a BER tester
Author
Tony Kirke
Member Typedef Documentation
template<class Numeric > typedef fundtype<Numeric>::ftype SPUC::sim_qam< Numeric >::CNumeric
template<class Numeric > typedef complex<CNumeric> SPUC::sim_qam< Numeric >::complex_type
Constructor & Destructor Documentation
template<class Numeric > SPUC::sim_qam< Numeric >::~sim_qam () inline
References SPUC::sim_qam< Numeric >::n.
template<class Numeric > SPUC::sim_qam< Numeric >::sim_qam (float_type rc_alpha = 0.25) inline
References SPUC::fir< Numeric, Coeff >::coeff, SPUC::fir< Numeric, Coeff >::num_taps, SPUC::root_raised_cosine(), and SPUC::fir< Numeric, Coeff >::settaps().
Member Function Documentation
template<class Numeric > void SPUC::sim_qam< Numeric >::loop_end (void) inline
References SPUC::sim_qam< Numeric >::ADC, SPUC::sim_qam< Numeric >::freq_offset, SPUC::lagrange< Numeric, Coeff >::reset(), and SPUC::fir< Numeric, Coeff >::reset().
template<class Numeric > void SPUC::sim_qam< Numeric >::loop_init (long rate, long conv_rate, float_type carrier_off = 0, float_type time_off = 0) inline
References SPUC::qam_tx< Numeric >::loop_init(), SPUC::fir< Numeric, Coeff >::reset(), SPUC::vco< Numeric >::reset_frequency(), and SPUC::sqrt().
template<class Numeric > complex<long> SPUC::sim_qam< Numeric >::rx_step (complex_type x) inline
References SPUC::base_demod< Numeric >::step(), and SPUC::base_demod< Numeric >::sym_pulse().
Referenced by SPUC::sim_qam< Numeric >::step().
template<class Numeric > void SPUC::sim_qam< Numeric >::step (void) inline
References SPUC::a_d::clock(), SPUC::sim_qam< Numeric >::rx_step(), and SPUC::sim_qam< Numeric >::tx_step().
template<class Numeric > complex<float_type> SPUC::sim_qam< Numeric >::tx_step () inline
References SPUC::sim_qam< Numeric >::b_noise, SPUC::noise::Cgauss(), SPUC::vco< Numeric >::clock(), SPUC::qam_tx< Numeric >::clock(), SPUC::qam_tx< Numeric >::data_level, SPUC::lagrange< Numeric, Coeff >::input(), SPUC::lagrange< Numeric, Coeff >::rephase(), SPUC::sim_qam< Numeric >::time_inc, and SPUC::fir< Numeric, Coeff >::update().
Referenced by SPUC::sim_qam< Numeric >::step().
Member Data Documentation
template<class Numeric > a_d* SPUC::sim_qam< Numeric >::ADC
Referenced by SPUC::sim_qam< Numeric >::loop_end().
template<class Numeric > complex_type SPUC::sim_qam< Numeric >::adc_out
template<class Numeric > float_type SPUC::sim_qam< Numeric >::alpha
template<class Numeric > complex<float_type> SPUC::sim_qam< Numeric >::b_noise
Referenced by SPUC::sim_qam< Numeric >::tx_step().
template<class Numeric > complex<float_type> SPUC::sim_qam< Numeric >::base
template<class Numeric > complex<float_type> SPUC::sim_qam< Numeric >::base1
template<class Numeric > float_type SPUC::sim_qam< Numeric >::carrier_offset_rate
template<class Numeric > float_type SPUC::sim_qam< Numeric >::channel_pwr
template<class Numeric > long SPUC::sim_qam< Numeric >::count
template<class Numeric > complex<long> SPUC::sim_qam< Numeric >::data
template<class Numeric > base_demod<Numeric>* SPUC::sim_qam< Numeric >::DUT
template<class Numeric > bool SPUC::sim_qam< Numeric >::enable_freq_offset
template<class Numeric > bool SPUC::sim_qam< Numeric >::enable_time_offset
template<class Numeric > vco<float_type>* SPUC::sim_qam< Numeric >::freq_offset
Referenced by SPUC::sim_qam< Numeric >::loop_end().
template<class Numeric > lagrange<complex<float_type> > SPUC::sim_qam< Numeric >::interp
template<class Numeric > complex<float_type> SPUC::sim_qam< Numeric >::main
template<class Numeric > complex<float_type> SPUC::sim_qam< Numeric >::main1
template<class Numeric > noise* SPUC::sim_qam< Numeric >::n
Referenced by SPUC::sim_qam< Numeric >::~sim_qam().
template<class Numeric > long SPUC::sim_qam< Numeric >::output_delay
template<class Numeric > const long SPUC::sim_qam< Numeric >::over
template<class Numeric > float_type SPUC::sim_qam< Numeric >::phase_acc
template<class Numeric > float_type SPUC::sim_qam< Numeric >::phase_inc
template<class Numeric > long SPUC::sim_qam< Numeric >::rate
template<class Numeric > long SPUC::sim_qam< Numeric >::rcv_symbols
template<class Numeric > fir<complex<float_type>,float_type > SPUC::sim_qam< Numeric >::rx_filter
template<class Numeric > float_type SPUC::sim_qam< Numeric >::snr
template<class Numeric > float_type SPUC::sim_qam< Numeric >::time_inc
Referenced by SPUC::sim_qam< Numeric >::tx_step().
template<class Numeric > float_type SPUC::sim_qam< Numeric >::time_offset
template<class Numeric > qam_tx<float_type> SPUC::sim_qam< Numeric >::TX
template<class Numeric > complex<float_type> SPUC::sim_qam< Numeric >::tx_data
template<class Numeric > long SPUC::sim_qam< Numeric >::tx_symbols
template<class Numeric > float_type SPUC::sim_qam< Numeric >::var
The documentation for this class was generated from the following file:
sim_qam.h