SPUC: SPUC::qpsk_ber_test Class Reference
SPUC::qpsk_ber_test Class Reference
SPUC non-template classes | Simulation classes And functions
A Class for doing BER test on QPSK.
#include <qpsk_ber_test.h>
Public Member Functions
qpsk_ber_test (void)
void reset (void)
void init_delay (int c)
bool found_sync (void)
void ber_results (long received)
long synchronize (long *received, complex< long > data)
long synchronise (long received, complex< double > data)
void final_results (long received)
void correlate (long *received, complex< long > data)
void print_running_ber (void)
float_type running_ber (void)
float_type ber (long received)
Public Attributes
long modc
time_t start_time
max_pn ref
complex< long > corr_sum
long errors
complex< long > rotate
bool sync
long interval
long prev_errors
Detailed Description
A Class for doing BER test on QPSK.
Author
Tony Kirke, Copyright(c) 2001
Tony Kirke
Constructor & Destructor Documentation
SPUC::qpsk_ber_test::qpsk_ber_test (void) inline
References reset().
Member Function Documentation
float_type SPUC::qpsk_ber_test::ber (long received) inline
References errors.
void SPUC::qpsk_ber_test::ber_results (long received)
References errors, modc, start_time, and sync.
Referenced by correlate(), and main().
void SPUC::qpsk_ber_test::correlate (long * received, complex< long > data) inline
References ber_results(), and synchronize().
void SPUC::qpsk_ber_test::final_results (long received)
References errors, start_time, and sync.
Referenced by main().
bool SPUC::qpsk_ber_test::found_sync (void) inline
References sync.
Referenced by main().
void SPUC::qpsk_ber_test::init_delay (int c) inline
References SPUC::max_pn::out(), and ref.
Referenced by main().
void SPUC::qpsk_ber_test::print_running_ber (void)
References interval, and running_ber().
void SPUC::qpsk_ber_test::reset (void) inline
References corr_sum, errors, interval, modc, prev_errors, ref, SPUC::max_pn::reset(), rotate, start_time, and sync.
Referenced by SPUC::sim_qpsk< Numeric >::loop_init(), and qpsk_ber_test().
float_type SPUC::qpsk_ber_test::running_ber (void)
References errors, interval, and prev_errors.
Referenced by print_running_ber().
long SPUC::qpsk_ber_test::synchronise (long received, complex< double > data)
References corr_sum, errors, interval, SPUC::max_pn::out(), ref, rotate, and sync.
long SPUC::qpsk_ber_test::synchronize (long * received, complex< long > data)
References corr_sum, errors, interval, SPUC::max_pn::out(), ref, rotate, and sync.
Referenced by correlate(), and main().
Member Data Documentation
complex<long> SPUC::qpsk_ber_test::corr_sum
Referenced by reset(), synchronise(), and synchronize().
long SPUC::qpsk_ber_test::errors
Referenced by ber(), ber_results(), final_results(), reset(), running_ber(), synchronise(), and synchronize().
long SPUC::qpsk_ber_test::interval
Referenced by print_running_ber(), reset(), running_ber(), synchronise(), and synchronize().
long SPUC::qpsk_ber_test::modc
Referenced by ber_results(), and reset().
long SPUC::qpsk_ber_test::prev_errors
Referenced by reset(), and running_ber().
max_pn SPUC::qpsk_ber_test::ref
Referenced by init_delay(), reset(), synchronise(), and synchronize().
complex<long> SPUC::qpsk_ber_test::rotate
Referenced by reset(), synchronise(), and synchronize().
time_t SPUC::qpsk_ber_test::start_time
Referenced by ber_results(), final_results(), and reset().
bool SPUC::qpsk_ber_test::sync
Referenced by ber_results(), final_results(), found_sync(), reset(), synchronise(), and synchronize().
The documentation for this class was generated from the following files:
qpsk_ber_test.h
qpsk_ber_test.cpp