SPUC: SPUC::scic< Numeric > Class Template Reference
SPUC::scic< Numeric > Class Template Reference
SPUC templates | FIR filters
Implementation for sharped cascaded integrator comb filter.
#include <scic.h>
Public Member Functions
scic (char n=2, long r=4)
void num_stages (char n, long r)
Numeric decimate (Numeric in, long rate, signed char dump)
Protected Attributes
long max_rate
char stages
cic< Numeric > main
cic< Numeric > sub
delay< Numeric > dly
Detailed Description
template<class Numeric>
class SPUC::scic< Numeric >
Implementation for sharped cascaded integrator comb filter.
Registers are signed long and default number of stages is 2.
Author
Tony Kirke
Constructor & Destructor Documentation
template<class Numeric > SPUC::scic< Numeric >::scic (char n = 2, long r = 4) inline
References SPUC::delay< Numeric >::set_size().
Member Function Documentation
template<class Numeric > Numeric SPUC::scic< Numeric >::decimate (Numeric in, long rate, signed char dump) inline
References SPUC::delay< Numeric >::check(), SPUC::cic< Numeric >::decimate(), and SPUC::delay< Numeric >::input().
template<class Numeric > void SPUC::scic< Numeric >::num_stages (char n, long r) inline
References SPUC::cic< Numeric >::num_stages(), and SPUC::delay< Numeric >::set_size().
Member Data Documentation
template<class Numeric > delay<Numeric> SPUC::scic< Numeric >::dly protected
template<class Numeric > cic<Numeric> SPUC::scic< Numeric >::main protected
template<class Numeric > long SPUC::scic< Numeric >::max_rate protected
template<class Numeric > char SPUC::scic< Numeric >::stages protected
template<class Numeric > cic<Numeric> SPUC::scic< Numeric >::sub protected
The documentation for this class was generated from the following file:
scic.h