SPUC: SPUC::nested_iir_allpass_tmp< Numeric, Coeff > Class Template Reference
SPUC::nested_iir_allpass_tmp< Numeric, Coeff > Class Template Reference
#include <nested_iir_allpass_1.h>
Public Member Functions
nested_iir_allpass_2 (Coeff c0, Coeff c1, Coeff b0, Coeff b1, Coeff k)
void reset ()
reset
Numeric clock (Numeric input)
Shift inputs by one time sample and place new sample into array.
Protected Attributes
int Delay
The 2 1st order allpass filters.
allpass_2nd< Numeric, Coeff > A0
allpass_2nd< Numeric, Coeff > A1
allpass_1< Numeric, Coeff > D0
Numeric prev_input
Member Function Documentation
template<class Numeric , class Coeff = float_type> Numeric SPUC::nested_iir_allpass_tmp< Numeric, Coeff >::clock (Numeric input) inline
Shift inputs by one time sample and place new sample into array.
References SPUC::allpass_1< Numeric, Coeff >::clock(), and SPUC::allpass_2nd< Numeric, Coeff >::clock().
template<class Numeric , class Coeff = float_type> SPUC::nested_iir_allpass_tmp< Numeric, Coeff >::nested_iir_allpass_2 (Coeff c0, Coeff c1, Coeff b0, Coeff b1, Coeff k) inline
References SPUC::nested_iir_allpass_tmp< Numeric, Coeff >::reset().
template<class Numeric , class Coeff = float_type> void SPUC::nested_iir_allpass_tmp< Numeric, Coeff >::reset (void) inline
reset
References SPUC::allpass_2nd< Numeric, Coeff >::reset(), and SPUC::allpass_1< Numeric, Coeff >::reset().
Referenced by SPUC::nested_iir_allpass_tmp< Numeric, Coeff >::nested_iir_allpass_2().
Member Data Documentation
template<class Numeric , class Coeff = float_type> allpass_2nd<Numeric,Coeff> SPUC::nested_iir_allpass_tmp< Numeric, Coeff >::A0 protected
template<class Numeric , class Coeff = float_type> allpass_2nd<Numeric,Coeff> SPUC::nested_iir_allpass_tmp< Numeric, Coeff >::A1 protected
template<class Numeric , class Coeff = float_type> allpass_1<Numeric,Coeff> SPUC::nested_iir_allpass_tmp< Numeric, Coeff >::D0 protected
template<class Numeric , class Coeff = float_type> int SPUC::nested_iir_allpass_tmp< Numeric, Coeff >::Delay protected
The 2 1st order allpass filters.
template<class Numeric , class Coeff = float_type> Numeric SPUC::nested_iir_allpass_tmp< Numeric, Coeff >::prev_input protected
The documentation for this class was generated from the following file:
nested_iir_allpass_1.h