SPUC: SPUC::allpass_1< Numeric, Coeff > Class Template Reference
SPUC::allpass_1< Numeric, Coeff > Class Template Reference
SPUC double templates | Allpass filters
Template class for 1st order allpass filter with programmble gain and delay.
#include <allpass_1.h>
Public Member Functions
allpass_1 (Coeff Gain=0, long s=1, long b=0)
Constructor with gain and delay.
Coeff get_coefficient (void)
void reset ()
Reset.
void set_gain (Coeff Gain)
void init (Coeff &Gain, long s)
Initializes gain and delay.
Numeric clock (Numeric input)
Shift inputs by one time sample and place new sample into array.
Protected Types
typedef mixed_type< Numeric,
Coeff >::dtype sum_type
Protected Attributes
long size
number of unit sample delays
long round_bits
float_type gain
circ_buffer< Numeric > mult
circ_buffer< Numeric > sum
quantiser< Numeric > Q
Detailed Description
template<class Numeric, class Coeff = float_type>
class SPUC::allpass_1< Numeric, Coeff >
Template class for 1st order allpass filter with programmble gain and delay.
Template class for 1st-order Allpass filter. The filter is a "first-order" Allpass section of the form G(z,n) = (a*z^n + 1)/(z^n+a) The delay n can be specified
Author
Tony Kirke
Member Typedef Documentation
template<class Numeric, class Coeff = float_type> typedef mixed_type<Numeric,Coeff>::dtype SPUC::allpass_1< Numeric, Coeff >::sum_type protected
Constructor & Destructor Documentation
template<class Numeric, class Coeff = float_type> SPUC::allpass_1< Numeric, Coeff >::allpass_1 (Coeff Gain = 0, long s = 1, long b = 0) inline
Constructor with gain and delay.
Member Function Documentation
template<class Numeric, class Coeff = float_type> Numeric SPUC::allpass_1< Numeric, Coeff >::clock (Numeric input) inline
Shift inputs by one time sample and place new sample into array.
Referenced by SPUC::nested_iir_allpass_tmp< Numeric, Coeff >::clock(), SPUC::notch_comb< Numeric, Coeff >::clock(), SPUC::iir_delay_allpass1< Numeric, Coeff >::clock(), SPUC::nested_allpass_1< Numeric, Coeff >::clock(), SPUC::iir_allpass1_halfband< SPUC::complex< CNumeric > >::clock(), SPUC::iir_allpass1< Numeric, Coeff >::clock(), SPUC::shelf_allpass1< Numeric, Coeff >::clock(), SPUC::nested_shelf_allpass_2< Numeric, Coeff >::clock(), and SPUC::nested_iir_allpass_2< Numeric, Coeff >::clock().
template<class Numeric, class Coeff = float_type> Coeff SPUC::allpass_1< Numeric, Coeff >::get_coefficient (void) inline
Referenced by SPUC::nested_shelf_allpass_2< Numeric, Coeff >::print(), and SPUC::nested_iir_allpass_2< Numeric, Coeff >::print().
template<class Numeric, class Coeff = float_type> void SPUC::allpass_1< Numeric, Coeff >::init (Coeff & Gain, long s) inline
Initializes gain and delay.
Referenced by SPUC::nested_shelf_allpass_2< Numeric, Coeff >::change(), SPUC::nested_iir_allpass_2< Numeric, Coeff >::change(), SPUC::iir_allpass1< Numeric, Coeff >::iir_allpass1(), SPUC::nested_shelf_allpass_2< Numeric, Coeff >::init(), SPUC::nested_allpass_1< Numeric, Coeff >::init(), SPUC::nested_iir_allpass_2< Numeric, Coeff >::init(), SPUC::notch_comb< Numeric, Coeff >::set_coeffs(), and SPUC::shelf_allpass1< Numeric, Coeff >::set_coeffs().
template<class Numeric, class Coeff = float_type> void SPUC::allpass_1< Numeric, Coeff >::reset () inline
Reset.
Referenced by SPUC::nested_iir_allpass_tmp< Numeric, Coeff >::reset(), SPUC::notch_comb< Numeric, Coeff >::reset(), SPUC::nested_shelf_allpass_2< Numeric, Coeff >::reset(), SPUC::nested_allpass_1< Numeric, Coeff >::reset(), SPUC::iir_delay_allpass1< Numeric, Coeff >::reset(), SPUC::nested_iir_allpass_2< Numeric, Coeff >::reset(), SPUC::iir_allpass1_halfband< SPUC::complex< CNumeric > >::reset(), SPUC::iir_allpass1< Numeric, Coeff >::reset(), and SPUC::shelf_allpass1< Numeric, Coeff >::reset().
template<class Numeric, class Coeff = float_type> void SPUC::allpass_1< Numeric, Coeff >::set_gain (Coeff Gain) inline
Member Data Documentation
template<class Numeric, class Coeff = float_type> float_type SPUC::allpass_1< Numeric, Coeff >::gain protected
template<class Numeric, class Coeff = float_type> circ_buffer<Numeric> SPUC::allpass_1< Numeric, Coeff >::mult protected
template<class Numeric, class Coeff = float_type> quantiser<Numeric> SPUC::allpass_1< Numeric, Coeff >::Q protected
Referenced by SPUC::allpass_1< Numeric >::clock().
template<class Numeric, class Coeff = float_type> long SPUC::allpass_1< Numeric, Coeff >::round_bits protected
template<class Numeric, class Coeff = float_type> long SPUC::allpass_1< Numeric, Coeff >::size protected
number of unit sample delays
template<class Numeric, class Coeff = float_type> circ_buffer<Numeric> SPUC::allpass_1< Numeric, Coeff >::sum protected
The documentation for this class was generated from the following file:
allpass_1.h