SPUC: SPUC::fir_adapt< Numeric, Coeff > Class Template Reference
SPUC::fir_adapt< Numeric, Coeff > Class Template Reference
SPUC double templates restricted | Equalization classes And functions | FIR filters
template class fir_adapt Based on FIR class, created to support LMS adaptive filtering
#include <fir_adapt.h>
Public Types
typedef base_type< Numeric >::btype real_type
Public Types inherited from SPUC::fir< Numeric, Coeff >
typedef base_type< Numeric >::btype Numeric_base
typedef mixed_type< Numeric,
Coeff >::dtype sum_type
Public Member Functions
fir_adapt (void)
Constructor.
fir_adapt (long n, real_type gain)
Constructor with size.
void reset ()
Reset both history and coefficients!
void set_gain (real_type gain)
Set adaptation gain.
void update_lms (Numeric err)
Calculate updated taps using LMS algorithm.
void update_lms_sign_coeff (Numeric err)
Calculate updated taps using LMS algorithm and sign of input.
Public Member Functions inherited from SPUC::fir< Numeric, Coeff >
void settap (long i, Coeff tap)
Set tap weights.
void settaps (fir_coeff< Coeff > &c)
long number_of_taps ()
Coeff gettap (long i)
void reset ()
Reset.
Coeff coeff_sum ()
Get sum of coefficients.
void normalize_gain ()
void make_hpf ()
Numeric out ()
Get current output.
Numeric check (long i)
Clock in new sample & compute current output.
void set_round_bits (long x)
~fir (void)
fir (void)
Constructor.
fir (long n, long rb=0)
Constructor.
fir (fir_coeff< Coeff > C)
Constructor.
void set_size (long n)
Set size of Filter.
long get_size (void)
fir (const char *file)
Constructor that gets coefficients from file (requires fir.cpp)
Numeric clock (Numeric in)
Update filter by inputting 1 sample and returning convolved output sample.
Numeric update (Numeric in)
Numeric iir (Numeric in)
int read_taps (const char *file)
void print (void)
void settap (std::vector< Coeff > z)
Public Attributes
real_type u
Adaptation gain.
Public Attributes inherited from SPUC::fir< Numeric, Coeff >
std::vector< Coeff > coeff
std::vector< Numeric > z
Numeric output
quantiser< Numeric > Q
long num_taps
Detailed Description
template<class Numeric, class Coeff = double>
class SPUC::fir_adapt< Numeric, Coeff >
template class fir_adapt Based on FIR class, created to support LMS adaptive filtering
Author
Tony Kirke
Tony Kirke
Member Typedef Documentation
template<class Numeric, class Coeff = double> typedef base_type<Numeric>::btype SPUC::fir_adapt< Numeric, Coeff >::real_type
Constructor & Destructor Documentation
template<class Numeric, class Coeff = double> SPUC::fir_adapt< Numeric, Coeff >::fir_adapt (void) inline
Constructor.
template<class Numeric, class Coeff = double> SPUC::fir_adapt< Numeric, Coeff >::fir_adapt (long n, real_type gain) inline
Constructor with size.
Member Function Documentation
template<class Numeric, class Coeff = double> void SPUC::fir_adapt< Numeric, Coeff >::reset (void) inline
Reset both history and coefficients!
Referenced by SPUC::lms_dfe< Numeric, Coeff >::reset(), and SPUC::mle< Numeric >::reset().
template<class Numeric, class Coeff = double> void SPUC::fir_adapt< Numeric, Coeff >::set_gain (real_type gain) inline
Set adaptation gain.
Referenced by SPUC::lms_dfe< Numeric, Coeff >::lms_dfe(), and SPUC::lms_dfe< Numeric, Coeff >::set_gain().
template<class Numeric, class Coeff = double> void SPUC::fir_adapt< Numeric, Coeff >::update_lms (Numeric err) inline
Calculate updated taps using LMS algorithm.
Referenced by SPUC::mle< Numeric >::update_taps_lms(), and SPUC::lms_dfe< Numeric, Coeff >::update_taps_lms().
template<class Numeric, class Coeff = double> void SPUC::fir_adapt< Numeric, Coeff >::update_lms_sign_coeff (Numeric err) inline
Calculate updated taps using LMS algorithm and sign of input.
Member Data Documentation
template<class Numeric, class Coeff = double> real_type SPUC::fir_adapt< Numeric, Coeff >::u
Adaptation gain.
The documentation for this class was generated from the following file:
fir_adapt.h