SPUC: SPUC::iir_lpf1< Numeric, Coeff > Class Template Reference
SPUC::iir_lpf1< Numeric, Coeff > Class Template Reference
SPUC double templates | IIR filters
Template Class for 1st Order lowpass iir filter.
#include <iir_lpf1.h>
Public Member Functions
iir_lpf1 (Coeff A=0, long b=0)
void set_coeff (Coeff A)
void set_round_bits (long x)
iir_lpf1 (const char *file)
Constructor reading coefficient from a file.
void print ()
Print out coefficients.
Numeric clock (Numeric input)
Input new sample and calculate output.
void reset ()
Reset.
Protected Attributes
Coeff gain
Numeric out
Numeric previous_out
Numeric previous_in
quantiser< Numeric > Q
Detailed Description
template<class Numeric, class Coeff = float_type>
class SPUC::iir_lpf1< Numeric, Coeff >
Template Class for 1st Order lowpass iir filter.
The filter is the first order low pass digital filter given by
where a is real and |a| < 1 Note: Not normalized
Author
Tony Kirke
Constructor & Destructor Documentation
template<class Numeric, class Coeff = float_type> SPUC::iir_lpf1< Numeric, Coeff >::iir_lpf1 (Coeff A = 0, long b = 0) inline
template<class Numeric, class Coeff = float_type> SPUC::iir_lpf1< Numeric, Coeff >::iir_lpf1 (const char * file) inline
Constructor reading coefficient from a file.
References SPUC::iir_lpf1< Numeric, Coeff >::gain.
Member Function Documentation
template<class Numeric, class Coeff = float_type> Numeric SPUC::iir_lpf1< Numeric, Coeff >::clock (Numeric input) inline
Input new sample and calculate output.
References SPUC::iir_lpf1< Numeric, Coeff >::out, SPUC::iir_lpf1< Numeric, Coeff >::previous_in, and SPUC::iir_lpf1< Numeric, Coeff >::Q.
Referenced by SPUC::iir< Numeric, Coeff >::clock().
template<class Numeric, class Coeff = float_type> void SPUC::iir_lpf1< Numeric, Coeff >::print (void) inline
Print out coefficients.
Referenced by SPUC::iir< Numeric, Coeff >::print().
template<class Numeric, class Coeff = float_type> void SPUC::iir_lpf1< Numeric, Coeff >::reset (void) inline
Reset.
Referenced by SPUC::iir< Numeric, Coeff >::reset().
template<class Numeric, class Coeff = float_type> void SPUC::iir_lpf1< Numeric, Coeff >::set_coeff (Coeff A) inline
Referenced by SPUC::iir< Numeric, Coeff >::set_coeffs().
template<class Numeric, class Coeff = float_type> void SPUC::iir_lpf1< Numeric, Coeff >::set_round_bits (long x) inline
References SPUC::quantiser< Numeric >::set_bits().
Referenced by SPUC::iir< Numeric, Coeff >::set_round_bits().
Member Data Documentation
template<class Numeric, class Coeff = float_type> Coeff SPUC::iir_lpf1< Numeric, Coeff >::gain protected
Referenced by SPUC::iir_lpf< Numeric, Coeff >::clock(), SPUC::iir_lpf< Numeric, Coeff >::get_a0(), SPUC::iir_lpf< Numeric, Coeff >::iir_lpf(), and SPUC::iir_lpf1< Numeric, Coeff >::iir_lpf1().
template<class Numeric, class Coeff = float_type> Numeric SPUC::iir_lpf1< Numeric, Coeff >::out protected
Referenced by SPUC::iir_lpf< Numeric, Coeff >::clock(), and SPUC::iir_lpf1< Numeric, Coeff >::clock().
template<class Numeric, class Coeff = float_type> Numeric SPUC::iir_lpf1< Numeric, Coeff >::previous_in protected
Referenced by SPUC::iir_lpf< Numeric, Coeff >::clock(), and SPUC::iir_lpf1< Numeric, Coeff >::clock().
template<class Numeric, class Coeff = float_type> Numeric SPUC::iir_lpf1< Numeric, Coeff >::previous_out protected
Referenced by SPUC::iir_lpf< Numeric, Coeff >::clock().
template<class Numeric, class Coeff = float_type> quantiser<Numeric> SPUC::iir_lpf1< Numeric, Coeff >::Q protected
Referenced by SPUC::iir_lpf< Numeric, Coeff >::clock(), and SPUC::iir_lpf1< Numeric, Coeff >::clock().
The documentation for this class was generated from the following file:
iir_lpf1.h