SPUC: SPUC::remez_fir Class Reference
SPUC::remez_fir Class Reference
SPUC non-template classes | FIR filters
template Remez_fir class
#include <remez_fir.h>
Public Member Functions
remez_fir ()
Static Public Member Functions
static bool remez (std::vector< float_type > &filt, int n, int numband, std::vector< float_type > &bands, const std::vector< float_type > &des, const std::vector< float_type > &weight, int type)
Detailed Description
template Remez_fir class
Calculates the optimal (in the Chebyshev/minimax sense) FIR filter impulse response given a set of band edges, the desired reponse on those bands, and the weight given to the error in those bands.
Inputs:
int numtaps - Number of filter coefficients
int numband - Number of bands in filter specification
float_type[] bands - User-specified band edges [2 * numband]
float_type[] des - User-specified band responses [numband]
float_type[] weight - User-specified error weights [numband]
int type - Type of filter
Output:
float_type[] h - Impulse response of final filter [numtaps]
Author
Tony Kirke
Constructor & Destructor Documentation
SPUC::remez_fir::remez_fir () inline
Member Function Documentation
bool SPUC::remez_fir::remez (std::vector< float_type > & filt, int n, int numband, std::vector< float_type > & bands, const std::vector< float_type > & des, const std::vector< float_type > & weight, int type) static
References BANDPASS, SPUC::cos(), DIFFERENTIATOR, GRIDDENSITY, SPUC::inv_dft(), SPUC::inv_dft_symmetric(), MAXITERATIONS, NEGATIVE, PI, POSITIVE, and TWOPI.
Referenced by SPUC::create_remez_fir(), SPUC::create_remez_lpfir(), and SPUC::remez_function().
The documentation for this class was generated from the following files:
remez_fir.h
remez_fir.cpp