SPUC: SPUC::notch_iir< Numeric, Coeff > Class Template Reference
SPUC::notch_iir< Numeric, Coeff > Class Template Reference
SPUC double templates | IIR filters
IIR notch filter based on 2nd order biquad.
#include <notch_iir.h>
Public Member Functions
notch_iir (Coeff B, Coeff Y)
void set_coeffs (Coeff B, Coeff Y)
void set_freq (Coeff B)
void set_depth (Coeff Y)
Numeric clock (Numeric x)
Public Attributes
iir_2nd< Numeric, Coeff > filter
Coeff gain
Detailed Description
template<class Numeric, class Coeff = float_type>
class SPUC::notch_iir< Numeric, Coeff >
IIR notch filter based on 2nd order biquad.
Author
Tony Kirke
Constructor & Destructor Documentation
template<class Numeric, class Coeff = float_type> SPUC::notch_iir< Numeric, Coeff >::notch_iir (Coeff B, Coeff Y) inline
Member Function Documentation
template<class Numeric, class Coeff = float_type> Numeric SPUC::notch_iir< Numeric, Coeff >::clock (Numeric x) inline
References SPUC::iir_2nd< Numeric, Coeff >::clock().
Referenced by SPUC::notch_example().
template<class Numeric, class Coeff = float_type> void SPUC::notch_iir< Numeric, Coeff >::set_coeffs (Coeff B, Coeff Y) inline
References SPUC::iir_2nd< Numeric, Coeff >::set_coeffs().
template<class Numeric, class Coeff = float_type> void SPUC::notch_iir< Numeric, Coeff >::set_depth (Coeff Y) inline
References SPUC::iir_2nd< Numeric, Coeff >::get_b2(), and SPUC::iir_2nd< Numeric, Coeff >::set_coeffs().
template<class Numeric, class Coeff = float_type> void SPUC::notch_iir< Numeric, Coeff >::set_freq (Coeff B) inline
References SPUC::iir_2nd< Numeric, Coeff >::get_a1(), and SPUC::iir_2nd< Numeric, Coeff >::set_coeffs().
Member Data Documentation
template<class Numeric, class Coeff = float_type> iir_2nd<Numeric, Coeff> SPUC::notch_iir< Numeric, Coeff >::filter
template<class Numeric, class Coeff = float_type> Coeff SPUC::notch_iir< Numeric, Coeff >::gain
The documentation for this class was generated from the following file:
notch_iir.h