SPUC: SPUC::fading_channel Class Reference
SPUC::fading_channel Class Reference
SPUC non-template classes | Simulation classes And functions | Communication classes And functions
#include <fading_channel.h>
Public Member Functions
fading_channel (long paths=1, float_type norm_delay_spread=1)
void setup (float_type norm_delay_spread)
void generate_channel ()
complex< float_type > update (const complex< float_type > s)
Public Attributes
fir< complex< float_type >
, complex< float_type > > exp_decay
long taps
float_type delay_spread
noise tap_gain
Detailed Description
FIR Channel Model. Exponential decay delay line channel model Mean channel power is normalized Profiles are generated using gaussian pdf
Author
Tony Kirke, Copyright(c) 2001
Tony Kirke
Constructor & Destructor Documentation
SPUC::fading_channel::fading_channel (long paths = 1, float_type norm_delay_spread = 1) inline
References delay_spread, exp_decay, generate_channel(), and taps.
Member Function Documentation
void SPUC::fading_channel::generate_channel ()
References SPUC::noise::Cgauss(), delay_spread, SPUC::exp(), exp_decay, SPUC::sqrt(), tap_gain, and taps.
Referenced by fading_channel(), and setup().
void SPUC::fading_channel::setup (float_type norm_delay_spread)
References delay_spread, exp_decay, generate_channel(), and taps.
complex< float_type > SPUC::fading_channel::update (const complex< float_type > s)
References exp_decay, and taps.
Referenced by SPUC::baud_eq_env< Numeric >::step().
Member Data Documentation
float_type SPUC::fading_channel::delay_spread
Referenced by fading_channel(), generate_channel(), and setup().
fir<complex<float_type>,complex<float_type> > SPUC::fading_channel::exp_decay
Referenced by fading_channel(), generate_channel(), SPUC::baud_eq_env< Numeric >::loop_init(), main(), setup(), and update().
noise SPUC::fading_channel::tap_gain
Referenced by generate_channel().
long SPUC::fading_channel::taps
Referenced by fading_channel(), generate_channel(), setup(), and update().
The documentation for this class was generated from the following files:
fading_channel.h
fading_channel.cpp