SPUC: SPUC::rls< Numeric > Class Template Reference
SPUC::rls< Numeric > Class Template Reference
SPUC templates | Equalization classes And functions | Communication classes And functions
Recursive Least Squares Algorithm.
#include <rls.h>
Public Member Functions
~rls ()
Destructor.
rls (const int n, float_type alpha)
Constructor.
Numeric update (Numeric y)
Process input sample.
void adapt (Numeric y)
Adapt filter.
Detailed Description
template<class Numeric>
class SPUC::rls< Numeric >
Recursive Least Squares Algorithm.
Author
Tony Kirke
Tony Kirke
Constructor & Destructor Documentation
template<class Numeric > SPUC::rls< Numeric >::~rls () inline
Destructor.
template<class Numeric > SPUC::rls< Numeric >::rls (const int n, float_type alpha) inline
Constructor.
Member Function Documentation
template<class Numeric > void SPUC::rls< Numeric >::adapt (Numeric y) inline
Adapt filter.
References SPUC::conj().
template<class Numeric > Numeric SPUC::rls< Numeric >::update (Numeric y) inline
Process input sample.
References SPUC::get_input(), SPUC::get_taps(), SPUC::to_vector(), and SPUC::fir< Numeric, Coeff >::update().
The documentation for this class was generated from the following file:
rls.h