SPUC: SPUC::cordic< Numeric > Class Template Reference
SPUC::cordic< Numeric > Class Template Reference
SPUC templates with real parameters | Miscellaneous DSP
Cordic rotator.
#include <cordic.h>
Public Member Functions
cordic (int n=7)
initializes tables and constants for the CORDIC algorithm
Numeric vector_mag (complex< Numeric > in)
Returns magnitude through CORDIC vectoring.
float_type vector_arg (complex< Numeric > in)
Returns arg through CORDIC vectoring.
complex< Numeric > rotate (complex< Numeric > in, float_type angle)
Public Attributes
std::vector< float_type > arctan_lut
std::vector< complex< Numeric > > stage
long stages
float_type vector_angle
Protected Member Functions
Numeric cordic_vector (complex< Numeric > in)
Cordic vectoring calculates arg and magnitude.
Detailed Description
template<class Numeric>
class SPUC::cordic< Numeric >
Cordic rotator.
Performs CORDIC rotations To rotate a vector through an angle of theta, we calculate:
x' = x cos(theta) - y sin(theta) y' = x sin(theta) + y cos(theta) Can be easily modified for hyperbolic and other functions
Author
Tony Kirke
Constructor & Destructor Documentation
template<class Numeric> SPUC::cordic< Numeric >::cordic (int n = 7) inline
initializes tables and constants for the CORDIC algorithm
Member Function Documentation
template<class Numeric> Numeric SPUC::cordic< Numeric >::cordic_vector (complex< Numeric > in) inline protected
Cordic vectoring calculates arg and magnitude.
Referenced by SPUC::cordic< CNumeric >::vector_arg(), and SPUC::cordic< CNumeric >::vector_mag().
template<class Numeric> complex<Numeric> SPUC::cordic< Numeric >::rotate (complex< Numeric > in, float_type angle) inline
Referenced by SPUC::qpsk_variable< Numeric >::clock().
template<class Numeric> float_type SPUC::cordic< Numeric >::vector_arg (complex< Numeric > in) inline
Returns arg through CORDIC vectoring.
template<class Numeric> Numeric SPUC::cordic< Numeric >::vector_mag (complex< Numeric > in) inline
Returns magnitude through CORDIC vectoring.
Member Data Documentation
template<class Numeric> std::vector<float_type> SPUC::cordic< Numeric >::arctan_lut
template<class Numeric> std::vector<complex<Numeric> > SPUC::cordic< Numeric >::stage
template<class Numeric> long SPUC::cordic< Numeric >::stages
Referenced by SPUC::cordic< CNumeric >::cordic(), SPUC::cordic< CNumeric >::cordic_vector(), and SPUC::cordic< CNumeric >::rotate().
template<class Numeric> float_type SPUC::cordic< Numeric >::vector_angle
The documentation for this class was generated from the following file:
cordic.h