SPUC: SPUC::noise Class Reference
SPUC::noise Class Reference
SPUC non-template classes | Miscellaneous DSP
Gaussian noise routine.
#include <noise.h>
Public Member Functions
noise (float_type i=1349555.0)
Random seed.
float_type gauss ()
Gaussian noise.
complex< float_type > Cgauss (void)
complex gaussian noise
float_type uni ()
Uniform noise.
float_type uniform ()
Uniform noise.
void set_seed (unsigned i=1349555)
Change seed.
Protected Attributes
char s
float_type x
Switch.
long idum
Saved calculated value.
Detailed Description
Gaussian noise routine.
Can create (float_type) gaussian white noise,
complex<float_type> gaussian white noise
or (float_type) uniform noise
Requires complex template class
Author
Tony Kirke
Constructor & Destructor Documentation
SPUC::noise::noise (float_type i = 1349555.0)
Random seed.
Constructor
Member Function Documentation
complex< float_type > SPUC::noise::Cgauss (void)
complex gaussian noise
References SPUC::sqrt(), and uniform().
Referenced by SPUC::fading_channel::generate_channel(), SPUC::baud_eq_env< Numeric >::step(), SPUC::sim_qpsk< Numeric >::tx_step(), SPUC::sim_qpsk_variable< Numeric >::tx_step(), and SPUC::sim_qam< Numeric >::tx_step().
float_type SPUC::noise::gauss ()
Gaussian noise.
References s, SPUC::sqrt(), uni(), and x.
void SPUC::noise::set_seed (unsigned i = 1349555) inline
Change seed.
Change seed
Referenced by main().
float_type SPUC::noise::uni (void)
Uniform noise.
References IA, IC, idum, and M.
Referenced by gauss(), and main().
float_type SPUC::noise::uniform (void)
Uniform noise.
References idum, LA, LAM, LM, LQ, and LR.
Referenced by Cgauss().
Member Data Documentation
long SPUC::noise::idum protected
Saved calculated value.
Referenced by uni(), and uniform().
char SPUC::noise::s protected
Referenced by gauss().
float_type SPUC::noise::x protected
Switch.
Referenced by gauss().
The documentation for this class was generated from the following files:
noise.h
noise.cpp