SPUC: SPUC::fir_decim< Numeric, Coeff > Class Template Reference
SPUC::fir_decim< Numeric, Coeff > Class Template Reference
SPUC double templates | FIR filters
template class for fir decimation based on FIR class
#include <fir_decim.h>
Public Member Functions
fir_decim (void)
Constructor.
fir_decim (long n)
fir_decim (const char *file)
void input (Numeric in)
Numeric decim (void)
Public Member Functions inherited from SPUC::fir< Numeric, Coeff >
void settap (long i, Coeff tap)
Set tap weights.
void settaps (fir_coeff< Coeff > &c)
long number_of_taps ()
Coeff gettap (long i)
void reset ()
Reset.
Coeff coeff_sum ()
Get sum of coefficients.
void normalize_gain ()
void make_hpf ()
Numeric out ()
Get current output.
Numeric check (long i)
Clock in new sample & compute current output.
void set_round_bits (long x)
~fir (void)
fir (void)
Constructor.
fir (long n, long rb=0)
Constructor.
fir (fir_coeff< Coeff > C)
Constructor.
void set_size (long n)
Set size of Filter.
long get_size (void)
fir (const char *file)
Constructor that gets coefficients from file (requires fir.cpp)
Numeric clock (Numeric in)
Update filter by inputting 1 sample and returning convolved output sample.
Numeric update (Numeric in)
Numeric iir (Numeric in)
int read_taps (const char *file)
void print (void)
void settap (std::vector< Coeff > z)
Additional Inherited Members
Public Types inherited from SPUC::fir< Numeric, Coeff >
typedef base_type< Numeric >::btype Numeric_base
typedef mixed_type< Numeric,
Coeff >::dtype sum_type
Public Attributes inherited from SPUC::fir< Numeric, Coeff >
std::vector< Coeff > coeff
std::vector< Numeric > z
Numeric output
quantiser< Numeric > Q
long num_taps
Detailed Description
template<class Numeric, class Coeff = float_type>
class SPUC::fir_decim< Numeric, Coeff >
template class for fir decimation based on FIR class
created to support polyphase FIR decimation
Author
Tony Kirke
Constructor & Destructor Documentation
template<class Numeric, class Coeff = float_type> SPUC::fir_decim< Numeric, Coeff >::fir_decim (void) inline
Constructor.
template<class Numeric, class Coeff = float_type> SPUC::fir_decim< Numeric, Coeff >::fir_decim (long n) inline
template<class Numeric, class Coeff = float_type> SPUC::fir_decim< Numeric, Coeff >::fir_decim (const char * file) inline
References SPUC::fir< Numeric, Coeff >::read_taps().
Member Function Documentation
template<class Numeric, class Coeff = float_type> Numeric SPUC::fir_decim< Numeric, Coeff >::decim (void) inline
Phase increments when in automatic mode Otherwise phase does not change
References SPUC::fir< Numeric, Coeff >::coeff, SPUC::fir< Numeric, Coeff >::num_taps, SPUC::fir< Numeric, Coeff >::output, SPUC::fir< Numeric, Coeff >::Q, and SPUC::fir< Numeric, Coeff >::z.
Referenced by SPUC::notch_example().
template<class Numeric, class Coeff = float_type> void SPUC::fir_decim< Numeric, Coeff >::input (Numeric in) inline
References SPUC::fir< Numeric, Coeff >::num_taps, and SPUC::fir< Numeric, Coeff >::z.
Referenced by SPUC::notch_example().
The documentation for this class was generated from the following file:
fir_decim.h