SPUC: SPUC::delay< Numeric > Class Template Reference
SPUC::delay< Numeric > Class Template Reference
SPUC templates | Miscellaneous DSP
Template class for Delay line.
#include <delay.h>
Public Member Functions
delay (long n=0)
Constructor.
delay & operator= (const delay &rhs)
Assignment.
~delay (void)
Destructor.
void reset (void)
Numeric check (long i)
Get delay at tap i.
Numeric checkback (long i)
Look back in delay line by i samples.
Numeric last ()
Get last tap.
void set_size (long n=2)
Set size of delay.
Numeric input (Numeric in)
Clock in new input sample.
Numeric update (Numeric in)
Clock in new sample and get output from delay line.
Public Attributes
long num_taps
Protected Attributes
std::vector< Numeric > z
Detailed Description
template<class Numeric>
class SPUC::delay< Numeric >
Template class for Delay line.
Template class for a Delay line (primitive used in other classes) Allows user to check at various points in delay line, but default use is a pure delay.
Author
Tony Kirke
Constructor & Destructor Documentation
template<class Numeric> SPUC::delay< Numeric >::delay (long n = 0) inline
Constructor.
template<class Numeric> SPUC::delay< Numeric >::~delay (void) inline
Destructor.
Member Function Documentation
template<class Numeric> Numeric SPUC::delay< Numeric >::check (long i) inline
Get delay at tap i.
Referenced by SPUC::iir_delay_allpass1< Numeric, Coeff >::clock(), and SPUC::scic< Numeric >::decimate().
template<class Numeric> Numeric SPUC::delay< Numeric >::checkback (long i) inline
Look back in delay line by i samples.
Referenced by SPUC::qpsk< Numeric >::clock().
template<class Numeric> Numeric SPUC::delay< Numeric >::input (Numeric in) inline
Clock in new input sample.
Referenced by SPUC::iir_delay_allpass1< Numeric, Coeff >::clock(), SPUC::iir_comb< Numeric, Coeff >::clock(), SPUC::qpsk< Numeric >::clock(), SPUC::scic< Numeric >::decimate(), SPUC::running_sum< Numeric >::update(), SPUC::running_average< Numeric >::update(), and SPUC::delay< T >::update().
template<class Numeric> Numeric SPUC::delay< Numeric >::last () inline
Get last tap.
Referenced by SPUC::running_sum< Numeric >::update(), and SPUC::running_average< Numeric >::update().
template<class Numeric> delay& SPUC::delay< Numeric >::operator= (const delay< Numeric > & rhs) inline
Assignment.
template<class Numeric> void SPUC::delay< Numeric >::reset (void) inline
Referenced by SPUC::iir_delay_allpass1< Numeric, Coeff >::reset(), SPUC::running_sum< Numeric >::reset(), SPUC::iir_comb< Numeric, Coeff >::reset(), SPUC::running_average< Numeric >::reset(), SPUC::running_average< Numeric >::running_average(), and SPUC::running_sum< Numeric >::running_sum().
template<class Numeric> void SPUC::delay< Numeric >::set_size (long n = 2) inline
Set size of delay.
Referenced by SPUC::iir_comb< Numeric, Coeff >::iir_comb(), SPUC::iir_delay_allpass1< Numeric, Coeff >::iir_delay_allpass1(), SPUC::iir_comb< Numeric, Coeff >::init(), main(), SPUC::scic< Numeric >::num_stages(), SPUC::running_average< Numeric >::running_average(), SPUC::running_sum< Numeric >::running_sum(), SPUC::scic< Numeric >::scic(), SPUC::iir_delay_allpass1< Numeric, Coeff >::set_delay(), SPUC::convolutional_interleaver< T >::set_size(), SPUC::running_sum< Numeric >::set_size(), and SPUC::running_average< Numeric >::set_size().
template<class Numeric> Numeric SPUC::delay< Numeric >::update (Numeric in) inline
Clock in new sample and get output from delay line.
Referenced by main().
Member Data Documentation
template<class Numeric> long SPUC::delay< Numeric >::num_taps
Referenced by SPUC::delay< T >::delay(), SPUC::delay< T >::operator=(), SPUC::delay< T >::reset(), and SPUC::delay< T >::set_size().
template<class Numeric> std::vector<Numeric> SPUC::delay< Numeric >::z protected
Referenced by SPUC::delay< T >::operator=().
The documentation for this class was generated from the following file:
delay.h