SPUC: SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ > Class Template Reference
SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ > Class Template Reference
A fast & lightweight fixed-point class.
#include <spuc_ufixed.h>
Public Types
typedef spuc_uint< TOTAL_BITS_ > val_type
typedef uint64_t max_val_type
Public Member Functions
spuc_ufixed ()
constructors
spuc_ufixed (double a)
template<int W>
spuc_ufixed (const spuc_int< W > &a)
built-in types
template<int W>
spuc_ufixed (const spuc_uint< W > &a)
spuc_ufixed (int8_t a)
spuc_ufixed (int16_t a)
spuc_ufixed (int32_t a)
spuc_ufixed (int64_t a)
spuc_ufixed (uint8_t a)
spuc_ufixed (uint16_t a)
spuc_ufixed (uint32_t a)
spuc_ufixed (uint64_t a)
spuc_ufixed (const spuc_ufixed &a)
From exact same type - just copy val.
template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1>
spuc_ufixed (const spuc_ufixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > &a)
from another spuc_ufixed<>
template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1>
spuc_ufixed (const spuc_fixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > &a)
from spuc_fixed<>
val_type getVal () const
should not be needed later
void from_double (double x)
Conversions.
template<typename T_ >
void from_int (T_ x)
Conversions.
template<typename T_ >
void from_uint (T_ x)
double to_double (void) const
int64_t to_int (void) const
operator double () const
Allow conversion to double for simulation.
operator val_type () const
Conversion to int type for comparing to ints.
bool operator! () const
conversion to bool
spuc_ufixed & operator++ ()
spuc_ufixed operator++ (int)
spuc_ufixed & operator-- ()
spuc_ufixed operator-- (int)
spuc_ufixed & operator= (const spuc_ufixed &a)
assignment operator, just copy the only member variable - no checks!
template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1>
spuc_ufixed< TOTAL_BITS_,
INT_BITS_, SPUC_Q_MODE_,
SPUC_O_MODE_ > & operator= (const spuc_ufixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > &a)
template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1>
spuc_ufixed< TOTAL_BITS_,
INT_BITS_, SPUC_Q_MODE_,
SPUC_O_MODE_ > & operator= (const spuc_fixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > &a)
template<int W_1>
spuc_ufixed< TOTAL_BITS_,
INT_BITS_, SPUC_Q_MODE_,
SPUC_O_MODE_ > & operator= (const spuc_int< W_1 > &a)
assignment operator from spuc_int
template<int W_1>
spuc_ufixed< TOTAL_BITS_,
INT_BITS_, SPUC_Q_MODE_,
SPUC_O_MODE_ > & operator= (const spuc_uint< W_1 > &a)
assignment operator from spuc_int
spuc_fixed< TOTAL_BITS_+1,
INT_BITS_+1 > operator- () const
sign operator - return spuc_fixed
spuc_ufixed operator~ () const
bit flip
spuc_ufixed & operator= (const int8_t &a)
spuc_ufixed & operator= (const int16_t &a)
spuc_ufixed & operator= (const int32_t &a)
spuc_ufixed & operator= (const int64_t &a)
spuc_ufixed & operator= (const uint8_t &a)
spuc_ufixed & operator= (const uint16_t &a)
spuc_ufixed & operator= (const uint32_t &a)
spuc_ufixed & operator= (const uint64_t &a)
spuc_ufixed & operator= (const double &a)
template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1>
spuc_ufixed & operator+= (const spuc_ufixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > &a)
template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1>
spuc_ufixed & operator+= (const spuc_fixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > &a)
template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1>
spuc_ufixed & operator-= (const spuc_ufixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > &a)
template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1>
spuc_ufixed & operator-= (const spuc_fixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > &a)
template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1>
spuc_ufixed & operator*= (const spuc_ufixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > &b)
template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1>
spuc_ufixed & operator*= (const spuc_fixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > &b)
template<int TOTAL_BITS_1, int INT_BITS_1>
spuc_ufixed & operator/= (const spuc_ufixed< TOTAL_BITS_1, INT_BITS_1 > &b)
Divide uses conversion back and forth to double for intermediate values.
spuc_ufixed & operator+= (const double &a)
"+= and -=" from different built-in types
spuc_ufixed & operator-= (const double &a)
spuc_ufixed & operator+= (const int8_t &a)
spuc_ufixed & operator-= (const int8_t &a)
spuc_ufixed & operator+= (const int16_t &a)
spuc_ufixed & operator-= (const int16_t &a)
spuc_ufixed & operator+= (const int32_t &a)
spuc_ufixed & operator-= (const int32_t &a)
spuc_ufixed & operator+= (const int64_t &a)
spuc_ufixed & operator-= (const int64_t &a)
spuc_ufixed & operator+= (const uint8_t &a)
spuc_ufixed & operator-= (const uint8_t &a)
spuc_ufixed & operator+= (const uint16_t &a)
spuc_ufixed & operator-= (const uint16_t &a)
spuc_ufixed & operator+= (const uint32_t &a)
spuc_ufixed & operator-= (const uint32_t &a)
spuc_ufixed & operator+= (const uint64_t &a)
spuc_ufixed & operator-= (const uint64_t &a)
spuc_ufixed & operator*= (const int8_t &a)
spuc_ufixed & operator/= (const int8_t &a)
spuc_ufixed & operator*= (const int16_t &a)
spuc_ufixed & operator/= (const int16_t &a)
spuc_ufixed & operator*= (const int32_t &a)
spuc_ufixed & operator/= (const int32_t &a)
spuc_ufixed & operator*= (const int64_t &a)
spuc_ufixed & operator/= (const int64_t &a)
spuc_ufixed & operator*= (const uint8_t &a)
spuc_ufixed & operator/= (const uint8_t &a)
spuc_ufixed & operator*= (const uint16_t &a)
spuc_ufixed & operator/= (const uint16_t &a)
spuc_ufixed & operator*= (const uint32_t &a)
spuc_ufixed & operator/= (const uint32_t &a)
spuc_ufixed & operator*= (const uint64_t &a)
spuc_ufixed & operator/= (const uint64_t &a)
spuc_ufixed & operator*= (const double &a)
spuc_ufixed & operator/= (const double &a)
template<int W>
spuc_ufixed & operator<<= (spuc_int< W > shift)
Left shifts + assign.
template<int W>
spuc_ufixed & operator<<= (spuc_uint< W > shift)
template<int W>
spuc_ufixed & operator>>= (spuc_int< W > shift)
Right shifts + assign.
template<int W>
spuc_ufixed & operator>>= (spuc_uint< W > shift)
spuc_ufixed & operator>>= (const int8_t &shift)
spuc_ufixed & operator>>= (const int16_t &shift)
spuc_ufixed & operator>>= (const int32_t &shift)
spuc_ufixed & operator>>= (const int64_t &shift)
spuc_ufixed & operator>>= (const uint8_t &shift)
spuc_ufixed & operator>>= (const uint16_t &shift)
spuc_ufixed & operator>>= (const uint32_t &shift)
spuc_ufixed & operator>>= (const uint64_t &shift)
spuc_ufixed & operator<<= (int8_t shift)
spuc_ufixed & operator<<= (int16_t shift)
spuc_ufixed & operator<<= (int32_t shift)
spuc_ufixed & operator<<= (int64_t shift)
spuc_ufixed & operator<<= (uint8_t shift)
spuc_ufixed & operator<<= (uint16_t shift)
spuc_ufixed & operator<<= (uint32_t shift)
spuc_ufixed & operator<<= (uint64_t shift)
bool operator== (const spuc_ufixed &a) const
boolean operators for same type
bool operator!= (const spuc_ufixed &a) const
bool operator< (const spuc_ufixed &a) const
bool operator> (const spuc_ufixed &a) const
bool operator<= (const spuc_ufixed &a) const
bool operator>= (const spuc_ufixed &a) const
val_type getInt () const
val_type getFrac () const
void init_max ()
void init_min ()
void setVal (int a)
void multm1 ()
void flip ()
bool is_neg () const
bool is_zero () const
Check for zero.
spuc_q_mode q_mode () const
Return Quantization mode.
spuc_o_mode o_mode () const
Return Overflow mode.
std::string type_params ()
void print (std::ostream &os=::std::cout) const
Public Attributes
val_type val
Static Public Attributes
static const int TOTAL_BITS = TOTAL_BITS_
static const int INTEGER_BITS = INT_BITS_
Detailed Description
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP>
class SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >
A fast & lightweight fixed-point class.
Member Typedef Documentation
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> typedef uint64_t SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::max_val_type
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> typedef spuc_uint<TOTAL_BITS_> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::val_type
Constructor & Destructor Documentation
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::spuc_ufixed () inline
constructors
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::spuc_ufixed (double a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int W> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::spuc_ufixed (const spuc_int< W > & a) inline
built-in types
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int W> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::spuc_ufixed (const spuc_uint< W > & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::spuc_ufixed (int8_t a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::spuc_ufixed (int16_t a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::spuc_ufixed (int32_t a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::spuc_ufixed (int64_t a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::spuc_ufixed (uint8_t a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::spuc_ufixed (uint16_t a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::spuc_ufixed (uint32_t a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::spuc_ufixed (uint64_t a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::spuc_ufixed (const spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ > & a) inline
From exact same type - just copy val.
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::spuc_ufixed (const spuc_ufixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > & a) inline
from another spuc_ufixed<>
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::spuc_ufixed (const spuc_fixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > & a) inline
from spuc_fixed<>
Member Function Documentation
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> void SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::flip () inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> void SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::from_double (double x) inline
Conversions.
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<typename T_ > void SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::from_int (T_ x) inline
Conversions.
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<typename T_ > void SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::from_uint (T_ x) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> val_type SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::getFrac () const inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> val_type SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::getInt () const inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> val_type SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::getVal () const inline
should not be needed later
Referenced by SPUC::operator*(), and SPUC::operator/().
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> void SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::init_max () inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> void SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::init_min () inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> bool SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::is_neg () const inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> bool SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::is_zero () const inline
Check for zero.
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> void SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::multm1 () inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_o_mode SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::o_mode () const inline
Return Overflow mode.
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator double () const inline
Allow conversion to double for simulation.
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator val_type () const inline
Conversion to int type for comparing to ints.
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> bool SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator! () const inline
conversion to bool
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> bool SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator!= (const spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ > & a) const inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator*= (const spuc_ufixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > & b) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator*= (const spuc_fixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > & b) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator*= (const int8_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator*= (const int16_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator*= (const int32_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator*= (const int64_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator*= (const uint8_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator*= (const uint16_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator*= (const uint32_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator*= (const uint64_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator*= (const double & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator++ () inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator++ (int) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator+= (const spuc_ufixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator+= (const spuc_fixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator+= (const double & a) inline
"+= and -=" from different built-in types
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator+= (const int8_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator+= (const int16_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator+= (const int32_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator+= (const int64_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator+= (const uint8_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator+= (const uint16_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator+= (const uint32_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator+= (const uint64_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_fixed<TOTAL_BITS_ + 1, INT_BITS_ + 1> SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator- () const inline
sign operator - return spuc_fixed
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator-- () inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator-- (int) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator-= (const spuc_ufixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator-= (const spuc_fixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator-= (const double & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator-= (const int8_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator-= (const int16_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator-= (const int32_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator-= (const int64_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator-= (const uint8_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator-= (const uint16_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator-= (const uint32_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator-= (const uint64_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int TOTAL_BITS_1, int INT_BITS_1> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator/= (const spuc_ufixed< TOTAL_BITS_1, INT_BITS_1 > & b) inline
Divide uses conversion back and forth to double for intermediate values.
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator/= (const int8_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator/= (const int16_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator/= (const int32_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator/= (const int64_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator/= (const uint8_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator/= (const uint16_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator/= (const uint32_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator/= (const uint64_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator/= (const double & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> bool SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator< (const spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ > & a) const inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int W> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator<<= (spuc_int< W > shift) inline
Left shifts + assign.
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int W> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator<<= (spuc_uint< W > shift) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator<<= (int8_t shift) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator<<= (int16_t shift) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator<<= (int32_t shift) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator<<= (int64_t shift) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator<<= (uint8_t shift) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator<<= (uint16_t shift) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator<<= (uint32_t shift) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator<<= (uint64_t shift) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> bool SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator<= (const spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ > & a) const inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator= (const spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ > & a) inline
assignment operator, just copy the only member variable - no checks!
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1> spuc_ufixed<TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_>& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator= (const spuc_ufixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > & a) inline
assignment operator from another size, use copy constructor, then copy val;
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int TOTAL_BITS_1, int INT_BITS_1, spuc_q_mode SPUC_Q_MODE_1, spuc_o_mode SPUC_O_MODE_1> spuc_ufixed<TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_>& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator= (const spuc_fixed< TOTAL_BITS_1, INT_BITS_1, SPUC_Q_MODE_1, SPUC_O_MODE_1 > & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int W_1> spuc_ufixed<TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_>& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator= (const spuc_int< W_1 > & a) inline
assignment operator from spuc_int
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int W_1> spuc_ufixed<TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_>& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator= (const spuc_uint< W_1 > & a) inline
assignment operator from spuc_int
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator= (const int8_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator= (const int16_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator= (const int32_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator= (const int64_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator= (const uint8_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator= (const uint16_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator= (const uint32_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator= (const uint64_t & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator= (const double & a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> bool SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator== (const spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ > & a) const inline
boolean operators for same type
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> bool SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator> (const spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ > & a) const inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> bool SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator>= (const spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ > & a) const inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int W> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator>>= (spuc_int< W > shift) inline
Right shifts + assign.
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> template<int W> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator>>= (spuc_uint< W > shift) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator>>= (const int8_t & shift) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator>>= (const int16_t & shift) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator>>= (const int32_t & shift) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator>>= (const int64_t & shift) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator>>= (const uint8_t & shift) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator>>= (const uint16_t & shift) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator>>= (const uint32_t & shift) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed& SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator>>= (const uint64_t & shift) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_ufixed SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::operator~ (void) const inline
bit flip
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> void SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::print (std::ostream & os = ::std::cout) const inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> spuc_q_mode SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::q_mode () const inline
Return Quantization mode.
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> void SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::setVal (int a) inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> double SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::to_double (void) const inline
Referenced by SPUC::operator!=(), SPUC::operator<(), operator<<(), SPUC::operator<=(), SPUC::operator==(), SPUC::operator>(), and SPUC::operator>=().
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> int64_t SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::to_int (void) const inline
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> std::string SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::type_params () inline
Member Data Documentation
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> const int SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::INTEGER_BITS = INT_BITS_ static
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> const int SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::TOTAL_BITS = TOTAL_BITS_ static
template<int TOTAL_BITS_, int INT_BITS_, spuc_q_mode SPUC_Q_MODE_ = SPUC_TRN, spuc_o_mode SPUC_O_MODE_ = SPUC_WRAP> val_type SPUC::spuc_ufixed< TOTAL_BITS_, INT_BITS_, SPUC_Q_MODE_, SPUC_O_MODE_ >::val
Referenced by SPUC::operator*().
The documentation for this class was generated from the following file:
spuc_ufixed.h