SPUC: SPUC::circ_buffer< T > Class Template Reference
SPUC::circ_buffer< T > Class Template Reference
SPUC templates | Miscellaneous DSP
Circular Buffer.
#include <circ_buffer.h>
Public Member Functions
circ_buffer (void)
circ_buffer (const circ_buffer< T > &A)
circ_buffer (int d)
circ_buffer (int d, T init_value)
~circ_buffer (void)
int size (void) const
void set_size (int l)
T operator[] (int i) const
circ_buffer< T > operator= (circ_buffer< T > &A)
void put (T data_in)
void input (T d)
void reset ()
T last ()
T check (int l)
Protected Attributes
std::vector< T > buf
int len
int ptr
Detailed Description
template<class T>
class SPUC::circ_buffer< T >
Circular Buffer.
Author
Tony Kirke, Copyright(c) 2001
Tony Kirke
Constructor & Destructor Documentation
template<class T> SPUC::circ_buffer< T >::circ_buffer (void) inline
template<class T> SPUC::circ_buffer< T >::circ_buffer (const circ_buffer< T > & A)
References SPUC::circ_buffer< T >::buf, SPUC::circ_buffer< T >::len, and SPUC::circ_buffer< T >::ptr.
template<class T> SPUC::circ_buffer< T >::circ_buffer (int d)
References SPUC::circ_buffer< T >::len, and SPUC::circ_buffer< T >::ptr.
template<class T> SPUC::circ_buffer< T >::circ_buffer (int d, T init_value)
References SPUC::circ_buffer< T >::buf, SPUC::circ_buffer< T >::len, and SPUC::circ_buffer< T >::ptr.
template<class T> SPUC::circ_buffer< T >::~circ_buffer (void) inline
Member Function Documentation
template<class T> T SPUC::circ_buffer< T >::check (int l) inline
Referenced by SPUC::allpass_1< Numeric >::clock().
template<class T> void SPUC::circ_buffer< T >::input (T d) inline
Referenced by SPUC::allpass_1< Numeric >::clock(), and SPUC::iir_allpass_variable_cascade< Numeric, Coeff >::clock().
template<class T> T SPUC::circ_buffer< T >::last () inline
Referenced by SPUC::iir_allpass_variable_cascade< Numeric, Coeff >::clock().
template<class T> circ_buffer< T > SPUC::circ_buffer< T >::operator= (circ_buffer< T > & A)
References SPUC::circ_buffer< T >::buf, SPUC::circ_buffer< T >::ptr, and SPUC::circ_buffer< T >::size().
template<class T> T SPUC::circ_buffer< T >::operator[] (int i) const inline
template<class T> void SPUC::circ_buffer< T >::put (T data_in) inline
template<class T> void SPUC::circ_buffer< T >::reset (void) inline
Referenced by SPUC::allpass_1< Numeric >::reset(), SPUC::iir_allpass_variable_cascade< Numeric, Coeff >::reset(), SPUC::iir_allpass_variable_cascade< Numeric, Coeff >::set_coeffs(), and SPUC::circ_buffer< SPUC::complex< CNumeric > >::set_size().
template<class T> void SPUC::circ_buffer< T >::set_size (int l) inline
Referenced by SPUC::allpass_1< Numeric >::allpass_1(), SPUC::iir_allpass_variable_cascade< Numeric, Coeff >::iir_allpass_variable_cascade(), SPUC::allpass_1< Numeric >::init(), main(), and SPUC::iir_allpass_variable_cascade< Numeric, Coeff >::set_coeffs().
template<class T> int SPUC::circ_buffer< T >::size (void) const inline
Referenced by SPUC::circ_buffer< T >::operator=().
Member Data Documentation
template<class T> std::vector<T> SPUC::circ_buffer< T >::buf protected
Referenced by SPUC::circ_buffer< T >::circ_buffer(), and SPUC::circ_buffer< T >::operator=().
template<class T> int SPUC::circ_buffer< T >::len protected
Referenced by SPUC::circ_buffer< T >::circ_buffer(), SPUC::circ_buffer< SPUC::complex< CNumeric > >::reset(), and SPUC::circ_buffer< SPUC::complex< CNumeric > >::size().
template<class T> int SPUC::circ_buffer< T >::ptr protected
Referenced by SPUC::circ_buffer< T >::circ_buffer(), SPUC::circ_buffer< SPUC::complex< CNumeric > >::input(), SPUC::circ_buffer< T >::operator=(), and SPUC::circ_buffer< SPUC::complex< CNumeric > >::put().
The documentation for this class was generated from the following file:
circ_buffer.h