SPUC: SPUC::bit Class Reference
SPUC::bit Class Reference
#include <bit.h>
Public Member Functions
bit ()
bit (int value)
bit & operator= (const short &value)
bit & operator= (const bit &x)
bit & operator/= (const bit &x)
bit & operator|= (const bit &x)
bit & operator+= (const bit &x)
bit & operator^= (const bit &x)
bit & operator-= (const bit &x)
bit & operator*= (const bit &x)
bit & operator&= (const bit &x)
bit operator+ (const bit &x) const
bit operator^ (const bit &x) const
bit operator- (const bit &x) const
bit operator- () const
bit operator& (const bit &x) const
bit operator! (void) const
bit operator~ (void) const
bit operator| (const bit &x) const
bool operator== (const bit &x) const
bool operator== (const int &x) const
bool operator!= (const bit &x) const
bool operator!= (const int &x) const
operator short () const
operator int () const
operator bool () const
operator float () const
operator double () const
char value () const
Constructor & Destructor Documentation
SPUC::bit::bit () inline
Referenced by operator!(), operator&(), operator+(), operator-(), operator^(), operator|(), and operator~().
SPUC::bit::bit (int value) inline
Member Function Documentation
SPUC::bit::operator bool () const inline
SPUC::bit::operator double () const inline
SPUC::bit::operator float () const inline
SPUC::bit::operator int () const inline
SPUC::bit::operator short () const inline
bit SPUC::bit::operator! (void) const inline
References bit().
bool SPUC::bit::operator!= (const bit & x) const inline
bool SPUC::bit::operator!= (const int & x) const inline
bit SPUC::bit::operator& (const bit & x) const inline
References bit().
bit& SPUC::bit::operator&= (const bit & x) inline
bit& SPUC::bit::operator*= (const bit & x) inline
bit SPUC::bit::operator+ (const bit & x) const inline
References bit().
bit& SPUC::bit::operator+= (const bit & x) inline
bit SPUC::bit::operator- (const bit & x) const inline
References bit().
bit SPUC::bit::operator- () const inline
References bit().
bit& SPUC::bit::operator-= (const bit & x) inline
bit& SPUC::bit::operator/= (const bit & x) inline
bit& SPUC::bit::operator= (const short & value) inline
bit& SPUC::bit::operator= (const bit & x) inline
bool SPUC::bit::operator== (const bit & x) const inline
bool SPUC::bit::operator== (const int & x) const inline
bit SPUC::bit::operator^ (const bit & x) const inline
References bit().
bit& SPUC::bit::operator^= (const bit & x) inline
bit SPUC::bit::operator| (const bit & x) const inline
References bit().
bit& SPUC::bit::operator|= (const bit & x) inline
bit SPUC::bit::operator~ (void) const inline
References bit().
char SPUC::bit::value () const inline
The documentation for this class was generated from the following file:
bit.h