SPUC: SPUC functions
SPUC functions
Functions
void SPUC::fft (std::vector< complex< float_type > > y, int n)
fast fourier transforms (FFT)
void SPUC::idft (std::vector< complex< float_type > > y, int n)
inverse discrete fourier transforms (IDFT)
void SPUC::dft (std::vector< complex< float_type > > y, int n)
discrete fourier transforms (DFT)
void SPUC::ifft (std::vector< complex< float_type > > y, int n)
inverse fast fourier transforms (IFFT)
bool SPUC::reduce (long x, long n)
Exclusive or the bits in x together.
float_type SPUC::erfc1 (float_type x)
Standard erfc1 function.
float_type SPUC::erf1 (float_type x)
Standard erf1 function.
void SPUC::swap (int *a, int *b)
Swap two integers.
void SPUC::quicksort (int *v, unsigned n)
Quicksort routine for array of integers.
float_type SPUC::sqrt (float_type x)
sqrt
complex< float_type > SPUC::sqrt (complex< float_type > x)
sqrt
complex< float_type > SPUC::sqrt (complex< long > x)
sqrt
float_type SPUC::coshin (float_type x)
float_type SPUC::arccos (float_type x)
float_type SPUC::cosh (float_type x)
float_type SPUC::sinh (float_type x)
float_type SPUC::cos (float_type x)
complex< float_type > SPUC::cos (complex< float_type > x)
complex< float_type > SPUC::exp (complex< float_type > x)
complex exponential
float_type SPUC::hypot (complex< float_type > z)
complex< float_type > SPUC::polar (float_type amp, float_type arg)
Polar to rectangular conversion.
Detailed Description
Function Documentation
float_type SPUC::arccos (float_type x)
function for inverse cosine of x
Author
Tony Kirke
References PI, and SPUC::sqrt().
float_type SPUC::cos (float_type cos)
cos function with various overloads
Author
Tony Kirke
Referenced by SPUC::blackman(), SPUC::butterworth_fir(), SPUC::cfft::cfft(), SPUC::chebc(), SPUC::cheby(), SPUC::chebyshev_s(), SPUC::carrier_nco::clock(), SPUC::cos(), SPUC::ellik(), SPUC::ellpj(), SPUC::expj(), SPUC::fir_freq(), SPUC::freqz(), SPUC::freqz_fir(), SPUC::iir_coeff::freqz_mag(), SPUC::fir_coeff< Numeric >::freqz_mag(), SPUC::freqz_mag(), SPUC::freqz_point(), SPUC::hamming(), SPUC::hanning(), SPUC::inv_dft_symmetric(), main(), SPUC::polar(), SPUC::ptr_freqz_fir(), SPUC::ptr_freqz_mag(), SPUC::ptr_freqz_point(), SPUC::raised_cosine_imp(), SPUC::remez_fir::remez(), SPUC::root_raised_cosine_imp(), SPUC::notch_allpass< Numeric, Coeff >::set_coeffs(), SPUC::cutboost< Numeric, Coeff >::set_coeffs(), and SPUC::cutboost< Numeric, Coeff >::set_freq().
complex< float_type > SPUC::cos (complex< float_type > x)
cos function with various overloads
Author
Tony Kirke
References SPUC::cos(), SPUC::cosh(), and SPUC::sinh().
float_type SPUC::cosh (float_type x)
function for hyperbolic cosine of x
Author
Tony Kirke
References SPUC::exp().
Referenced by SPUC::chebc(), SPUC::cheby(), SPUC::chebyshev_s(), and SPUC::cos().
float_type SPUC::coshin (float_type x)
function for hyperbolic inverse cosine of x
Author
Tony Kirke
References SPUC::sqrt().
Referenced by SPUC::chebc(), and SPUC::cheby().
void SPUC::dft (std::vector< complex< float_type > > y, int n)
discrete fourier transforms (DFT)
Author
Tony Kirke
References SPUC::expj(), and TWOPI.
float_type SPUC::erf1 (float_type x)
Standard erf1 function.
Author
Tony Kirke
References SPUC::erfc1().
float_type SPUC::erfc1 (float_type x)
Standard erfc1 function.
Author
Tony Kirke
References SPUC::exp().
Referenced by SPUC::erf1().
complex< float_type > SPUC::exp (complex< float_type > x)
complex exponential
exp function with various overloads
Author
Tony Kirke
References SPUC::expj().
Referenced by SPUC::butterworth_fir(), SPUC::cosh(), SPUC::erfc1(), SPUC::find_roots(), SPUC::gaussian_fir(), SPUC::fading_channel::generate_channel(), SPUC::msqrt(), SPUC::sum_and_dump< CNumeric >::set_exp(), and SPUC::sinh().
void SPUC::fft (std::vector< complex< float_type > > y, int n)
fast fourier transforms (FFT)
Author
Tony Kirke
References SPUC::expj(), and TWOPI.
float_type SPUC::hypot (complex< float_type > z) inline
magnitude of a complex number
Author
Tony Kirke
References SPUC::magsq(), and SPUC::sqrt().
Referenced by SPUC::freqz_mag_point(), and SPUC::ptr_freqz_mag_point().
void SPUC::idft (std::vector< complex< float_type > > y, int n)
inverse discrete fourier transforms (IDFT)
Author
Tony Kirke
References SPUC::expj(), and TWOPI.
void SPUC::ifft (std::vector< complex< float_type > > y, int n)
inverse fast fourier transforms (IFFT)
Author
Tony Kirke
References SPUC::expj(), and TWOPI.
complex< float_type > SPUC::polar (float_type amp, float_type arg)
Polar to rectangular conversion.
convert from polar to cartesian
Author
Tony Kirke
References SPUC::cos().
Referenced by SPUC::bpe< Numeric, Coeff >::clock(), SPUC::other_freq(), SPUC::sqrt(), and SPUC::z_freqz_db().
void SPUC::quicksort (int * v, unsigned n)
Quicksort routine for array of integers.
Author
Tony Kirke
References SPUC::swap().
bool SPUC::reduce (long x, long n)
Exclusive or the bits in x together.
Author
Tony Kirke
Referenced by SPUC::data_conv_encoder::conv_encoder().
float_type SPUC::sinh (float_type x)
function for hyperbolic sine of x
Author
Tony Kirke
References SPUC::exp().
Referenced by SPUC::chebyshev_s(), and SPUC::cos().
float_type SPUC::sqrt (float_type x)
sqrt
Author
Tony Kirke
Referenced by SPUC::arccos(), SPUC::butterworth_fir(), SPUC::noise::Cgauss(), SPUC::chebyshev_s(), SPUC::coshin(), SPUC::ellik(), SPUC::elliptic_allpass(), SPUC::elliptic_iir(), SPUC::ellpj(), SPUC::ellpk(), SPUC::find_roots(), SPUC::fir_freq(), SPUC::iir_coeff::freqz_mag(), SPUC::fir_coeff< Numeric >::freqz_mag(), SPUC::noise::gauss(), SPUC::gaussian_fir(), SPUC::fading_channel::generate_channel(), SPUC::hypot(), SPUC::kaiser(), SPUC::qam_tx< float_type >::loop_init(), SPUC::baud_eq_env< Numeric >::loop_init(), SPUC::sim_qpsk< Numeric >::loop_init(), SPUC::sim_qpsk_variable< Numeric >::loop_init(), SPUC::sim_qam< Numeric >::loop_init(), main(), SPUC::msqrt(), SPUC::normalized(), SPUC::iir_coeff::pz_to_ap(), SPUC::rv_stat::rms(), SPUC::sqrt(), and SPUC::rv_stat::std().
complex< float_type > SPUC::sqrt (complex< float_type > x)
sqrt
Author
Tony Kirke
References SPUC::arg(), SPUC::magsq(), SPUC::polar(), and SPUC::sqrt().
complex< float_type > SPUC::sqrt (complex< long > x)
sqrt
Author
Tony Kirke
References SPUC::arg(), SPUC::magsq(), SPUC::polar(), and SPUC::sqrt().
void SPUC::swap (int * a, int * b)
Swap two integers.
Author
Tony Kirke
Referenced by SPUC::quicksort().