SPUC: Simulation classes And functions
Simulation classes And functions
Classes
class SPUC::a_d
An A/D conversion class.
class SPUC::base_demod< Numeric >
base class for a demodulator (not currently used?)
class SPUC::baud_eq_env< Numeric >
Class for doing a simulation of an equalizer running at 1 sample/symbol.
class SPUC::bpsk_ber_test
A Class for simulating a BPSK system.
class SPUC::fading_channel
class SPUC::fbool_nco< M, L >
Template class for a NCO based on template unsigned int class.
class SPUC::fnco< M >
Template class for a NCO based on template unsigned int class.
class SPUC::qnoise< Numeric >
class to add quantization noise to signal
class SPUC::qpsk_ber_test
A Class for doing BER test on QPSK.
class SPUC::quantiser< Numeric >
........
class SPUC::sim_qam< Numeric >
A Class for simulating a QAM system.
class SPUC::sim_qpsk< Numeric >
A Class for simulating a QPSK system that includes.
class SPUC::sim_qpsk_variable< Numeric >
A Class for simulating a variable rate QPSK system.
class SPUC::timing_nco
A NCO for symbol recovery in a variable rate QPSK receiver.
class SPUC::vco< Numeric >
Voltage controlled oscillator with complex output.
Functions
int main (int argc, char *argv[])
Simulation of QPSK receiver in AWGN.
Detailed Description
Function Documentation
int main (int argc, char * argv[])
Simulation of QPSK receiver in AWGN.
References SPUC::sim_qpsk< Numeric >::BER_mon, SPUC::qpsk_ber_test::ber_results(), CAR_LOOP_ON, SPUC::qpsk_ber_test::final_results(), SPUC::qpsk_ber_test::found_sync(), SPUC::sim_qpsk< Numeric >::freq, SPUC::qpsk_ber_test::init_delay(), SPUC::sim_qpsk< Numeric >::loop_end(), SPUC::sim_qpsk< Numeric >::loop_init(), SPUC::sim_qpsk< Numeric >::num, SPUC::sim_qpsk< Numeric >::rcv_symbols, SPUC::sim_qpsk< Numeric >::RECEIVER, SPUC::noise::set_seed(), SPUC::sim_qpsk< Numeric >::snr, SPUC::sim_qpsk< Numeric >::step(), SYM_LOOP_ON, SPUC::qpsk_ber_test::synchronize(), SPUC::sim_qpsk< Numeric >::time, SPUC::noise::uni(), and WAITSYMBOLS.