SPUC: Miscellaneous DSP
Miscellaneous DSP
Classes
class SPUC::a_d
An A/D conversion class.
class SPUC::circ_buffer< T >
Circular Buffer.
class SPUC::cordic< Numeric >
Cordic rotator.
class SPUC::delay< Numeric >
Template class for Delay line.
class SPUC::fixed_delay< Numeric, D >
Template class for Delay line with Fixed Delay.
class SPUC::max_pn
Maximal Length Pseudorandom sequence generator.
class SPUC::noise
Gaussian noise routine.
class SPUC::qnoise< Numeric >
class to add quantization noise to signal
class SPUC::quantiser< Numeric >
........
class SPUC::rv_stat
a basic random Variable Statistics Class
class SPUC::sigma_delta
Simple 1st order All-digital Sigma Delta converter.
Typedefs
typedef complex< float_type > SPUC::CPLX
General Purpose C++ complex FFT Transform.
Functions
template<class T >
std::vector< T > SPUC::auto_corr (const std::vector< T > &x)
Compute the autocorrelation of the Vector.
template<class T >
std::vector< T > SPUC::burg (std::vector< T > x, int P)
AR model coefficients calculation using Burg algorithm.
template<typename T >
T SPUC::conj (T in)
Templated conjugate function template function that uses a class to allow template specialization.
template<class T >
std::vector< T > SPUC::convolve (const std::vector< T > &x, const std::vector< T > &y)
std::vector< complex
< float_type > > SPUC::find_roots (const std::vector< float_type > &a, long n)
Calculate the complex roots of a polynomial equation.
template<class T >
std::vector< T > SPUC::fliplr (const std::vector< T > &x)
fliplr - same as matlab function
template<class T >
complex< float_type > SPUC::freqz_point (std::vector< T > b, std::vector< T > a, float_type freq, int N)
frequency transfer function at freq with iir A and B equations
template<class T >
float_type SPUC::freqz_mag_point (std::vector< T > x, float_type freq, int N)
frequency magnitude function at freq with fir x
template<class T >
complex< float_type > SPUC::freqz_point (T a, float_type freq)
frequency transfer function at freq for 1st order allpass
template<class T >
std::vector< complex
< float_type > > SPUC::freqz (std::vector< T > b, std::vector< T > a, int pts)
frequency transfer function over "pts" points for IIR
template<class T >
std::vector< complex
< float_type > > SPUC::freqz_mag (std::vector< T > b, std::vector< T > a, int pts)
frequency magnitude function over "pts" points for IIR
template<class T >
std::vector< complex
< float_type > > SPUC::freqz_fir (std::vector< T > x, int pts)
frequency magnitude function over "pts" points for FIR
template<class T >
std::vector< T > SPUC::levdur (std::vector< T > R)
Template class for Levinson-Durbin algorithm.
template<typename T >
base_type< T >::btype SPUC::magsq (T in)
Templated Magnitude Squared function template function that uses a class to allow template specialization.
template<class T >
std::vector< T > SPUC::partial_convolve (const std::vector< T > &x, const std::vector< T > &y, int N, int M)
template<class T >
complex< float_type > SPUC::ptr_freqz_point (T *b, T *a, float_type freq, int N)
frequency transfer function at freq with iir A and B equations
template<class T >
float_type SPUC::ptr_freqz_mag_point (T *x, float_type freq, int N)
frequency magnitude function at freq with fir x
template<class T >
complex< float_type > SPUC::ptr_freqz_point (T a, float_type freq)
frequency transfer function at freq for 1st order allpass
template<class T >
void SPUC::freqz (complex< float_type > *f, T *b, T *a, int N, int pts)
frequency transfer function over "pts" points for IIR
template<class T >
void SPUC::ptr_freqz_mag (float_type *f, T *b, T *a, int N, int pts)
frequency magnitude function over "pts" points for IIR
template<class T >
void SPUC::ptr_freqz_fir (complex< float_type > *f, T *x, int N, int pts)
frequency magnitude function over "pts" points for FIR
template<typename T >
quantized_type< T >::dtype SPUC::quantize (T in)
Templated Quantize function template function that uses a class to allow template specialization.
template<class T >
long SPUC::real_quantize (T in)
Templated quantize function.
template<class T >
T SPUC::real_round (T in, long bits)
Templated round function.
template<class T >
T SPUC::real_saturate (T in, long bits)
Templated saturation functions.
template<>
long SPUC::real_saturate (long in, long bits)
Templated saturation functions.
template<class T >
T SPUC::round (T in, long bits)
Templated round function template function that uses a class to allow template specialization.
template<class T >
T SPUC::saturate (T in, long bits)
Templated saturate function template function that uses a class to allow template specialization.
template<typename T >
T SPUC::signbit (T in)
Templated signbit function template function that uses a class to allow template specialization.
template<class T >
void SPUC::toeplitz (vector< T > x, matrix< T > &A)
Get Symmetric Toeplitz matrix from vector.
SPUC::cfft::cfft (int size, float_type scalef1=0.5, float_type scalef2=1.0, float_type scalei1=1.0, float_type scalei2=1.0)
General Purpose C++ complex FFT Transform.
Detailed Description
Typedef Documentation
typedef complex<float_type> SPUC::CPLX
General Purpose C++ complex FFT Transform.
This is a general-purpose C++ complex FFT transform class. it is defined as a template over a complex type. For instance, if using gnu gcc, the complex type is complex<float_type> And you declare the cfft class as cfft<complex<float_type>>
The underlying CPLX type requires: CPLX() operator = , CPLX(CPLX const&) CPLX(float_type,float_type) [used on cos/sin] CPLX operator*(CPLX , float_type) CPLX conj(CPLX const &); [conjugate] ComPlex::operator @ (CPLX , CPLX) [ where @ =* + - ]
Author
Tony Kirke
Function Documentation
template<class T > std::vector<T> SPUC::auto_corr (const std::vector< T > & x)
Compute the autocorrelation of the Vector.
Author
Tony Kirke, Copyright(c) 2001
Tony Kirke
Referenced by main().
template<class T > std::vector<T> SPUC::burg (std::vector< T > x, int P)
AR model coefficients calculation using Burg algorithm.
Author
Tony Kirke, Copyright(c) 2001
Tony Kirke
References SPUC::conj(), and SPUC::magsq().
SPUC::cfft::cfft (int size, float_type scalef1 = 0.5, float_type scalef2 = 1.0, float_type scalei1 = 1.0, float_type scalei2 = 1.0)
General Purpose C++ complex FFT Transform.
References SPUC::conj(), SPUC::cos(), and PI.
template<typename T > T SPUC::conj (T in)
Templated conjugate function template function that uses a class to allow template specialization.
Author
Tony Kirke
Referenced by SPUC::rls< Numeric >::adapt(), SPUC::burg(), SPUC::cfft::cfft(), SPUC::dd_symbol(), SPUC::cfft::hermitian(), SPUC::qpsk_dd_phase(), SPUC::fir_adapt< Numeric, Numeric >::update_lms(), and SPUC::fir_adapt< Numeric, Numeric >::update_lms_sign_coeff().
template<class T > std::vector<T> SPUC::convolve (const std::vector< T > & x, const std::vector< T > & y)
Author
Tony Kirke, Copyright(c) 2001
Tony Kirke
References M.
Referenced by SPUC::iir_coeff::pz_to_ap().
std::vector< complex< float_type > > SPUC::find_roots (const std::vector< float_type > & a, long n)
Calculate the complex roots of a polynomial equation.
Author
Tony Kirke
References SPUC::exp(), and SPUC::sqrt().
Referenced by main(), and SPUC::iir_coeff::pz_to_ap().
template<class T > std::vector<T> SPUC::fliplr (const std::vector< T > & x)
fliplr - same as matlab function
Author
Tony Kirke
Referenced by SPUC::iir_coeff::pz_to_ap().
template<class T > void SPUC::freqz (complex< float_type > * f, T * b, T * a, int N, int pts)
frequency transfer function over "pts" points for IIR
Author
Tony Kirke
References SPUC::cos(), and PI.
template<class T > std::vector<complex<float_type> > SPUC::freqz (std::vector< T > b, std::vector< T > a, int pts)
frequency transfer function over "pts" points for IIR
Author
Tony Kirke
References SPUC::cos(), and PI.
template<class T > std::vector<complex<float_type> > SPUC::freqz_fir (std::vector< T > x, int pts)
frequency magnitude function over "pts" points for FIR
Author
Tony Kirke
References SPUC::cos(), and PI.
template<class T > std::vector<complex<float_type> > SPUC::freqz_mag (std::vector< T > b, std::vector< T > a, int pts)
frequency magnitude function over "pts" points for IIR
Author
Tony Kirke
References SPUC::cos(), SPUC::magsq(), and PI.
template<class T > float_type SPUC::freqz_mag_point (std::vector< T > x, float_type freq, int N)
frequency magnitude function at freq with fir x
Author
Tony Kirke
References SPUC::expj(), and SPUC::hypot().
template<class T > complex<float_type> SPUC::freqz_point (std::vector< T > b, std::vector< T > a, float_type freq, int N)
frequency transfer function at freq with iir A and B equations
Author
Tony Kirke
References SPUC::cos().
template<class T > complex<float_type> SPUC::freqz_point (T a, float_type freq)
frequency transfer function at freq for 1st order allpass
Author
Tony Kirke
References SPUC::cos(), and SPUC::normalized().
template<class T > std::vector<T> SPUC::levdur (std::vector< T > R)
Template class for Levinson-Durbin algorithm.
<font color="red">Under construction!</font>
Author
Tony Kirke
template<typename T > base_type< T >::btype SPUC::magsq (T in)
Templated Magnitude Squared function template function that uses a class to allow template specialization.
Author
Tony Kirke
References SPUC::magsqr< T >::magsqd().
Referenced by SPUC::burg(), SPUC::cic_freq(), SPUC::mle< Numeric >::estimate(), SPUC::fir_freq(), SPUC::iir_coeff::freqz_mag(), SPUC::fir_coeff< Numeric >::freqz_mag(), SPUC::freqz_mag(), SPUC::hypot(), main(), SPUC::other_freq(), SPUC::ptr_freqz_mag(), SPUC::iir_coeff::pz_to_ap(), SPUC::iir_coeff::pz_to_poly(), SPUC::sqrt(), SPUC::qpsk_discriminators::symbol_lock_out(), SPUC::sim_qpsk_variable< Numeric >::tx_step(), SPUC::equalizer::update_levels(), SPUC::fast_equalizer::update_levels(), SPUC::z_freqz_db(), and SPUC::iir_coeff::z_root_to_ab().
template<class T > std::vector<T> SPUC::partial_convolve (const std::vector< T > & x, const std::vector< T > & y, int N, int M)
Author
Tony Kirke, Copyright(c) 2001
Tony Kirke
References M.
Referenced by SPUC::iir_coeff::p2_to_poly(), and SPUC::iir_coeff::pz_to_poly().
template<class T > void SPUC::ptr_freqz_fir (complex< float_type > * f, T * x, int N, int pts)
frequency magnitude function over "pts" points for FIR
Author
Tony Kirke
References SPUC::cos(), and PI.
template<class T > void SPUC::ptr_freqz_mag (float_type * f, T * b, T * a, int N, int pts)
frequency magnitude function over "pts" points for IIR
Author
Tony Kirke
References SPUC::cos(), SPUC::magsq(), and PI.
template<class T > float_type SPUC::ptr_freqz_mag_point (T * x, float_type freq, int N)
frequency magnitude function at freq with fir x
Author
Tony Kirke
References SPUC::expj(), and SPUC::hypot().
template<class T > complex<float_type> SPUC::ptr_freqz_point (T * b, T * a, float_type freq, int N)
frequency transfer function at freq with iir A and B equations
Author
Tony Kirke
References SPUC::cos().
template<class T > complex<float_type> SPUC::ptr_freqz_point (T a, float_type freq)
frequency transfer function at freq for 1st order allpass
Author
Tony Kirke
References SPUC::cos(), and SPUC::normalized().
template<typename T > quantized_type<T>::dtype SPUC::quantize (T in)
Templated Quantize function template function that uses a class to allow template specialization.
Author
Tony Kirke
References SPUC::quantizer< Numeric >::quantized().
template<class T > long SPUC::real_quantize (T in)
Templated quantize function.
Author
Tony Kirke
References SPUC_TOLONG.
Referenced by SPUC::quantizer< Numeric >::quantized(), SPUC::quantizer< complex< T > >::quantized(), SPUC::quantizer< Numeric >::quantized_scale(), and SPUC::quantizer< complex< T > >::quantized_scale().
template<class T > T SPUC::real_round (T in, long bits)
Templated round function.
Author
Tony Kirke
Referenced by SPUC::rounder< Numeric >::rounded(), and SPUC::rounder< complex< T > >::rounded().
template<class T > T SPUC::real_saturate (T in, long bits)
Templated saturation functions.
Author
Tony Kirke
Referenced by SPUC::saturater< Numeric >::saturated(), and SPUC::saturater< complex< T > >::saturated().
template<> long SPUC::real_saturate (long in, long bits) inline
Templated saturation functions.
Author
Tony Kirke
References SPUC::ABS().
template<class T > T SPUC::round (T in, long bits)
Templated round function template function that uses a class to allow template specialization.
Author
Tony Kirke
Referenced by SPUC::iir_allpass2< Numeric, Coeff >::clock(), SPUC::iir_delay_allpass1< Numeric, Coeff >::clock(), SPUC::iir_allpass1_halfband< SPUC::complex< CNumeric > >::clock(), SPUC::iir_allpass1< Numeric, Coeff >::clock(), SPUC::nested_shelf_allpass_2< Numeric, Coeff >::clock(), SPUC::nested_iir_allpass_2< Numeric, Coeff >::clock(), SPUC::qpsk< Numeric >::clock(), SPUC::iir_allpass_variable_cascade< Numeric, Coeff >::clock(), SPUC::iir_allpass1_cascade< Numeric, Coeff >::clock(), SPUC::qpsk_variable< Numeric >::clock(), SPUC::iir_allpass1_cascade< Numeric, Coeff >::get_hp_out(), and SPUC::iir_allpass_variable_cascade< Numeric, Coeff >::get_hp_out().
template<class T > T SPUC::saturate (T in, long bits)
Templated saturate function template function that uses a class to allow template specialization.
Author
Tony Kirke
Referenced by SPUC::qpsk_variable< Numeric >::clock(), and SPUC::qpsk_discriminators::pll_disc().
template<typename T > T SPUC::signbit (T in)
Templated signbit function template function that uses a class to allow template specialization.
Author
Tony Kirke
Referenced by SPUC::qpsk< Numeric >::clock(), SPUC::qpsk_variable< Numeric >::clock(), SPUC::fir_adapt< Numeric, Numeric >::update_lms(), and SPUC::fir_adapt< Numeric, Numeric >::update_lms_sign_coeff().
template<class T > void SPUC::toeplitz (vector< T > x, matrix< T > & A)
Get Symmetric Toeplitz matrix from vector.
Author
Tony Kirke, Copyright(c) 2001
Tony Kirke
References SPUC::vector< T >::size().