SPUC: qpsk_variable_main.cpp File Reference
qpsk_variable_main.cpp File Reference
#include <stdio.h>
#include <spuc/spuc_math.h>
#include <spuc/sim_qpsk_variable.h>
#include <spuc/noise.h>
Macros
#define SYM_LOOP_ON 10
#define CAR_LOOP_ON 1000
#define WAITSYMBOLS 15000
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
#define CAR_LOOP_ON 1000
Referenced by main().
#define SYM_LOOP_ON 10
Referenced by main().
#define WAITSYMBOLS 15000
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
References SPUC::sim_qpsk_variable< Numeric >::agc_scale, SPUC::sim_qpsk_variable< Numeric >::base, SPUC::sim_qpsk_variable< Numeric >::BER_mon, SPUC::qpsk_ber_test::ber_results(), CAR_LOOP_ON, SPUC::qpsk_ber_test::final_results(), SPUC::qpsk_ber_test::found_sync(), SPUC::qpsk_ber_test::init_delay(), SPUC::sim_qpsk_variable< Numeric >::loop_end(), SPUC::sim_qpsk_variable< Numeric >::loop_init(), SPUC::magsq(), SPUC::sim_qpsk_variable< Numeric >::num, SPUC::sim_qpsk_variable< Numeric >::rcv_symbols, SPUC::sim_qpsk_variable< Numeric >::RECEIVER, SPUC::noise::set_seed(), SPUC::sim_qpsk_variable< Numeric >::snr, SPUC::sqrt(), SPUC::sim_qpsk_variable< Numeric >::step(), SPUC::sim_qpsk_variable< Numeric >::sum_n, SPUC::sim_qpsk_variable< Numeric >::sum_s, SYM_LOOP_ON, SPUC::qpsk_ber_test::synchronize(), SPUC::noise::uni(), and WAITSYMBOLS.