SPUC: test_sint2.cpp File Reference
test_sint2.cpp File Reference
#include <iostream>
#include <fstream>
#include <iomanip>
#include <spuc/sint.h>
#include <spuc/iir_2nd.h>
#include <spuc/iir.h>
#include <spuc/butterworth_iir.h>
#include <spuc/delay.h>
Macros
#define OK
Functions
int main (int argv, char *argc[])
Macro Definition Documentation
#define OK
Function Documentation
int main (int argv, char * argc[])
References SPUC::butterworth_iir(), SPUC::iir_2nd< Numeric, Coeff >::clock(), SPUC::iir_2nd< Numeric, Coeff >::fb2, SPUC::iir_coeff::get_root(), SPUC::complex< T >::im, SPUC::iir_2nd< Numeric, Coeff >::print(), SPUC::iir< Numeric, Coeff >::print(), SPUC::iir_coeff::quantize(), SPUC::complex< T >::re, SPUC::iir_2nd< Numeric, Coeff >::set_coeffs(), and SPUC::iir_2nd< Numeric, Coeff >::set_round_bits().