SPUC: test_filters.cpp File Reference
test_filters.cpp File Reference
#include <iostream>
#include <fstream>
#include <iomanip>
#include <spuc/fir_coeff.h>
#include <spuc/remez_fir.h>
#include <spuc/gaussian_fir.h>
#include <spuc/butterworth_fir.h>
#include <spuc/create_remez_lpfir.h>
#include <spuc/iir_allpass1.h>
#include <spuc/iir_allpass1_cascade.h>
#include <spuc/freqz.h>
Macros
#define PTS 200
Functions
int main (int argv, char *argc[])
testing various types of filters
Macro Definition Documentation
#define PTS 200
Referenced by main().
Function Documentation
int main (int argv, char * argc[])
testing various types of filters
References SPUC::butterworth_fir(), SPUC::iir_allpass1_cascade< Numeric, Coeff >::clock(), SPUC::create_remez_lpfir(), SPUC::gaussian_fir(), SPUC::magsq(), SPUC::fir_coeff< Numeric >::print(), and PTS.