SPUC: test_speed.cpp File Reference
test_speed.cpp File Reference
#include <math.h>
#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <spuc/noise.h>
#include <spuc/fir.h>
#include <sys/time.h>
#include <spuc/spuc_fixed.h>
Functions
double get_time ()
int main (int argc, char *argv[])
Function Documentation
double get_time ()
Referenced by main().
int main (int argc, char * argv[])
References SPUC::arg(), SPUC::cos(), SPUC::expj(), and get_time().