SPUC: test_ddfse.cpp File Reference
test_ddfse.cpp File Reference
#include <iostream>
#include <fstream>
#include <iomanip>
#include <stdlib.h>
#include <spuc/complex.h>
#include <spuc/baud_eq_env.h>
#include <spuc/noise.h>
Macros
#define EQTYPE 0
Functions
int main (int argc, char *argv[])
Baud rate equalization simulation.
Macro Definition Documentation
#define EQTYPE 0
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Baud rate equalization simulation.
BPSK (real) data is corrupted with a multipath channel (delay spread = baud rate?) with L (programmable) number of taps Noise is added and this program generates BER data over a range of SNR points with a MLSE (Viterbi) Equalizer with 2^L states TYPE 1 == DDFSE
References SPUC::bpsk_ber_test::ber(), SPUC::baud_eq_env< Numeric >::BER_mon, SPUC::baud_eq_env< Numeric >::data, EQTYPE, SPUC::fading_channel::exp_decay, SPUC::bpsk_ber_test::final_results(), SPUC::bpsk_ber_test::found_sync(), SPUC::baud_eq_env< Numeric >::loop_end(), SPUC::baud_eq_env< Numeric >::loop_init(), SPUC::baud_eq_env< Numeric >::multipaths, SPUC::baud_eq_env< Numeric >::num, SPUC::baud_eq_env< Numeric >::rcv_symbols, SPUC::noise::set_seed(), SPUC::baud_eq_env< Numeric >::snr, SPUC::baud_eq_env< Numeric >::step(), and SPUC::bpsk_ber_test::synchronize().