SPUC: test_q.cpp File Reference
test_q.cpp File Reference
#include <iostream>
#include <fstream>
#include <iomanip>
#include <spuc/equalizer.h>
Macros
#define NEW_WAY_B
Functions
int main (int argc, char *argv[])
testing graphic equalizer
Macro Definition Documentation
#define NEW_WAY_B
Function Documentation
int main (int argc, char * argv[])
testing graphic equalizer
References SPUC::iir_allpass_variable_cascade< Numeric, Coeff >::clock(), SPUC::iir_allpass_variable_cascade< Numeric, Coeff >::set_coeffs(), SPUC::circ_buffer< T >::set_size(), and SPUC::delay< Numeric >::set_size().