SPUC: test_sint.cpp File Reference
test_sint.cpp File Reference
#include <iostream>
#include <fstream>
#include <iomanip>
#include <spuc/sint.h>
#include <spuc/fpint.h>
#include <spuc/iir_2nd.h>
#include <spuc/iir.h>
#include <spuc/butterworth_iir.h>
Functions
int main (int argv, char *argc[])
Function Documentation
int main (int argv, char * argc[])
References SPUC::butterworth_iir(), SPUC::iir_2nd< Numeric, Coeff >::clock(), SPUC::iir_coeff::get_root(), SPUC::complex< T >::im, SPUC::iir_2nd< Numeric, Coeff >::print(), SPUC::iir< Numeric, Coeff >::print(), SPUC::complex< T >::re, and SPUC::iir_2nd< Numeric, Coeff >::set_round_bits().