SPUC: test_dump.cpp File Reference
test_dump.cpp File Reference
#include <iostream>
#include <fstream>
#include <iomanip>
#include <spuc/iir_2nd.h>
#include <spuc/iir.h>
#include <spuc/butterworth_iir.h>
Functions
int main (int argv, char *argc[])
Function Documentation
int main (int argv, char * argc[])
References SPUC::butterworth_iir(), SPUC::iir_coeff::get_root(), SPUC::iir_2nd< Numeric, Coeff >::print(), SPUC::iir< Numeric, Coeff >::print(), SPUC::iir_coeff::quantize(), and SPUC::iir_2nd< Numeric, Coeff >::set_round_bits().