SPUC: test_mlse.cpp File Reference
test_mlse.cpp File Reference
#include <spuc/max_pn.h>
#include <spuc/delay.h>
#include <spuc/fir.h>
#include <spuc/mle.h>
#include <iostream>
#include <fstream>
#include <iomanip>
Functions
int main (int argv, char *argc[])
Function Documentation
int main (int argv, char * argc[])
References SPUC::mle< Numeric >::cfir, SPUC::fir< Numeric, Coeff >::coeff, SPUC::mle< Numeric >::mlsd(), SPUC::max_pn::out(), SPUC::fir< Numeric, Coeff >::settap(), SPUC::delay< Numeric >::update(), and SPUC::fir< Numeric, Coeff >::update().