SPUC: test_iir.cpp File Reference
test_iir.cpp File Reference
#include <iostream>
#include <fstream>
#include <iomanip>
#include <spuc/butterworth_iir.h>
#include <spuc/elliptic_iir.h>
#include <spuc/iir.h>
#include <spuc/iir_2nd.h>
#include <spuc/spuc_fp.h>
Functions
int main (int argv, char *argc[])
testing various types for IIR
Function Documentation
int main (int argv, char * argc[])
testing various types for IIR
References SPUC::iir_coeff::a_tf, SPUC::iir_coeff::b_tf, SPUC::butterworth_iir(), SPUC::iir< Numeric, Coeff >::clock(), SPUC::iir_coeff::poles, SPUC::iir< Numeric, Coeff >::print(), and SPUC::iir_coeff::zeros.