SPUC: test_iir2nd.cpp File Reference
test_iir2nd.cpp File Reference
#include <iostream>
#include <fstream>
#include <iomanip>
#include <spuc/butterworth_iir.h>
#include <spuc/elliptic_iir.h>
#include <spuc/iir.h>
#include <spuc/iir_2nd.h>
Functions
int main (int argv, char *argc[])
testing various types for 2nd order IIR
Function Documentation
int main (int argv, char * argc[])
testing various types for 2nd order IIR
References SPUC::butterworth_iir(), SPUC::iir_2nd< Numeric, Coeff >::clock(), SPUC::elliptic_iir(), SPUC::iir_coeff::get_coeff_a(), SPUC::iir_2nd< Numeric, Coeff >::print(), and SPUC::iir< Numeric, Coeff >::print().