#pragma once
#include <iostream>
#include <spuc/spuc_defines.h>
#include <cmath>
#include <spuc/conj.h>
#include <spuc/signbit.h>
#include <spuc/magsq.h>
#include <spuc/builtin.h>
#define ASP_C(x) 
#include <complex>
using std::complex;
#include <spuc/complex_functions.h>
