#include <spuc/a_d.h>
#include <spuc/afile.h>
#include <spuc/afile_rw.h>
#include <spuc/agc.h>
#include <spuc/allpass.h>
#include <spuc/allpass_1.h>
#include <spuc/allpass_1aq1.h>
#include <spuc/allpass_1aq2.h>
#include <spuc/allpass_2nd.h>
#include <spuc/array.h>
#include <spuc/array1d.h>
#include <spuc/array2d.h>
#include <spuc/auto_corr.h>
#include <spuc/base_demod.h>
#include <spuc/base_type.h>
#include <spuc/baud_eq_env.h>
#include <spuc/bit.h>
#include <spuc/bit_scrambler.h>
#include <spuc/bpe.h>
#include <spuc/bpsk_ber_test.h>
#include <spuc/bpsk_dd_phase.h>
#include <spuc/bpsk_quadricorrelator.h>
#include <spuc/btsc_dec.h>
#include <spuc/btsc_dec_defines.h>
#include <spuc/btsc_defines.h>
#include <spuc/btsc_demod.h>
#include <spuc/btsc_enc.h>
#include <spuc/btsc_fixed_de_emph.h>
#include <spuc/btsc_fixed_pre_emph.h>
#include <spuc/btsc_gain_control.h>
#include <spuc/btsc_lmr_demod.h>
#include <spuc/btsc_receiver.h>
#include <spuc/btsc_sap_demod.h>
#include <spuc/btsc_sf_de_emph.h>
#include <spuc/btsc_sf_pre_emph.h>
#include <spuc/btsc_spectral_compression.h>
#include <spuc/btsc_spectral_control.h>
#include <spuc/btsc_spectral_expansion.h>
#include <spuc/btsc_transmitter.h>
#include <spuc/builtin.h>
#include <spuc/burg.h>
#include <spuc/butterworth_allpass.h>
#include <spuc/butterworth_fir.h>
#include <spuc/butterworth_iir.h>
#include <spuc/carrier_nco.h>
#include <spuc/cfft.h>
#include <spuc/chebyshev_iir.h>
#include <spuc/cic.h>
#include <spuc/circ_buffer.h>
#include <spuc/complex.h>
#include <spuc/complex_class.h>
#include <spuc/complex_functions.h>
#include <spuc/complex_io.h>
#include <spuc/complex_operators.h>
#include <spuc/conj.h>
#include <spuc/conjr.h>
#include <spuc/convolutional_interleaver.h>
#include <spuc/convolve.h>
#include <spuc/cordic.h>
#include <spuc/cp_afc.h>
#include <spuc/create_remez_lpfir.h>
#include <spuc/cutboost.h>
#include <spuc/data_conv_encoder.h>
#include <spuc/dbx_dec.h>
#include <spuc/dbx_enc.h>
#include <spuc/dd_symbol.h>
#include <spuc/delay.h>
#include <spuc/dqpsk.h>
#include <spuc/dvb_conv_encoder.h>
#include <spuc/elliptic_allpass.h>
#include <spuc/elliptic_iir.h>
#include <spuc/fading_channel.h>
#include <spuc/farrow.h>
#include <spuc/farrow_upsampler.h>
#include <spuc/fbool_nco.h>
#include <spuc/fft.h>
#include <spuc/find_roots.h>
#include <spuc/fir.h>
#include <spuc/fir_adapt.h>
#include <spuc/fir_coeff.h>
#include <spuc/fir_decim.h>
#include <spuc/fir_interp.h>
#include <spuc/fir_inv_dft.h>
#include <spuc/fliplr.h>
#include <spuc/fm_demod.h>
#include <spuc/fnco.h>
#include <spuc/fpint.h>
#include <spuc/freqz.h>
#include <spuc/fundtype.h>
#include <spuc/fxd.h>
#include <spuc/gaussian_fir.h>
#include <spuc/idft.h>
#include <spuc/ifft.h>
#include <spuc/iir.h>
#include <spuc/iir_1st.h>
#include <spuc/iir_2nd.h>
#include <spuc/iir_allpass1.h>
#include <spuc/iir_allpass1_cascade.h>
#include <spuc/iir_allpass1_halfband.h>
#include <spuc/iir_allpass2.h>
#include <spuc/iir_coeff.h>
#include <spuc/iir_comb.h>
#include <spuc/iir_delay_allpass1.h>
#include <spuc/iir_df.h>
#include <spuc/iir_exp1.h>
#include <spuc/iir_hpf.h>
#include <spuc/iir_hpf1.h>
#include <spuc/iir_lpf.h>
#include <spuc/iir_lpf1.h>
#include <spuc/iir_shelf.h>
#include <spuc/int_s.h>
#include <spuc/int_u.h>
#include <spuc/lagrange.h>
#include <spuc/levdur.h>
#include <spuc/lms_dfe.h>
#include <spuc/loop_filter.h>
#include <spuc/magsq.h>
#include <spuc/magsqr.h>
#include <spuc/matrix.h>
#include <spuc/max_pn.h>
#include <spuc/misc.h>
#include <spuc/mixed_type.h>
#include <spuc/mle.h>
#include <spuc/nco.h>
#include <spuc/nda_symbol.h>
#include <spuc/noise.h>
#include <spuc/notch_allpass.h>
#include <spuc/notch_example.h>
#include <spuc/notch_iir.h>
#include <spuc/ofdm_data_encoder.h>
#include <spuc/partial_convolve.h>
#include <spuc/ptr_freqz.h>
#include <spuc/qam_conv_decoder.h>
#include <spuc/qam_mod.h>
#include <spuc/qam_soft_decision.h>
#include <spuc/qam_tx.h>
#include <spuc/qnoise.h>
#include <spuc/qpsk.h>
#include <spuc/qpsk_ber_test.h>
#include <spuc/qpsk_dd_phase.h>
#include <spuc/qpsk_discriminators.h>
#include <spuc/qpsk_quadricorrelator.h>
#include <spuc/qpsk_rcfd.h>
#include <spuc/qpsk_variable.h>
#include <spuc/quad_data.h>
#include <spuc/quant.h>
#include <spuc/quantiser.h>
#include <spuc/quantize.h>
#include <spuc/quantized_type.h>
#include <spuc/quantizer.h>
#include <spuc/raised_cosine.h>
#include <spuc/raised_cosine_imp.h>
#include <spuc/real_quantize.h>
#include <spuc/real_round.h>
#include <spuc/real_saturate.h>
#include <spuc/remez_fir.h>
#include <spuc/resampler.h>
#include <spuc/rls.h>
#include <spuc/root_raised_cosine.h>
#include <spuc/root_raised_cosine_imp.h>
#include <spuc/round.h>
#include <spuc/rounder.h>
#include <spuc/running_sum.h>
#include <spuc/rv_stat.h>
#include <spuc/saturate.h>
#include <spuc/saturater.h>
#include <spuc/scic.h>
#include <spuc/sigma_delta.h>
#include <spuc/signbit.h>
#include <spuc/signbitr.h>
#include <spuc/sim_qam.h>
#include <spuc/sim_qpsk.h>
#include <spuc/sim_qpsk_variable.h>
#include <spuc/sint.h>
#include <spuc/smart_array.h>
#include <spuc/spuc_defines.h>
#include <spuc/spuc_math.h>
#include <spuc/spuc_typedefs.h>
#include <spuc/spuc_types.h>
#include <spuc/sum_and_dump.h>
#include <spuc/timing_nco.h>
#include <spuc/toeplitz.h>
#include <spuc/uint.h>
#include <spuc/unquantized_mixed_type.h>
#include <spuc/unquantized_type.h>
#include <spuc/vco.h>
#include <spuc/vector.h>
#include <spuc/vfixed.h>
#include <spuc/vfloat.h>
#include <spuc/viterbi.h>
#include <spuc/vlog.h>
#include <spuc/window.h>
//! \file 
//! \brief Automatically generated header file includes all other header files

